### PR TITLE
i18n(fr): Update `basics/*` from #9240

### PR DESCRIPTION
**Pull request by thomasbnt**
#### Description (required)
i18n(fr): Update `basics/*` from #9240 :
- [x] astro-components (Err link : [(waiting for reference/directives-reference was updated)](https://github.com/withastro/docs/pull/10133/commits/b8ca25d68d2091dc748ede017539bdf2bc23fa9e))
- [x] astro-pages
- [x] layouts
- [x] project-structure

> [!NOTE]
> Err link at L23 `astro-components`, waiting for `reference/directives-reference`

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n

### CODE REVIEW

**Comment by thomasbnt** [comment]
> LGTM, just two tiny nits... And the two broken links... but that will have to wait... I have a feeling Yan is going to have fun merging the PRs... 😅

Thanks you for your review!

**Comment by ArmandPhilippot** [comment]
The broken link in `directives-reference.mdx` should be fixed with #10195 but there's still a broken link in `layout.mdx`.

**Comment by trueberryless** [comment]
Haven't looked into this PR, but wanted to mention that it would be very appreciated if the changes from #10327 could be translated as well... 🙏🥺

**Comment by thomasbnt** [comment]
> Haven't looked into this PR, but wanted to mention that it would be very appreciated if the changes from #10327 could be translated as well... 🙏🥺

Hello! Thanks for your head up about the recent modification from #10327! I just added modifcations with [`ebf9316` (#10133)](https://github.com/withastro/docs/pull/10133/commits/ebf9316fbf465fef960d5643131cedf0f26f970c)

**Pull request merged**
