### PR TITLE
docs(en/pt-BR): update integration-reference build end hook

### PR DESCRIPTION
**Pull request by userquin**
#### What kind of changes does this PR include?

- [X] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [ ] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

- What does this PR change? Give us a brief description.
Adds the missing `routes` on the `astro:build:done` integration hook: for context https://github.com/withastro/astro/pull/3438#issuecomment-1136473008
- Did you change something visual? A before/after screenshot can be helpful.
NO

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @userquin ! I can see this is your first contribution to the docs, so YAY 🥳  and I'm going to give you a few handy tips about PRs to this repo, because we have a bit of a complicated setup here, especially with all the languages involved.  😅 

Here's how to make sure we can accept your PR:

1. Please do NOT include any files like `pnpm-lock.yaml` in your PR. It's important to only give us the files with documentation changes. 
2. Please only give us a documentation change for a page at the /en/ filepath. We have our own system for making sure this change will be reflected in the 6 other languages where this change will need to occur. I noticed that this PR includes both /en/ and /pt-BR/ changed. Please remove the /pt-BR/ file from this PR.
3. THANK YOU for mentioning  https://github.com/withastro/astro/pull/3438 so we can track where this change comes from! But, when documentation is added for a PR to Astro that has not yet been accepted, a PR to docs must be marked as a draft. It cannot be merged until the feature or fix it relates to has been approved and merged.

I can mark it as a draft here myself, but I wanted to explain why I'm doing so. 

Also, if somehow your Astro PR is not accepted, or is accepted with changes that affect this documentation, please remember to come back and update this, or close it if necessary! We might not notice what happens in the other repo, so it's up to you to help us out!  😄 

Thank you again for your contribution, and please let me know if you have any questions about any of the changes I've asked for!

**Comment by userquin** [comment]
@sarah11918 the PR on Astro doesn't affect this PR, the signature for the hook is wrong

Tmr I'll undo the changes on the pt-BR and revert changes on the lock file.

**Comment by sarah11918** [comment]
@userquin Perfect, thanks for clarifying that! I'll take it out of draft status, then when the other files are removed, I'll update the branch, make sure our internal checks pass etc. so it can be merged.

**Comment by userquin** [comment]
@sarah11918 supersed by https://github.com/withastro/docs/pull/667

**Pull request closed without merging**
