### PR TITLE
i18n(de): update `concepts/why-astro.mdx`

### PR DESCRIPTION
**Pull request by trueberryless**
#### Description (required)

- update `concepts/why-astro.mdx`

#### Related issues & labels (optional)

- #5428 
- #4166 
- #3556 
- #2067

### CODE REVIEW

**Comment by jsparkdev** [comment]
Thank you @trueberryless ! 

I would like to request two modifications.

1. please make the arrows on lines 57 and 58 the same as the other arrows.
2. the last paragraph of the heading `Entwicklerorientiert` doesn't seem to exist, please add it.

**Comment by jsparkdev** [comment]
On line 54 of `from-create-react-app.mdx`, there is a link to `/de/concepts/why-astro/#inhaltsfokussiert`. However, in the modified file, there is no corresponding heading, resulting in an error.

**Comment by trueberryless** [comment]
All links should be fixed now! 😊

**Review by jsparkdev — APPROVED** [review]
good. LGTM!

**Pull request merged**
