### PR TITLE
chore: Update `tailwind.mdx`

### PR DESCRIPTION
**Pull request by jacobdalamb**
#### Description (required)

Consistent use of `.mjs` as that's the default and mention `ts|mts|cts` as another optional file types for the Tailwind config file

#### Related issues & labels (optional)

- Closes # https://github.com/withastro/astro/pull/9600
- Suggested label:

### CODE REVIEW

**Review by VoxelMC — APPROVED** [review]
Thank you for doing this! I have had this on my to-do list for some time but never got around to it. LGTM!

**Comment by Yan-Thomas** [comment]
Thanks @jacobdalamb, nice work! Could I ask you to remove the change to the files of other languages? Our translation tracking system will consider these "updated" if we merge like this, despite there being changes in the English version that are not present in the translations.

**Comment by jacobdalamb** [comment]
> Thanks @jacobdalamb, nice work! Could I ask you to remove the change to the files of other languages? Our translation tracking system will consider these "updated" if we merge like this, despite there being changes in the English version that are not present in the translations.

Done!

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Pull request merged**
