### PR TITLE
fix: fix style, make the style more perfect!

### PR DESCRIPTION
**Pull request by sun0225SUN**
#### Description (required)

before VS after

image

image

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by sun0225SUN** [comment]
fix mobile style.

image

image

**Comment by sun0225SUN** [comment]
my discord id is `sunguoqi`

**Comment by sarah11918** [comment]
Thank you for this contribution, @sun0225SUN ! We will get some community reviews and people to test on various devices/screen sizes today during our Discord "Talking and Doc'ing" call!

**Comment by BryceRussell** [comment]
Thanks for making a PR on this! I previewed this on my Desktop (Firefox) and mobile (IOS Safari) and the styles look good to me, I don't see any immediate issues with any of these style changes

**Review by HiDeoo — CHANGES_REQUESTED** [review]
Thanks for your contribution, great attention to detail :raised_hands:

We visually tested the changes today during our Discord "Talking and Doc'ing" call and everything seems to looks perfect :thumbsup: One tiny little detail, nested CSS media queries are not something used in the current codebase, so for consistency, it may be wise to avoid them. Would you mind removing the new one introduced in this PR?

---

Unrelated to this PR, we also spotted during the call a few minor details related to the tracker tabbed content. Would it be something you would be interested in fixing as well? (note that this is not a blocker for this PR and does not need to be done in this PR, your call).

- On mobile, top rounded corners for the tracker seems to be inconsistent depending if you are the first chapter, the last chapter or in the middle.

SCR-20240404-nlsv
SCR-20240404-nlpq
SCR-20240404-nlsv

- Still on mobile, it looks like the bottom-left and right borders of the tracker are not rounded but the content inside is (this one is a bit tricky to spot, may need to zoom in).

SCR-20240404-nmhq

---

Thanks again for your contribution!

**Comment by sun0225SUN** [comment]
Okay, I will continue to work on the details, thank you.

**Comment by sun0225SUN** [comment]
It looks like I've fixed everything, but I haven't, the imperfections are still there and I don't seem to have the ability to fix it at the moment.

The imperfection is: 

- when we click on the first element, you will find that there seems to be a 1px pixel block in the lower left corner. This is caused by the style of the `<a>` tag. I tried overriding its `box-shadow` attribute, But it didn't take effect.
image


- Another problem is the left and right lower corners of the panels, which are inconsistent with the borders. I also failed to fix it.
image


As for why I added `min-width:268px;`, it is to solve the following problem. The digital card is generated using svg, which must give a minimum width. Otherwise, when the browser ratio changes, the same will appear. Layout issues.

image

**Comment by HiDeoo** [comment]
Thanks for your thorough investigation. I spend a bit more time outside of the T&D session to think about this, and I think there is another issue that we did not spot.

When the tutorial tracker is in the page right sidebar, it's very easy to spot which chapter the user is currently in.

SCR-20240405-kmsp

When reducing the viewport width and the tutorial tracker is now part of a dropdown, there is no obvious way to know which chapter the user is currently in except a slight color and font-weight change which are not very noticeable in my opinion.

SCR-20240405-knmc

I'm not sure if this is on purpose or not, a mistake, something that was forgotten, etc. I implemented a few changes to make it more like the non-dropdown version.

SCR-20240405-kntp

I personally think this is a better approach visually and functionally but we would need to confirm with more people, thinking about Sarah and Chris, maybe there are design mockups that we are not aware of, etc.

I'm posting here the patch for all my changes so far which I think also fixes the original issues you spotted but I think we should wait for feedback before any further action.

```patch
diff --git a/src/components/starlight/MobileTableOfContents.astro b/src/components/starlight/MobileTableOfContents.astro
index 84139cbd9..b76b1e064 100644
--- a/src/components/starlight/MobileTableOfContents.astro
+++ b/src/components/starlight/MobileTableOfContents.astro
@@ -110,13 +110,18 @@ const starlightTranslations = useStarlightTranslations(Astro.props.lang);
 	.dropdown {
 		--border-top: 1px;
 		margin-top: calc(-1 * var(--border-top));
-		border: var(--border-top) solid var(--sl-color-gray-6);
 		border-top-color: var(--sl-color-hairline-shade);
 		max-height: calc(85vh - var(--sl-nav-height) - var(--sl-mobile-toc-height));
 		overflow-y: auto;
 		background-color: var(--sl-color-black);
 		box-shadow: var(--sl-shadow-md);
 	}
+
+	@media (min-width: 72em) {
+		.dropdown {
+			border: var(--border-top) solid var(--sl-color-gray-6);
+		}
+	}
 </style>
 
 <script>
diff --git a/src/components/tabs/TabListItem.astro b/src/components/tabs/TabListItem.astro
index 38fdff61e..1391c489e 100644
--- a/src/components/tabs/TabListItem.astro
+++ b/src/components/tabs/TabListItem.astro
@@ -15,6 +15,7 @@ const { id, initial } = Astro.props;
 
 <style>
 	a {
+		display: block;
 		fill: var(--sl-color-gray-2);
 	}
 
@@ -23,7 +24,6 @@ const { id, initial } = Astro.props;
 		z-index: 1;
 		background-color: var(--sl-color-gray-6);
 		box-shadow: 0px 0px 0px 1px var(--sl-color-gray-5);
-		border-radius: 0.25rem 0.25rem 0 0;
 		fill: var(--sl-color-white);
 	}
 	a[aria-selected='true']::after {
@@ -35,4 +35,10 @@ const { id, initial } = Astro.props;
 		background-color: var(--sl-color-gray-6);
 		position: absolute;
 	}
+
+	@media (min-width: 72em) {
+		a[aria-selected='true'] {
+			border-radius: 0.25rem 0.25rem 0 0;
+		}
+	}
 </style>
diff --git a/src/components/tabs/TabbedContent.astro b/src/components/tabs/TabbedContent.astro
index ef55bdcc2..77b2c9f64 100644
--- a/src/components/tabs/TabbedContent.astro
+++ b/src/components/tabs/TabbedContent.astro
@@ -41,6 +41,12 @@ const { tabs } = Astro.props as Props;
 		overflow-y: hidden;
 	}
 
+	@media (min-width: 72em) {
+		.tab-list {
+			justify-content: space-between;
+		}
+	}
+
 	.panels {
 		padding-left: 1px;
 		padding-right: 1px;
diff --git a/src/components/tutorial/TutorialNav.astro b/src/components/tutorial/TutorialNav.astro
index bce67a16a..d7608d188 100644
--- a/src/components/tutorial/TutorialNav.astro
+++ b/src/components/tutorial/TutorialNav.astro
@@ -88,14 +88,18 @@ const isCurrentUnit = (unit: (typeof units)[number]) =>
 		padding: 1em;
 		background-color: var(--sl-color-gray-6);
 		box-shadow: 0px 0px 0px 1px var(--sl-color-gray-5);
-		border-radius: 0.25rem;
 	}
 
-	:global(section:first-child) .unit {
-		border-radius: 0 0.25rem 0.25rem 0.25rem;
-	}
-	:global(section:last-child) .unit {
-		border-radius: 0.25rem 0 0.25rem 0.25rem;
+	@media (min-width: 72em) {
+		.unit {
+			border-radius: 0.25rem;
+		}
+		:global(section:first-child) .unit {
+			border-radius: 0 0.25rem 0.25rem 0.25rem;
+		}
+		:global(section:last-child) .unit {
+			border-radius: 0.25rem 0 0.25rem 0.25rem;
+		}
 	}
 
 	.tutorial-nav ol.lessons {
```

**Comment by sun0225SUN** [comment]
Thank you, that's really cool :tada:

**Review by sarah11918 — APPROVED** [review]
Giving my approval for making the chapter more visible in mobile, and trusting @HiDeoo to make the final call!

**Review by HiDeoo — COMMENTED** [review]
After discussing with the team, it looks like there are indeed design documents regarding the tutorial tracker but unfortunately, they do not include mobile designs for it.

Rather than holding up the PR to figure out what the best mobile UI would be, have some back and forth, etc. I think the best approach will be to merge this amazing first-time contribution addressing the initial issues you found and we can later on iterate on the mobile issues in a separate PR.

I suggested a few changes that should address these issues while minimizing the number of changes. Would you be able to check on your end and validate that they address the issues you initially found?

Thanks again for your patience and hard work on this!

**Review by HiDeoo — APPROVED** [review]
Thanks for your updates and patience. Looks like the issues you spotted are now fixed 🎉

We will be able to focus on improving the mobile experience in a new dedicated PR but until then, these improvements looks good to go!

**Pull request merged**
