### PR TITLE
i18n(zh-cn): fix link from-gatsby.mdx

### PR DESCRIPTION
**Pull request by AitorMT**
#### Description (required)

The link has been fixed, it was pointing to the English version edition. #6926

### CODE REVIEW

**Comment by liruifengv** [comment]
Thank you! @AitorMT 

I've noticed this, and I think that if new content is to be added, it should be added to the English page first, and then updated for the other i18n pages.

So I think this makes sense now.

**Comment by AitorMT** [comment]
> Thank you! @AitorMT
> 
> I've noticed this, and I think that if new content is to be added, it should be added to the English page first, and then updated for the other i18n pages.
> 
> So I think that makes sense for now.

So, do I close the pull request ?

**Comment by liruifengv** [comment]
This may need to be discussed. cc @Yan-Thomas @sarah11918

**Comment by sarah11918** [comment]
Ah, great question! Thank you for asking!

I will also wait for @Yan-Thomas to answer, but my opinion is yes, the link to add a new piece of content *should* go to the English site. That is the only way that the other languages would know to update. 

Links to update the page itself (like in the sidebar), should point to the proper language. But, all new content must first be added to the English page.

So, one option is to just close this PR. Another option is to update the text, if you feel that would be helpful, in other languages to make it clear that these links should be added to the English site.

e.g., the translation of:

> If you find (or make) a useful video or blog post about converting a Gatsby site to Astro , [ Edit the source page] ( https://github.com/withastro/docs/edit/main/src/content/ docs/ en-us /guides/migrate-to-astro/from-gatsby.mdx ) to add it here!

Let's see if Yan thinks anything different!

**Comment by AitorMT** [comment]
If you tell me how to do this, I will do it, thank you.

**Comment by Yan-Thomas** [comment]
Oh right, sorry I wasn't clear @AitorMT, I believe something along what Sarah suggested works:

> If you found (or made!) a helpful video or blog post about converting a Gatsby site to Astro, [edit the source page](https://github.com/withastro/docs/edit/main/src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx) to add it here!

**Comment by liruifengv** [comment]
> If you tell me how to do this, I will do it, thank you.

Yeah. You can update the en page use Sarah's suggestion. And other language page is in the hands of our translators

**Comment by yanthomasdev** [comment]
Looks like this PR got a bit stale, I'll close this one but I would appreciate a new one to be open with the change to English as suggested above when you have time @AitorMT!

**Pull request closed without merging**
