### PR TITLE
Show list of docs contributor avatars on Getting Started page

### PR DESCRIPTION
**Pull request by delucis**
As teased in [`#docs`](https://discord.com/channels/830184174198718474/853350631389265940/961024501854920754) on Discord, this repurposes the previously unused `AvatarList` component into a `ContributorList` component that can show all contributors for a given repository.

I’ve added it to the bottom of the Getting Started page to encourage folks to get involved:

Screenshot of new Contribute section with facepile

## To-do

To build reliably, we need to provide a GitHub Personal Access Token along with the API request that fetches the list of contributors. (It does build without, but gets rate-limited fairly quickly and will show a fallback link in that case.)

Someone with Netlify Admin access needs to add a new token as an environment variable there.

1. Create a personal access token on GitHub by clicking **Generate New Token** here: https://github.com/settings/tokens

2. Set it not to expire (or set a reminder to replace it when it does). It doesn’t need any scopes selecting, just scroll down and hit **Generate token**

3. In the Netlify Admin dashboard go to Site Settings > Build & Deploy > Environment: https://app.netlify.com/sites/astro-docs-2/settings/deploys#environment

4. Click **Edit variables** and add a new variable called `PUBLIC_GITHUB_TOKEN`. Paste in the new personal access token as the value and hit **Save**.

### CODE REVIEW

**Comment by sarah11918** [comment]
I am +1 on this!

**Comment by natemoo-re** [comment]
I love this! I'd love for @FredKSchott to get this over the line when he has time!

**Review by bholmesdev — APPROVED** [review]
✨ _**Contribeautiful**_ ✨

**Comment by natemoo-re** [comment]
Just added a PAT to the Netlify environment! Merging! 🎉

**Comment by jasikpark** [comment]
It shouldn’t need a new token? I thought there was still a token from the first time we set this up?

**Comment by delucis** [comment]
@jasikpark Could that have been when the docs were deployed from the main repo? The old component was looking for `SNOWPACK_PUBLIC_GITHUB_TOKEN` in the env, so I assumed that was likely outdated.

**Comment by FredKSchott** [comment]
Glad we got this merged in time for community day!

I'd eventually love to sort these by role, similar to how we do this on astro.build: https://astro.build/about/
via this script: https://github.com/withastro/astro.build/blob/main/scripts/update-contributors.mjs

**Comment by delucis** [comment]
Oh, snap! I hadn’t even seen that on the main site. Could maybe even move all that to a `community-data` repo that gets rebuilt every day. That way the sites could just fetch some JSON file from there and not worry about tokens etc. Would be nice for contributors running the docs locally.

Thanks for taking the time on this during such a busy week! 🙌

**Pull request merged**
