### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by VoxelMC**
#### Description (required)

This PR bumps the `@astrojs/starlight` dependency to `0.16.0`, as well as all of the dependencies that are required for Starlight.

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Oops, forgot to explain we’ll need to update our imports of `virtual:starlight/components`.

So stuff like this:

```js
import { TableOfContents, MobileTableOfContents } from 'virtual:starlight/components';
```

would become 

```js
import TableOfContents from 'virtual:starlight/components/TableOfContents';
import MobileTableOfContents from 'virtual:starlight/components/MobileTableOfContents';
```

**Comment by VoxelMC** [comment]
> Oops, forgot to explain we’ll need to update our imports of `virtual:starlight/components`.
> 
> So stuff like this:
> 
> ```js
> import { TableOfContents, MobileTableOfContents } from 'virtual:starlight/components';
> ```
> 
> would become 
> 
> ```js
> import TableOfContents from 'virtual:starlight/components/TableOfContents';
> import MobileTableOfContents from 'virtual:starlight/components/MobileTableOfContents';
> ```

Perfect, will do!

**Comment by VoxelMC** [comment]
> Looks like we’re missing some styling highlighting the current subheading in the table of contents:
> 
> image
> Heading off for the weekend, so maybe this can wait until Monday.
> 
> @sarah11918 you could try this branch and if it makes your dev server problems go away, you could make the call that losing these styles for a couple of days is acceptable if you plan to work on stuff over the weekend!

Is this a regression from Starlight, or is it behaviour from my changes? Just to be sure there's nothing I can do about it.

**Comment by sarah11918** [comment]
I'll test this branch over the weekend and see how the dev server behaves!

**Comment by sarah11918** [comment]
OK, preliminary tests look good here! I have not yet crashed the dev server. So clearly, NWTWWHB!

**Review by sarah11918 — APPROVED** [review]
Did not crash for me with normal use!

**Review by Yan-Thomas — APPROVED** [review]

**Pull request merged**
