### PR TITLE
Update astro-i18n.mdx [i18nIgnore]

### PR DESCRIPTION
**Pull request by trueberryless**
fix type english

#### Description (required)

- remove word `use` because I think it is a typo

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by ArmandPhilippot — APPROVED** [review]
I'm not a native speaker but I think you're right! Well seen! I didn't notice it when I review the PR or when I translated... 👀 

PS: If you use `typo` in the PR title [you don't even need to use `i18nIgnore`](https://github.com/withastro/docs/blob/7ec04d117c055c030c4ded6948dc9f74ee0d9bfa/lunaria.config.json#L109)... but it works too! 😉

**Comment by casungo** [comment]
> PS: If you use `typo` in the PR title [you don't even need to use `i18nIgnore`](https://github.com/withastro/docs/blob/7ec04d117c055c030c4ded6948dc9f74ee0d9bfa/lunaria.config.json#L109)... but it works too! 😉

TIL! very cool.

**Review by casungo — APPROVED** [review]
LGTM! good catch

**Comment by sarah11918** [comment]
Great job everyone!

**Pull request merged**
