### PR TITLE
i18n(ar): Update nav.ts

### PR DESCRIPTION
**Pull request by wpplumber**
#### Description (required)

I translated nav.ts.

#### Related issues & labels (optional)

- Suggested label: i18n

#### First-time contributor to Astro Docs?

@tarik

### CODE REVIEW

**Comment by yanthomasdev** [comment]
Thanks @wpplumber, I'll just ask you to update the format the file is on.

As shown in the comment above this file:
```ts
/**
 * This configures the navigation sidebar.
 * All other languages follow this ordering/structure and will fall back to
 * English for any entries they haven’t translated.
 *
 * - All entries MUST include `text` and `key`
 * - Heading entries MUST include `header: true` and `type`
 * - Link entries MUST include `slug` (which excludes the language code)
 *
 * For translators:
 *
 * Copy the English `key` value unchanged and translate only the `text` into your language:
 *
 * `src/i18n/en/nav.ts`: `{ text: 'Getting Started', slug: 'getting-started', key: 'getting-started' },`
 * `src/i18n/ja/nav.ts`: `'getting-started': 'はじめに',`
 */
```

It should go back to the format it had before but with the keys updated, like so:

```ts
export default NavDictionary({
	// Start Here
	startHere: 'ابدأ هنا',
	'getting-started': 'دليل البداية',
	install: 'التثبيت',
	'editor-setup': 'إعداد المحرر',
	// (more keys...)
});
```

**Comment by wpplumber** [comment]
Welcome @yanthomasdev,

>It should go back to the format it had before 

I think I'm using the latest [format](https://github.com/withastro/docs/blob/main/src/i18n/en/nav.ts) used in the English version!

**Comment by wpplumber** [comment]
Welcome @yanthomasdev,

I made changes based on your review.

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks @wpplumber

**Pull request merged**
