### PR TITLE
i18n(zh-cn): Add translation for `guides/assets`

### PR DESCRIPTION
**Pull request by XindiShang**
#### What kind of changes does this PR include?

- Translated content

#### Description

- Add simplified Chinese translation for `assets (experimental)`

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
Thanks @XindiShang! This page/feature is still experimental, therefore we haven't officially given support for translation, though we'd be happy to receive it when we do so, I'm drafting for now.

**Comment by melon95** [comment]
Hello, may I ask if you still plan to follow up on the translation of this page? If not, I can take over this task.

**Comment by liruifengv** [comment]
This page still was `i18nReady: false`. Can we translate this continue? @Yan-Thomas

**Comment by Yan-Thomas** [comment]
@liruifengv this page is going under heavy changes for 3.0, so I would recommend we keep it untranslated for now!

**Comment by sarah11918** [comment]
Thank you for the work on this PR, but it's now outdated since this page has been removed, and our image content has been translated for the new v3.0 docs!

Closing this PR, but looking forward to more contributions in the future! :raised_hands:

**Pull request closed without merging**
