### PR TITLE
i18n(zh-cn): Update strapi.mdx

### PR DESCRIPTION
**Pull request by webvs2**
#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by webvs2** [comment]
This is a problem I encountered when I was learning how to use strapi cms, which caused me to have doubts for a long time, and then I found out the solution and updated it

**Comment by Yan-Thomas** [comment]
> This is a problem I encountered when I was learning how to use strapi cms, which caused me to have doubts for a long time, and then I found out the solution and updated it

Hey @webvs2, thanks for this! I'll note that we don't accept content changes in other languages, but we do appreciate the intention to improve our docs: would you be able to make a PR changing the English version, so that we can review it and then allow this change to roll out for all languages, not only Simplified Chinese?

**Comment by webvs2** [comment]
Sorry, I will change and close that PR

**Comment by webvs2** [comment]
> > This is a problem I encountered when I was learning how to use strapi cms, which caused me to have doubts for a long time, and then I found out the solution and updated it
> 
> Hey @webvs2, thanks for this! I'll note that we don't accept content changes in other languages, but we do appreciate the intention to improve our docs: would you be able to make a PR changing the English version, so that we can review it and then allow this change to roll out for all languages, not only Simplified Chinese?

@Yan-Thomas examine  #6762

**Pull request closed without merging**
