### PR TITLE
i18n(es): Translated `view-transitions.mdx`

### PR DESCRIPTION
**Pull request by Waxer59**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `view-transitions.mdx`

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Comment by Yan-Thomas** [comment]
Pointing out we need to add the page to the Spanish `nav.ts` so that it shows up in the sidebar!

**Comment by Waxer59** [comment]
> Pointing out we need to add the page to the Spanish `nav.ts` so that it shows up in the sidebar!

I've already added it!

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
