### PR TITLE
i18n(zh-CN): add translation guides

### PR DESCRIPTION
**Pull request by Genteure**
#### What kind of changes does this PR include?

- Something else!

#### Description

Add translation guides for `zh-cn`.

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @Genteure ! I love that you have decided to make your own translation guide! 

Instead of a draft PR, merging something smaller to start, that can be PRd and improved upon might be more helpful. I would be happy to approve merging something and then you can continue to add/improve it! Please let a maintainer know when you feel ready to do this by undrafting the PR , and we will merge it!  :raised_hands:

**Comment by Genteure** [comment]
Hi @sarah11918. Sorry this PR has been left aside for some time, I'll cleanup and finish this PR in the next few days.

**Comment by Genteure** [comment]
This PR is ready for review and merge.

cc @100gle @liruifengv

**Review by 100gle — APPROVED** [review]
great work! 👍

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks 🙌

**Pull request merged**
