### PR TITLE
i18n(es): Update `configuration-reference.mdx`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Updated `configuration-reference.mdx` based on this commit d7b595797aed5c3740700af7d1aa82414fcac285

### CODE REVIEW

**Review by DavidEGiraldo — APPROVED** [review]
LGTM 👍

**Review by Waxer59 — APPROVED** [review]
LGTM ✅

**Comment by dreyfus92** [comment]
Gracias @Waxer59 y @DavidEGiraldo por la revisión 😁

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
