### PR TITLE
feat(de): update german i18n-guides

### PR DESCRIPTION
**Pull request by trueberryless**
#### Description (required)

- add `recipe` translation to deutsch.md because Beispiel fits better in German

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by sarah11918 — CHANGES_REQUESTED** [review]
You should not be creating any PRs right now!  😅 We are not merging any PRs to main, and only a few core maintainers are finishing up v5 for release next week.

I'm sorry, but we are not merging anything right now. So this will have to wait until v5 is released.

Blocking so this does not get accidentally merged.

**Comment by trueberryless** [comment]
@sarah11918 Not even when I wanna merge i to 5.0.0-beta 🥺

Fun aside, 100% understandable, gonna wait till next week... 😂🎉

**Comment by sarah11918** [comment]
Noting this was auto closed when v5 PR merged. We'll need a new PR! @trueberryless because I can't reopen this!

**Comment by trueberryless** [comment]
> Noting this was auto closed when v5 PR merged. We'll need a new PR! @trueberryless because I can't reopen this!

No problem, I got u 😉

**Pull request closed without merging**
