### PR TITLE
Add Steps component to `testing.mdx`

### PR DESCRIPTION
**Pull request by Egpereira**
# Add Steps component to `testing.mdx`

Adds the `Step` component where needed.

### CODE REVIEW

**Review by HiDeoo — COMMENTED** [review]
Thanks for your contribution :raised_hands:

Any specific reason why "Running your NightwatchJS tests" and "Running your Playwright tests" sections were not modified? Or maybe just missed?

**Comment by sarah11918** [comment]
!coauthor

**Comment by HiDeoo** [comment]
> > Thanks for your contribution 🙌
> > Any specific reason why "Running your NightwatchJS tests" and "Running your Playwright tests" sections were not modified? Or maybe just missed?
> 
> I'm not 100% on this decision, but I thought that those two sections weren't actually steps to be followed, but more than one example of how to run the same commands with different flags for different outcomes.
> 
> Any thoughts on that?

I think you are correct regarding NightwatchJS but then, I think the sentence above may be wrong (which initially led to my comment): "using the CLI steps below".

Altho, for Playwright, you need to run the first command before the second one which only open the report generated by the first one.

**Comment by sarah11918** [comment]
I am going to merge this one as is for the Steps component, so that no other significant changes occur for the translators to handle!

If anyone would like to revisit wording on this page, let's do it in a separate PR!

**Comment by Egpereira** [comment]
Proposed change for the NightwatchJS section (unordered list and "commands" instead of "steps"):

NightwatchJS section changes to unordered list

Proposed change for the Playwright section (actually use the Steps component)

Playwright testing section using the Steps component

**Comment by Egpereira** [comment]
@HiDeoo let me know what you think and I can open another PR afterwards if needed.

**Comment by HiDeoo** [comment]
> @HiDeoo let me know what you think and I can open another PR afterwards if needed.

I personally think it's way better 👍  If you're up for it, let's make a new PR and see what other people think about it, but at least for me, I find your solution more correct and readable.

**Comment by Egpereira** [comment]
> > @HiDeoo let me know what you think and I can open another PR afterwards if needed.
> 
> I personally think it's way better 👍 If you're up for it, let's make a new PR and see what other people think about it, but at least for me, I find your solution more correct and readable.

Perfect, I'll open it as soon as I can (and after these changes are on the main branch) and I'll tag you in the PR or in the discord chat to take a look. Thanks!

**Pull request merged**
