### PR TITLE
i18n(ja): Update heroku.mdx

### PR DESCRIPTION
**Pull request by morinokami**
#### Description (required)

- Update heroku.mdx.
  - [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/heroku.mdx?since=2023-10-14T12:53:43.000Z)
    - https://github.com/withastro/docs/pull/5904
    - https://github.com/withastro/docs/pull/5954

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by shuuji3 — APPROVED** [review]
LGTM! 🚀

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks @morinokami @shuuji3

**Comment by liruifengv** [comment]
!coauthor

**Review by dreyfus92 — APPROVED** [review]
Thank you peeps! LGTM ✅

**Pull request merged**
