### PR TITLE
removed link to "snowpack" configuration in Installation Guide

### PR DESCRIPTION
**Pull request by sarah11918**
I hope the change was as easy as removing the linked word "snowpack" in all the other languages too. I will post on the docs-i18n channel to ask others to look over their language, just in case.

Note: not every language had this file, and of the ones that did, not every file included this specific configuration. I believe I caught all the existing ones.

### CODE REVIEW

**Review by iKasch — APPROVED** [review]
German looks good :)

**Comment by lostra01** [comment]
Hungarian one is top quality.

**Review by lostra01 — APPROVED** [review]
Hungarian one is perfect!

**Review by jonathantneal — APPROVED** [review]

**Comment by jonathantneal** [comment]
Ah, accuracy for everyone. 🥲 Thanks, @sarah11918.

**Pull request merged**
