### PR TITLE
Remove unnecessary spaces in HTML tags in the tutorial

### PR DESCRIPTION
**Pull request by morinokami**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

- Fix a typo in tutorial 2-4.

### CODE REVIEW

**Comment by TheOtterlord** [comment]
Good catch! Looks like this exists in a few other places, such as tutorial 2-3 (twice) and the Spanish translations of those pages.

**Review by sasoria — APPROVED** [review]
Thank you, nice catch!

**Comment by morinokami** [comment]
@TheOtterlord @sasoria @ElianCodes I tried to find as many typos of the same pattern in other locations as I could! Could you please check again?

**Comment by TheOtterlord** [comment]
This looks great, thanks! I've found a couple remaining, which I'll commit now, but then I think this is ready to merge.

**Review by TheOtterlord — APPROVED** [review]

**Pull request merged**
