### PR TITLE
i18n(fr): update `guides/actions.mdx` & `modules/astro-actions.mdx`

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
#### Description (required)

Adds changes from #9240 and #10190 to the French translation of `guides/actions.mdx` and `reference/modules/astro-actions.mdx`.

> [!NOTE]
> I haven't updated a link in `guides/actions.mdx` (l406) because `api-reference.mdx` is not yet updated. I think it's okay if this file is marked as up-to-date without this link since `link:check` will throw an error if we forget to update it when updating `api-reference.mdx`.

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Review by thomasbnt — APPROVED** [review]
LGTM!

**Comment by yanthomasdev** [comment]
Thanks, we're missing this commit here: https://github.com/withastro/docs/commit/3851215985ad1b574da6962172acd9ea02e4aabe

**Comment by ArmandPhilippot** [comment]
I saw the PR passed but didn't think to update... Thanks for noticing that! It should be up-to-date now.

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
