### PR TITLE
Eduardo `<Steps>` up!

### PR DESCRIPTION
**Pull request by yanthomasdev**
#### Description (required)

image

### CODE REVIEW

**Comment by sarah11918** [comment]
If it helps, [here is a list of all the PRs](https://github.com/withastro/docs/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+-label%3Ai18n+author%3Aegpereira) that went into this one.

**Comment by sarah11918** [comment]
!coauthor

**Comment by yanthomasdev** [comment]
Shoutout to @Egpereira for the amazing work!

**Review by liruifengv — COMMENTED** [review]
deploy section reviewed

**Pull request merged**
