### PR TITLE
Upgrade docs site to Astro v3

### PR DESCRIPTION
**Pull request by ElianCodes**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- upgrades Astro and integrations to v3

#### Todo:

- [x] wait on `astro-og-canvas` to catch up with v3 compatible version
- [x] import all as types
- [x] change endpoints to uppercase
 - [x] FileTree fails
 - [x] Make sure everything works

---

## Known Bugs

- [x] Image source is `[object object]`
- [x] Theme not working (`localStorage`)
- [x] Sometimes weird tabbing behaviour (`localStorage`)
- [x] Some spacing seems off (asides and chevrons) (`compressHTML` issue)
---

Preview URL: https://deploy-preview-4461--astro-docs-2.netlify.app/

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Thanks for this @ElianCodes! Looks surprisingly mostly OK on a quick browse around.

We might want to set [`scopedStyleStrategy: 'where'`](https://docs.astro.build/en/reference/configuration-reference/#scopedstylestrategy) in `astro.config.mjs` just to be safe. I’ve only spotted one CSS detail off so far caused by specificity shifts with the new attribute default, but there might be some others lurking and shouldn’t do any harm to switch back to the `:where()` approach.

I haven’t seen anything yet, but we should also keep an eye out for issues caused by `compressHTML` now being enabled by default. Spotted a few issues in Starlight where spaces between inline elements were getting collapsed due to https://github.com/withastro/compiler/issues/852

**Comment by itsmatteomanf** [comment]
*Very* minor thing, but on Safari latest `/en/guides/upgrade-to/v3/` doesn't have a fully working scroll-spy (works on current deployed).

Stops at https://deploy-preview-4461--astro-docs-2.netlify.app/en/guides/upgrade-to/v3/#moved-astro-check-now-requires-an-external-package.

**Comment by ElianCodes** [comment]
> Very minor thing, but on Safari latest /en/guides/upgrade-to/v3/ doesn't have a fully working scroll-spy (works on current deployed).

@itsmatteomanf, weird! It seems to work fine on my Safari!

**Comment by itsmatteomanf** [comment]
Another, even more minor thing, the chevrons on the sidebar are closer to the text. Tested on Chrome and Safari latest.

**Comment by itsmatteomanf** [comment]
> > Very minor thing, but on Safari latest /en/guides/upgrade-to/v3/ doesn't have a fully working scroll-spy (works on current deployed).
> 
> @itsmatteomanf, weird! It seems to work fine on my Safari!

And now works for me, too. I tried refreshing, changing page, hard refreshing, and it stayed, but now decided to work. It's so interesting sometimes.

**Comment by itsmatteomanf** [comment]
Actually important thing.

The theme selector default loads to unselected.

image

If you select the other option compared to current then works fine, but doesn't save for the next load, which resets to system settings.

**Comment by Alynva** [comment]
I found a weird tab synchronization behaviour:

e2888f26-3b4d-4c09-ac0a-35c17a558b3a

**Comment by itsmatteomanf** [comment]
> I found a weird tab synchronization behaviour:

That works fine for me, the snap to the top of the code block scroll wise is jarring, but it's the same as v2.

**Comment by itsmatteomanf** [comment]
> the chevrons on the sidebar are closer to the text

Same with the language "tags" for not translated pages.

**Comment by sarah11918** [comment]
Not sure whether this was happening before but confirming the site and new port works fine in Gitpod, but with these error messages in the terminal: 
image

**Comment by Alynva** [comment]
> > I found a weird tab synchronization behaviour:
> 
> ~That works fine for me~, the snap to the top of the code block scroll wise is jarring, but it's the same as v2.
> 
> Ok, now I see that, too.

I think it happens on components after the page's fold, [here](https://deploy-preview-4461--astro-docs-2.netlify.app/en/guides/integrations-guide/) its possible to test both (before and after the fold)

**Comment by itsmatteomanf** [comment]
> > > I found a weird tab synchronization behaviour:
> > 
> > 
> > ~That works fine for me~, the snap to the top of the code block scroll wise is jarring, but it's the same as v2.
> > Ok, now I see that, too.
> 
> I think it happens on components after the page's fold, [here](https://deploy-preview-4461--astro-docs-2.netlify.app/en/guides/integrations-guide/) its possible to test both (before and after the fold)

Yeah, it looks like some sort of loading of the component.

**Review by Fryuni — COMMENTED** [review]
I just tried every behavior I could remember and every combination of odd actions I could think of, with some special care on the tutorials. Everything is behaving correctly as far as I can tell, but I found a single asset problem.

The confirmation for the feedback form is broken.

How it was supposed to be:
image

What happened:
image

**Comment by VoxelMC** [comment]
Very very minor thing I noticed a little while ago - some faulty styling [here](https://deploy-preview-4461--astro-docs-2.netlify.app/en/guides/middleware/ ).

image

**Comment by sarah11918** [comment]
@VoxelMC That issue is in the live docs right now! Sharp eye, but it's not related to the v3 upgrade and needs its own fix. 

Would you like to make a separate PR to fix the indentation there?  https://github.com/withastro/docs/edit/main/src/content/docs/en/guides/middleware.mdx

**Comment by Fryuni** [comment]
Seems like the same problem is present in all translations, same fix for all of them.

**Comment by VoxelMC** [comment]
> @VoxelMC That issue is in the live docs right now! Sharp eye, but it's not related to the v3 upgrade and needs its own fix. 
> 
> Would you like to make a separate PR to fix the indentation there?  https://github.com/withastro/docs/edit/main/src/content/docs/en/guides/middleware.mdx  

@sarah11918 I will do just that!

**Comment by itsmatteomanf** [comment]
@ElianCodes looks good now to me, the toggle for light/dark works perfectly.

**Review by TheOtterlord — COMMENTED** [review]
All other `client:visible` component usage seems to work :+1:

**Review by TheOtterlord — APPROVED** [review]

**Review by delucis — APPROVED** [review]
LGTM! Thanks for all the work on this @ElianCodes and everyone for checking in and reporting problems!

**Pull request merged**
