### PR TITLE
Fix incorrect return values in server-side-rendering.mdx

### LINKED ISSUE #5467: check on example using deprecated feature returning plain object instead of Response
### 📚 Subject area/topic

SSR

### 📋 Page(s) affected (or suggested, for new content)

https://docs.astro.build/en/guides/server-side-rendering/ 

### 📋 General description or bullet points (if proposing new content)

Reported on Discord: https://discord.com/channels/830184174198718474/853350631389265940/1175190161991159879

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

none

### PR DESCRIPTION
**Pull request by mingjunlu**
#### Description

This PR fixes the incorrect return values of endpoint-related snippets in server-side-rendering.mdx.

#### Related issues & labels

- Closes #5467
- Suggested label: code snippet update

### CODE REVIEW

**Review by dreyfus92 — CHANGES_REQUESTED** [review]
Thank you for handling this @mingjunlu. One note is that these changes only should be applied to the `en` version of the docs since we already have a tracker that can let know other translators about changes applied to it. I'd encourage you to only leave the changes for the `en` version. Aside from the suggestion LGTM 😁

**Comment by mingjunlu** [comment]
@dreyfus92 Got it! Thanks for the explanation. Changes have been applied to the `en` version only (using `git rebase`)

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by sarah11918 — APPROVED** [review]
Thank you for jumping on this issue, @mingjunlu !  🙌

**Pull request merged**
