### PR TITLE
Add Steps component to `modified-time.mdx`

### PR DESCRIPTION
**Pull request by Egpereira**
# Add Steps component to `modified-time.mdx`

Adds the `Step` component where needed.

### CODE REVIEW

**Comment by DuanBoomer** [comment]
!coauthor

**Comment by DuanBoomer** [comment]
this pr is good 
image

**Review by sarah11918 — APPROVED** [review]
LGTM!

**Review by DuanBoomer — APPROVED** [review]
LGTM

**Comment by sarah11918** [comment]
!coauthor

**Pull request merged**
