### PR TITLE
Updated the react docs url to the new one in various places

### PR DESCRIPTION
**Pull request by georgeiliadis91**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description
Updated the react docs url in various places.

### CODE REVIEW

**Review by ElianCodes — APPROVED** [review]
LGTM 🚀

**Comment by Yan-Thomas** [comment]
Thanks @georgeiliadis91, could I ask you to remove the changes to the files in the `/old-translations`  folder? These are not maintained nor shown anymore, so we don't need to get these updated.

**Comment by georgeiliadis91** [comment]
@Yan-Thomas  hello, will do in a couple of hours cheers!

**Review by Yan-Thomas — APPROVED** [review]
Perfect @georgeiliadis91, LGTM

**Pull request merged**
