### PR TITLE
i18n(zh-TW): Update `why-astro.mdx`

### PR DESCRIPTION
**Pull request by SnowViktor**
#### Description (required)

- Updated `why-astro.mdx` to more closely match native speaker usage.

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n 

Discord username: snow_viktor

### CODE REVIEW

**Comment by liruifengv** [comment]
Hi @SnowViktor Thank you first PR. But you changed `why-astro.mdx` but PR title is  `getting-started.mdx`

**Comment by mingjunlu** [comment]
Hi @SnowViktor,

Thanks for taking the time to submit this PR.
As @liruifengv pointed out, the commit message is also mismatched.

**Comment by SnowViktor** [comment]
Hello, @mingjunlu .

Sorry for entering the wrong PR title before, it has been corrected now.
But I'm not good at using git, so I don't know how to correct the commit message and cause other commits to occur.

Thank you.

**Review by mingjunlu — APPROVED** [review]
LGTM!

**Comment by mingjunlu** [comment]
@SnowViktor Thanks for making those changes. Welcome to Team Docs!

**Pull request merged**
