### PR TITLE
i18n(es): Translated `unsupported-config-transform-error.mdx`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `unsupported-config-transform-error.mdx` to spanish and added reference

### CODE REVIEW

**Review by Waxer59 — COMMENTED** [review]
Buena PR 🤠, te dejo unas sugerencias

**Comment by dreyfus92** [comment]
Gracias por la revisión @Waxer59 😁

**Review by Waxer59 — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 💜

**Pull request merged**
