### PR TITLE
i18n(zh-cn): Translate backend.mdx

### PR DESCRIPTION
**Pull request by luoingly**
#### What kind of changes does this PR include?

- Translated content

#### Description

- Translate backend.mdx

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
Hey @luoingly, thanks for the PR! Just pointing out that the nav label (the one in the sidebar) "Add backend services" isn't translated, could you add it to the PR? Here's more info about it in our i18n guide: https://github.com/withastro/docs/blob/main/TRANSLATING.md#2-ui-text

**Comment by luoingly** [comment]
> Hey @luoingly, thanks for the PR! Just pointing out that the nav label (the one in the sidebar) "Add backend services" isn't translated, could you add it to the PR? Here's more info about it in our i18n guide: https://github.com/withastro/docs/blob/main/TRANSLATING.md#2-ui-text

Another pr by @liruifengv #3317 have made the chages, so I didn't do it here.

**Comment by Yan-Thomas** [comment]
> Another pr by @liruifengv https://github.com/withastro/docs/pull/3317 have made the chages, so I didn't do it here.

You're right, thanks! Just merged it, this one should be good to go as well 💜

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks 💜

**Pull request merged**
