### PR TITLE
i18n(zh-cn): update `reference/configuration-reference.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### Description (required)

- update `reference/configuration-reference.mdx`
- translate for `experimental.devOverlay`

#### Related issues & labels (optional)

#5132
#5201

### CODE REVIEW

**Comment by liruifengv** [comment]
昨天发布 3.4，有个新 commit: https://github.com/withastro/docs/commit/f80dc91c54b0ce242a7ca5d8e3a74090b7275993

**Comment by 100gle** [comment]
> 昨天发布 3.4，有个新 commit: [f80dc91](https://github.com/withastro/docs/commit/f80dc91c54b0ce242a7ca5d8e3a74090b7275993)

Resolved.

**Review by liruifengv — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Nice job 🙌

**Pull request merged**
