### PR TITLE
i18n(fr) Update `getting-started.mdx`

### PR DESCRIPTION
**Pull request by McFlyPartages**
#### Description (required)

Update getting started file with PR #8190

### CODE REVIEW

**Review by thomasbnt — APPROVED** [review]

**Review by thomasbnt — APPROVED** [review]
LGTM

**Comment by McFlyPartages** [comment]
LGTM

**Review by dreyfus92 — APPROVED** [review]
Merci les gars! LGTM ✅

**Comment by yanthomasdev** [comment]
Thanks @McFlyPartages, could you add https://github.com/withastro/docs/commit/94d715311fc2a18733ab5a002c78188f26a54184 here?

**Comment by McFlyPartages** [comment]
> Thanks @McFlyPartages, could you add [94d7153](https://github.com/withastro/docs/commit/94d715311fc2a18733ab5a002c78188f26a54184) here?

Its OK Thanks

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks peeps 🙌

**Pull request merged**
