### PR TITLE
i18n(zh-cn): Update nav.ts & ui.ts

### PR DESCRIPTION
**Pull request by liruifengv**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Update nav.ts & ui.ts

### CODE REVIEW

**Comment by liruifengv** [comment]
I don't know how to update [docsearch.ts](https://github.com/withastro/docs/blob/main/src/i18n/zh-cn/docsearch.ts).

Maybe it's because the content in `modals` is being translated, causing it to show incomplete?

**Review by 100gle — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps! 🚀

**Comment by Yan-Thomas** [comment]
> Maybe it's because the content in modal was translated, causing it to show incomplete?
Oh nice catch, yes, probably something related to that.

**Pull request merged**
