### PR TITLE
Add Storyblok logo to sponsors

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- Add the Storyblok logo to the sponsors section in the left sidebar.
- Switches the layout a little and simplifies `aria-label` for sponsors to only include the brand name and avoid needing to translate it.
- Minified the Netlify logo & simplified the CSS while I was there.

| Before | After |
|---|---|
| Screen Shot 2023-02-02 at 11 10 35 | Screen Shot 2023-02-02 at 11 10 06

### CODE REVIEW

**Comment by sarah11918** [comment]
I love that the logo colours coincidentally match our "tip" colour!  :rocket: 

I'll go with whatever everyone decides re: alignment etc. At first I thought this was right aligned, I think because of the length of the sidebar items down at the bottom, but I'm guessing its center? Only because of the shorter nav items it's near, I might be tempted to try left-aligned, but happy with whatever everyone decides!

**Comment by sarah11918** [comment]
Visually, I like that better! Does it make as much *sense*? I do like it though.

**Comment by FredKSchott** [comment]
the all-centered aligned screenshot is my favorite!

**Comment by delucis** [comment]
Ok going to merge the centre aligned one for now so this can go live. We can definitely revisit later/as part of the redesign process.

**Pull request merged**
