### PR TITLE
i18n(zh-cn): Update integrations-reference.mdx

### PR DESCRIPTION
**Pull request by liruifengv**
#### Description (required)

- Update integrations-reference.mdx
- Update translation
- Fix Line Breaks

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by huyikai — COMMENTED** [review]
LGTM

**Comment by Yan-Thomas** [comment]
Pointing out we're missing this commit: https://github.com/withastro/docs/commit/9c9bdb1ad1ce786b5171777e54ffe38e9da0bdd6

**Comment by liruifengv** [comment]
> Pointing out we're missing this commit: [9c9bdb1](https://github.com/withastro/docs/commit/9c9bdb1ad1ce786b5171777e54ffe38e9da0bdd6)

Done. I also create a new PR to add the missing. https://github.com/withastro/docs/pull/6755

**Review by dreyfus92 — APPROVED** [review]
Thanks everybody, LGTM ✅

**Pull request merged**
