### PR TITLE
i18n(fr) : `MPA vs. SPA`

### PR DESCRIPTION
**Pull request by thomasbnt**
#### What kind of changes does this PR include?

- Translated content

#### Description

- Translated `MPA vs. SPA` in French language. Updates content from `src/pages/fr/concepts/mpa-vs-spa.md`

### CODE REVIEW

**Comment by thomasbnt** [comment]
Hmmm 🤔 

https://app.netlify.com/sites/astro-docs-2/deploys/63095c75f4deed0009a2b2b0#L395

```bash
1:53:02 AM:  error   Cannot destructure property 'version' of 'packageInfo' as it is undefined.
1:53:02 AM:     at file:///opt/build/repo/dist/entry.mjs?time=1661557975374:32675:11
1:53:02 AM:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1:53:02 AM:     at async renderToIterable (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:951:21)
1:53:02 AM:     at async renderAstroComponentInline (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:636:22)
1:53:02 AM:     at async _render (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:527:5)
1:53:02 AM:     at async AstroComponent.[Symbol.asyncIterator] (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:546:7)
1:53:02 AM:     at async renderAstroComponent (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:1004:20)
1:53:02 AM:     at async _render (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:525:5)
1:53:02 AM:     at async _render (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:521:5)
1:53:02 AM:     at async renderSlot (file:///opt/build/repo/dist/entry.mjs?time=1661557975374:564:22)
1:53:02 AM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
1:53:02 AM: ​
1:53:02 AM: ────────────────────────────────────────────────────────────────
1:53:02 AM:   "build.command" failed                                        
1:53:02 AM: ────────────────────────────────────────────────────────────────
1:53:02 AM: ​
1:53:02 AM:   Error message
1:53:02 AM:   Command failed with exit code 1: npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build (https://ntl.fyi/exit-code-1)

```

**Comment by Yan-Thomas** [comment]
Sorry for the inconvenience @thomasbnt, I'll take a look at this issue and fix it ASAP! :raised_hands:

**Comment by thomasbnt** [comment]
Thanks @sarah11918 !

**Comment by sarah11918** [comment]
Alright, I think we're good re: the deploy preview now @thomasbnt @Yan-Thomas!

**Comment by thomasbnt** [comment]
Good! Can you review this PR @pioupia ? 👋🏼😎

**Review by pioupia — APPROVED** [review]

**Comment by Yan-Thomas** [comment]
Thanks @thomasbnt, @pioupia! Just a thing, we just had new changes to this page merged: https://github.com/withastro/docs/commit/ed7b6dc67d91bc82112ea75056f46c1b96be2331, can you add these changes to your PR? After this, LGTM and ready to merge!

**Comment by thomasbnt** [comment]
> Thanks @thomasbnt, @pioupia! Just a thing, we just had new changes to this page merged: [ed7b6dc](https://github.com/withastro/docs/commit/ed7b6dc67d91bc82112ea75056f46c1b96be2331), can you add these changes to your PR? After this, LGTM and ready to merge!

Changed with this commit [`a7c02b8` (#1420)](https://github.com/withastro/docs/pull/1420/commits/a7c02b804016e40282439bd34996e8d3c48b6de7)

**Comment by Yan-Thomas** [comment]
LGTM, thanks for this @thomasbnt! 🙌

**Pull request merged**
