### PR TITLE
Code as headings

### LINKED ISSUE #509: Code as headings, or not?
We're trying to determine a consistent style to use.

Currently, and (explicitly by request), the CLI page does NOT use formatted code for the various `--` headings. 

However, on Project Struture, the directories DO use formatted code directories.

Do we have a preference? Are we concerned with consistency? (And sorry, more of these issues will come up as more translators are actively in the docs wanting explicit instructions, and finding these inconsistencies.) 😅 

Screenshot 2022-05-09 18 45 12
Screenshot 2022-05-09 18 44 43

### PR DESCRIPTION
**Pull request by Chrissdroid**
#### What kind of changes does this PR include?

- [x] Minor content fixes (broken links, typos, etc.)

#### Description

- What does this PR change? Adds backticks in the `reference/` directory.

Closes #509 

Before:
image

After:
image

### CODE REVIEW

**Comment by sarah11918** [comment]
I mean... right??

**Comment by delucis** [comment]
In general I feel positive about this change, except maybe these smaller headings at the bottom of the Adapter API reference page?

image

They feel kind of too small. Whereas currently the bolding helps them stand out:

image

The `code` in headings don’t look bold because we only ship regular and italic weights of IBM Plex Mono (they get kind of faux-bolded by the browser but it’s minimal and doesn’t look great).

We _could_ also ship a bold weight of the monospace font, but the alternative solution would be shipping _no_ code font and use system fonts like we do for all the other text in the docs? That way there’ll usually be a bold monospace variant available.

As an example here’s the same snippet with `font-family: monospace` on my (macOS) machine:

image

**Comment by sarah11918** [comment]
I agree they seem a little small, and would be tempted to want them a tiny bit bigger instead of necessarily bolder myself, but I'm OK with whatever people prefer!

**Comment by delucis** [comment]
> I agree they seem a little small, and would be tempted to want them a tiny bit bigger

Yeah, that’s also a possibility. By default `code` is set to a smaller font-size than surrounding text to balance, but maybe we need to experiment with some heading-specific code styles.

**Comment by delucis** [comment]
@Chrissdroid Do you want to try adding the following to the docs styles to see how it feels? Bumps the font size back up to the size of other text helping code-only headings stand out and also disables bold so we don’t get the browser faux-bolding the monospace font.

```css
:is(h1, h2, h3, h4, h5) code {
  font-size: 1em;
  font-weight: 400;
}
```

In a couple of quick tests this looked like an improvement to me.

**Comment by Chrissdroid** [comment]
Tell me if it's better for you @sarah11918, on my side it's clearly better for reading

**Comment by delucis** [comment]
Thanks @Chrissdroid!

So, what do we think now? Consider the small standalone headings like [the bottom of the adapter page](https://deploy-preview-545--astro-docs-2.netlify.app/en/reference/adapter-reference/#apprenderrequest) and mixed code and text headings like [the top of the runtime API page](https://deploy-preview-545--astro-docs-2.netlify.app/en/reference/api-reference/) or (smaller) in [the integrations reference](https://deploy-preview-545--astro-docs-2.netlify.app/en/reference/integrations-reference/#config-option).

**Comment by sarah11918** [comment]
I've only looked on desktop so far, both light and dark mode, but *I* like this. I find it very readable.

The only thing that startled me at first was the huge ASTRO global.  :)  But, I don't hate it? It is very "Astro-y"

**Comment by sarah11918** [comment]
Just checked it on my phone, and It's BIG, yeah. But it's CLEAR. I think it's a winner.

**Comment by Chrissdroid** [comment]
It looks pretty great like this, it's more readable this way 👍

**Comment by sarah11918** [comment]
LGTM!

**Comment by delucis** [comment]
Yay! Also LGTM! We can always revert if someone chokes on these `code` tags. Thanks for doing this @Chrissdroid 🙌

**Pull request merged**
