### PR TITLE
i18n(ja): Update vercel.mdx

### PR DESCRIPTION
**Pull request by morinokami**
#### Description (required)

- Update vercel.mdx.
  - [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/vercel.mdx?since=2023-08-30T13:25:52.000Z)
    - https://github.com/withastro/docs/pull/6267

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by shuuji3 — APPROVED** [review]
LGTM! 🚀

**Review by AitorMT — APPROVED** [review]
LGTM!

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks peeps @morinokami and @shuuji3 @AitorMT review.

**Comment by liruifengv** [comment]
!coauthor

**Review by dreyfus92 — APPROVED** [review]
Thank you peeps! LGTM ✅

**Pull request merged**
