### PR TITLE
New Integrations page, linked to in sidebar

### PR DESCRIPTION
**Pull request by sarah11918**
New integrations page added separately here. (Not yet in sidebar, but will new proposed landing page has its updated location.)

### CODE REVIEW

**Comment by sarah11918** [comment]
Page to preview: https://deploy-preview-160--astro-docs-2.netlify.app/en/integrations/integrations/

(It's not visible from sidebar yet, so this can be accepted and no one will be able to navigate it until I explicitly add it to the sidebar.)

**Comment by delucis** [comment]
This looks amazing @sarah11918!

Do you think subheadings dividing up the types of resource (rather than having that inline on each item) would be helpful?

Like:

- Production Sites
- Blog Posts
- Repos

Each of these is quite a different resource, so maybe it’s helpful to be able to quickly locate the kind you’re looking for. The repos seem to all be templates/starters, so you might want to fork one and get started, the blog posts are more practical guides to doing X, while the sites are cool for checking out and seeing what’s possible.

**Comment by sarah11918** [comment]
@delucis Please take a look now!  :)

Some slight organization, also added to the sidebar. I'm not loving that it's in "Setup" and will probably move it eventually, but at least it's there, and prominent (so people can see Astro with stuff! Yay!), and can now be linked to from the new Getting Started page proposed in https://github.com/withastro/docs/pull/155

**Comment by delucis** [comment]
Looks great! 

I might use a `username/reponame` style for the repo links, but that's a tiny stylistic detail.

Re: sidebar link location — would it make sense to have this linked in the “Guides” section rather than “Setup”?

**Comment by sarah11918** [comment]
> I might use a `username/reponame` style for the repo links, but that's a tiny stylistic detail.

Done! One was already like that, so I made them all consistent. Good call @delucis !

> Re: sidebar link location — would it make sense to have this linked in the “Guides” section rather than “Setup”?

Yeah, I'm not thrilled with this, but I'm also not thrilled with Themes and Astro vs X being up there either, so that area is going to get tidied soon anyway.  :)  And, it's not actually a "guide" either, so I think the lesser evil right now is to put it with the other related stuff that's ALSO not in the best place, then deal with it all together!

**Pull request merged**
