### PR TITLE
Update typo in `en/guides/cms/storyblok.mdx`

### LINKED ISSUE #4155: Fix "Static site generation" code documentation
https://github.com/withastro/docs/blob/371a48d8fbf95923d583fb1f639ced74f0ebc2eb/src/content/docs/en/guides/cms/storyblok.mdx#L429

Stepping through this documentation at this step results in an error that "This record could not be found."

Updating this line to `cdn/stories/blog/${slug}` fixes the issue.

### PR DESCRIPTION
**Pull request by vcotir**
#### What kind of changes does this PR include?
- Minor content fixes (broken links, typos, etc.)

#### Description
- **Closes #4155**
-  **Updates content of `en/guides/cms/storyblok.mdx` guide**

Review comments on rationale [HERE](https://github.com/withastro/docs/issues/4155#issuecomment-1685138406) for details.

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
Thanks so much for helping to keep our content accurate, @vcotir, and welcome to Team Docs!  🥳

**Comment by TheOtterlord** [comment]
Thanks for updating this! Should we also update [`BlogPostList.astro`](https://github.com/withastro/docs/pull/4279/files#diff-a39822f4e4c9493470ba570f15871e2277cc4e4ab4efa5b2cde283eaeb9cf9a9R315) to target the same folder? Since it's also part of the "make a blog" guide.

**Review by TheOtterlord — COMMENTED** [review]
Thanks for updating this! Should we also update [BlogPostList.astro](https://github.com/withastro/docs/pull/4279/files#diff-a39822f4e4c9493470ba570f15871e2277cc4e4ab4efa5b2cde283eaeb9cf9a9R315) to target the same folder? Since it's also part of the "make a blog" guide.

**Comment by sarah11918** [comment]
@TheOtterlord I'm making this PR your call!

**Comment by TheOtterlord** [comment]
Thanks @vcotir! Let's get this merged

**Comment by vcotir** [comment]
@TheOtterlord Appreciate you filling in my gap there. Sorry for the lapse in communication.

**Pull request merged**
