### PR TITLE
i18n(es): Update `vercel.mdx`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Updated `vercel.mdx` based on these 2 commits 9a069be8145cd4fa4c1b7ef4c714661840449532 & 29c3a3eb2a17a550d382f0af005f418d54de9ca3

### CODE REVIEW

**Review by DavidEGiraldo — APPROVED** [review]
LGTM

**Review by Waxer59 — COMMENTED** [review]
Buena PR 🤠, te dejo unas sugerencias

**Comment by dreyfus92** [comment]
Muchas gracias por la sugerencias y revisión @Waxer59  y @DavidEGiraldo 😄

**Review by Waxer59 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🙌

**Pull request merged**
