### PR TITLE
feat(image_services): Add mention of new validateOptions hook

### PR DESCRIPTION
**Pull request by Princesseuh**
#### What kind of changes does this PR include?

- New or updated content

#### Description

https://github.com/withastro/astro/pull/6555 adds a new hook to the Image Service API that can be used to validate and augment the passed options. The built-in services uses this hook to set the default format as `webp` if the user hasn't passed a format, for example.

It takes the same `options` as the other hooks, so an `ImageTransform` and it returns an ImageTransform as well. Returning an `ImageTransform` is mandatory, so the implementation should probably always end with `return options;`

This PR additionally contain some misc fix to the rest of the file

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
LGTM, @Princesseuh!  :tada:

**Review by Yan-Thomas — COMMENTED** [review]
LGTM! But I do agree with @Jutanium here, might be helpful to have an example.

**Comment by Princesseuh** [comment]
Core PR has been merged, will merge this when it's released

**Comment by sarah11918** [comment]
Merging-on-release, but we have an example ready to add in a separate PR.

**Pull request merged**
