### PR TITLE
Update authentication.mdx

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
#### Description (required)

Added two articles on authentication in Astro.

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi Rishi!

Unfortunately we are not accepting any changes to the v4 version of our docs at the moment, since we are very close to releasing v5 docs and have stopped contributions to this branch and are preparing it for long-term, unmaintained mode.

You can see [this issue](https://github.com/withastro/docs/issues/10092) about making a PR to Astro Tips following the steps to add there if you'd like to submit this to them.

So I will close *this* PR, but suggest you add to Astro Tips while we're adding a bunch of content there now anyway! 🥳 

After v5 stable docs have been released, you can also make a PR to this page again at that time. This will be sometime in early December.

**Comment by rishi-raj-jain** [comment]
@sarah11918 

Hey Sarah,

I've opened https://github.com/withastro/docs/pull/10105 for the new branch.

Oh I see, astro-tips is where all the new resources would go into?

**Comment by sarah11918** [comment]
> Oh I see, astro-tips is where all the new resources would go into?

Yes, Astro Tips for now. The 5.0 branchis for our maintainers right now. Thank you!

**Comment by rishi-raj-jain** [comment]
> Added two articles on authentication in Astro.

Done - https://github.com/astrolicious/astro-tips.dev/pull/308/.

**Pull request closed without merging**
