### PR TITLE
i18n(es): Translated `expected-image-options.mdx` and `expected-image.mdx`

### PR DESCRIPTION
**Pull request by Waxer59**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `expected-image-options.mdx` and `expected-image.mdx` to spanish

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM! ✅

**Comment by Waxer59** [comment]
He añadido una nueva página

**Comment by Yan-Thomas** [comment]
> He añadido una nueva página

Oh nice! If you can, could you please give this PR another look @dreyfus92? Looks good to me but I want to be sure 🙌

**Comment by dreyfus92** [comment]
@Yan-Thomas will do, give me a few.

**Review by dreyfus92 — APPROVED** [review]
LGTM! ✅

**Review by Yan-Thomas — APPROVED** [review]

**Pull request merged**
