### PR TITLE
[i18nIgnore] Migrate to Content Collections

### PR DESCRIPTION
**Pull request by bholmesdev**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- **Migrate all docs pages to a `docs` collection under `/src/content/docs/`.** This preserves the existing i18n folder structure, unchanged.
- Enforce schemas for different docs layouts based on a new `type` frontmatter param. **This `type` replaces the `layout` param,** and can be omitted when using the `MainLayout`. These types can be found browsing the schemas [under `src/content/config.ts`](https://github.com/withastro/docs/pull/2546/files#diff-544dcd1cb4d05890db2dcf497052df475216a57683c346216e43133407b7ea58). I'm curious if the docs team has ideas for CONTRIBUTING updates or further refactors here!

```diff
---
- layout: ~/layouts/DeployGuideLayout.astro
+ type: deploy
---
```

- Update navigation mappers, open graph utilities, and other uses of `glob` to use `getCollection`.
- Update the `[lang]/[...slug].astro` to render content collection entries. This also allowed for fallbacks and page routes to be generated in the same place. This also maps the `type` frontmatter param to the correct layout.
- Add type safety to layout and head props.
- Add a new `splitSlugFromLang` util. This helps with parsing the language out of the generated content collection `slug`.
- Rename redirect slug routes to `[...enRedirectSlug]` and `[enBaseLevelRedirectSlug]`. This was purely for readability debugging our new slug generation routes. I'll differ to @delucis for changing this naming back.

**Chores**
- Bump Astro core to 2.0, and peer packages to their respective majors
- Update `markdown` config to use new `gfm` and `smartypants` flags

### CODE REVIEW

**Comment by sarah11918** [comment]
Confirming that I have tested/looked for (large screen size):
Tutorial: check boxes, multiple choice quizzes, confetti
Components: package manager tabs (including selecting one affecting all on the page), Since (new added in), Right sidebar tracking
Alt Layouts: tutorial, deploy, migrate, CMS
Different languages: navigated in `pl` and `pt-Br`

**Comment by Yan-Thomas** [comment]
I had checked this PR before the optimizations and everything was working properly, and again I'm here to confirm everything looks great!

What I tested:
- Are components working? (Since, Badge, Version, Tabs, Algolia, Dev-only warning, etc) ✔️ 
- Are all pages and their subpages being rendered? (Integrations, Error Reference, 404...) ✔️ 
- Are our translations there, working as intended? (Language Selector, Fallback, "EN", etc) ✔️
- No layout bugs or malfunctioning mobile features? ✔️

**Comment by sarah11918** [comment]
is updating our contributor/translator guide a pre-req to merging this? Should we have that available first, @delucis @Yan-Thomas ?

**Comment by Yan-Thomas** [comment]
> is updating our contributor/translator guide a pre-req to merging this? Should we have that available first, @delucis @Yan-Thomas ?

I believe @delucis made all the necessary changes to these, couldn't find anywhere else in our `.md` guides where we mention `src/pages` rather than `src/content`, so we should be good to go!

**Comment by sarah11918** [comment]
DOES THIS MEAN I APPROVE????

**Review by sarah11918 — APPROVED** [review]
I have not found any reason not to approve this...

Great work @delucis & @bholmesdev !

Let's ... NOT do this again soon??  :sweat_smile:

**Review by Yan-Thomas — APPROVED** [review]

**Pull request merged**
