### PR TITLE
i18n(fr): Update the `getting-started`

### PR DESCRIPTION
**Pull request by thomasbnt**
#### Description (required)
Update the `getting-started` to the new design of the doc

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n

### CODE REVIEW

**Comment by thomasbnt** [comment]
Errors links aren't in this file/language : 
```bash
Error: Broken fragment link in HTML page at "/ar/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#الترجمة". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue231ga3n, #idea231ga3n, #other231ga3n, #textarea231ga3n, #_top, #أهم-المميزات, #جرب-أسترو-على-متصفحك, #ابدأ-مشروعك-الاول-مع-أسترو, #tab-3, #tab-4, #tab-5, #tab-panel-3, #tab-panel-4, #tab-panel-5, #تعلم-أسترو, #ابحر-مع-أسترو, #انضم-إلى-مجتمعنا, #ما-الجديد, #ساهم, #docsearch-lvl0
Error: Broken fragment link in HTML page at "/es/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#traduce". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue6wq3sa, #idea6wq3sa, #other6wq3sa, #textarea6wq3sa, #_top, #características-clave, #prueba-astro-en-tu-navegador, #empieza-tu-primer-proyecto, #tab-397, #tab-398, #tab-399, #tab-panel-397, #tab-panel-398, #tab-panel-399, #aprende-astro, #extiende-astro, #únete-a-nuestra-comunidad, #qué-hay-de-nuevo, #contribuye, #docsearch-lvl0
Error: Broken fragment link in HTML page at "/hi/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#astro-docs-का-अनुवाद-करें". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue1819i83, #idea1819i83, #other1819i83, #textarea1819i83, #_top, #प्रमुख-विशेषताऐं, #अपने-ब्राउज़र-में-astro-आज़माएं, #अपनी-पहली-परियोजना-आरम्भ-करे, #tab-786, #tab-787, #tab-788, #tab-panel-786, #tab-panel-787, #tab-panel-788, #सीखे-astro, #astro-का-विस्तार-करें, #हमारी-समुदाय-के-साथ-जुड़े, #astro-में-नया-क्या-है, #astro-में-योगदान-करें, #docsearch-lvl0
Error: Broken fragment link in HTML page at "/it/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#traduci". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue3kj4ntw, #idea3kj4ntw, #other3kj4ntw, #textarea3kj4ntw, #_top, #funzionalità-chiave, #prova-astro-nel-tuo-browser, #inizia-il-tuo-primo-progetto, #tab-807, #tab-808, #tab-809, #tab-panel-807, #tab-panel-808, #tab-panel-809, #impara-astro, #estendi-astro, #unisciti-alla-nostra-community, #cosa-cè-di-nuovo, #contribuisci, #docsearch-lvl0
Error: Broken fragment link in HTML page at "/ja/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#翻訳する". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue4cljbc, #idea4cljbc, #other4cljbc, #textarea4cljbc, #_top, #主な特長, #ブラウザでastroを試す, #最初のプロジェクトを始める, #tab-837, #tab-838, #tab-839, #tab-panel-837, #tab-panel-838, #tab-panel-839, #astroを学ぶ, #astroを拡張する, #コミュニティに参加する, #新着情報, #貢献する, #docsearch-lvl0
Error: Broken fragment link in HTML page at "/pt-br/getting-started/", unknown source location: The linked page does not contain a fragment with the name "#traduza". Available fragments: #theme-icons, #starlight__sidebar, #starlight__mobile-toc, #starlight__on-this-page--mobile, #starlight__on-this-page, #issue121b68p, #idea121b68p, #other121b68p, #textarea121b68p, #_top, #funcionalidades-principais, #experimente-astro-no-seu-navegador, #comece-seu-primeiro-projeto, #tab-1048, #tab-1049, #tab-1050, #tab-panel-1048, #tab-panel-1049, #tab-panel-1050, #aprenda-astro, #estenda-astro, #junte-se-a-comunidade, #o-que-há-de-novo, #contribua, #docsearch-lvl0
```

https://github.com/withastro/docs/actions/runs/7106530124/job/19346153990?pr=5628

**Comment by delucis** [comment]
Fixed the check! Just needed to re-run it 🙌

**Comment by McFlyPartages** [comment]
LGTM 😉

**Review by dreyfus92 — APPROVED** [review]
Bon boulot @thomasbnt, CMSB 🫡

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
