### PR TITLE
i18n(ko): translate rss.mdx

### PR DESCRIPTION
**Pull request by sujang958**
#### What kind of changes does this PR include?

- Translated content

#### Description

I translatd `rss.mdx` in Korean.

### CODE REVIEW

**Comment by ElianCodes** [comment]
hey @sujang958, Thank you so much for your PR!

This page has been updated since v3, are you willing to take those changes into account in this PR?

**Comment by sujang958** [comment]
Yes of course. I will be doing it soon

**Comment by ElianCodes** [comment]
Thank you so much!

**Comment by sarah11918** [comment]
Hi @sujang958 ! ! Just checking if you are still available to update this page?

We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this can be ready, we would like to be able to review it.  Thanks!

**Comment by sujang958** [comment]
oh ok I will finish this by tomorrow

**Pull request merged**
