### PR TITLE
Simplify middleware examples

### LINKED ISSUE #7567: context.locals or locals?
### 📚 Subject area/topic

To context.locals or locals?

### 📋 Page(s) affected (or suggested, for new content)

Understanding the context is like trying to find your way around a new city without a map; it's a whole lot easier when you know where you're standing!

https://docs.astro.build/en/guides/middleware/

It's interesting to see how others have approached in their writing:
https://github.com/gustavocadev/lucia/blob/cf41b481e184dd5ebfa03ec1d04e4f3e858487cd/docs/pages/getting-started/astro.md?plain=1#L2

But which is correct?

### 📋 Description of content that is out-of-date or incorrect

Storing data in context.locals
Section titled Storing data in context.locals

context.locals is an object that can be manipulated inside the middleware.

This locals object is forwarded across the request handling process and is available as a property to APIContext and AstroGlobal. This allows data to be shared between middlewares, API routes, and .astro pages. This is useful for storing request-specific data, such as user data, across the rendering step.

Integration properties

Integrations may set properties and provide functionality through the locals object. If you are using an integration, check its documentation to ensure you are not overriding any of its properties or doing unnecessary work.

...

src/middleware.js

export function onRequest ({ locals, request }, next) {

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

NA

### PR DESCRIPTION
**Pull request by sasoria**
#### Description
This pull request simplifies the code examples in the section about middleware. I have removed any destructoring of the `context` object to make it easier to understand where it is located in the code.

#### Related issues & labels (optional)

- Closes #7567

### CODE REVIEW

**Comment by sasoria** [comment]
I've been told to tag you here @ematipico. What do you think of this?

**Review by ematipico — APPROVED** [review]
Looks good to me

**Review by sarah11918 — APPROVED** [review]
Thank you @sasoria ! I do think this is helpful!

**Review by dreyfus92 — APPROVED** [review]
Thanks everyone! LGTM ✅

**Pull request merged**
