### PR TITLE
Feat: Add fallback language indicator to links

### PR DESCRIPTION
**Pull request by hippotastic**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [ ] Translated content
- [X] Changes to the docs site code
- [ ] Something else!

#### Description

- Fixes https://github.com/withastro/docs/issues/646.
- Adds an `(EN)` suffix to the link text of links pointing to pages that have not been translated yet.

### CODE REVIEW

**Comment by sarah11918** [comment]
I tried a few examples of being catapulted deep into an English page at various screen sizes, and all seems to work well! 

I don't know whether at some point we may want the (EN) text styled any differently than the link text itself, but this is currently non-distracting and entirely functioning as far as I can tell.

LGTM.

**Comment by hippotastic** [comment]
Nice, thank you for testing all those scenarios! I'll wait to see if @delucis has something to add and then merge if everything is alright. :)

**Comment by sarah11918** [comment]
(I didn't want to TELL you to wait for Chris... but I'm glad you have that instinct!)  ;)

**Review by delucis — APPROVED** [review]
LGTM! Thanks for this Hippo 💜

**Pull request merged**
