### PR TITLE
Document Astro GitHub Action inputs

### LINKED ISSUE #1714: Github pages deploy arguments
The Astro action for the github deploy guide has arguments that aren’t mentioned anywhere. Should I list and explain them?

### PR DESCRIPTION
**Pull request by mandar1jn**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Closes #1714 
- This PR adds documentation about the optional arguments that the withastro/action github action can take
- I'd like the `hacktoberfest-accepted` tag to be added to this PR

### CODE REVIEW

**Comment by mandar1jn** [comment]
If this PR gets accepted: I changed the deploy.yml file embedded in the page. Should I also update this for https://github.com/withastro/github-pages and https://github.com/withastro/action if this PR gets accepted and merged?

**Comment by natemoo-re** [comment]
> Should I also update this for https://github.com/withastro/github-pages and https://github.com/withastro/action if this PR gets accepted and merged?

Yes please @mandar1jn, that would be super helpful!

**Comment by mandar1jn** [comment]
> > Should I also update this for [withastro/github-pages](https://github.com/withastro/github-pages) and [withastro/action](https://github.com/withastro/action) if this PR gets accepted and merged?
> 
> Yes please @mandar1jn, that would be super helpful!

done

**Comment by mandar1jn** [comment]
could you please add the `hacktoberfest-accepted` tag?

**Comment by delucis** [comment]
Thanks @mandar1jn! 🎉

**Pull request merged**
