### PR TITLE
Adding hashes to links

### PR DESCRIPTION
**Pull request by mrienstra**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.) **<-- mostly**
- New or updated content **<-- a smidgen**

This PR began with adding hashes to links.

Along the way, I found & fixed / improved:
* Added `extendDefaultPlugins: true` to 2 examples, to reduce surprising side effects that may otherwise occur when blindly copying code from examples.
* Indentation.
* `npm i` --> `npm install` (for consistency).
* Changed and added a few links.
* Removed unnecessary `import Tabs` from 2 pages
* Switched 1 page from `Tabs` to `PackageManagerTabs`
* Added `PackageManagerTabs` to 1 page.
* Added a link from [reference/adapter-reference](https://docs.astro.build/en/reference/adapter-reference/) to the [SSR guide](https://docs.astro.build/en/guides/server-side-rendering/), as there was otherwise no convenient path from `reference/adapter-reference` to other adapter docs.
* Added some new headers to [guides/server-side-rendering](https://docs.astro.build/en/guides/server-side-rendering/), in part so I could link directly to `#adding-an-adapter`, but also because I think it will scan better.

---

During the same editing session, I edited 4 auto-generated files:
https://github.com/withastro/docs/compare/main...mrienstra:docs:placeholder-1

I'll have to open another PR for those changes, the sources in question being:
- https://github.com/withastro/astro/blob/main/packages/integrations/mdx/README.md
- https://github.com/withastro/astro/blob/main/packages/integrations/partytown/README.md
- https://github.com/withastro/astro/blob/main/packages/integrations/sitemap/README.md
- https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts

### CODE REVIEW

**Comment by mrienstra** [comment]
Whoops, removed `Tabs` import that was being used, fixing that now...

**Comment by mrienstra** [comment]
Find:
```
<Tabs client:visible sharedStore="js-ts">\n<Fragment slot="tab\.js">JavaScript</Fragment>\n<Fragment slot="tab\.ts">TypeScript</Fragment>\n<Fragment slot="panel\.js">\n([\w\W]+?)\n</Fragment>\n<Fragment slot="panel\.ts">\n([\w\W]+?)\n</Fragment>\n</Tabs>
```
Replace:
```
<JavascriptFlavorTabs>
  <Fragment slot="js">
  $1
  </Fragment>
  <Fragment slot="ts">
  $2
  </Fragment>
</JavascriptFlavorTabs>
```

Find:
```
<Tabs client:visible>\n  <Fragment slot="tab.1.npm">npm</Fragment>\n  <Fragment slot="tab.2.yarn">yarn</Fragment>\n  <Fragment slot="tab.3.pnpm">pnpm</Fragment>\n  <Fragment slot="panel.1.npm">\n  ([\w\W]+?)\n  </Fragment>\n  <Fragment slot="panel.2.yarn">\n  ([\w\W]+?)\n  </Fragment>\n  <Fragment slot="panel.3.pnpm">\n  ([\w\W]+?)\n  </Fragment>\n</Tabs>
```

Replace:
```
<PackageManagerTabs>
  <Fragment slot="npm">
  $1
  </Fragment>
  <Fragment slot="pnpm">
  $2
  </Fragment>
  <Fragment slot="yarn">
  $3
  </Fragment>
</PackageManagerTabs>
```

**Comment by sarah11918** [comment]
Hi @mrienstra, lots of stuff here! I appreciate how much effort you're putting into all kinds of docs improvements!

This is a LOT for one PR, and not something we'd normally encourage putting all together like this. Partly because some people might be appropriate to look at some, but not worry about *all* of it. And protip: if the title of the PR doesn't describe what's in here, that's a clue that it's probably more than we want to address at once!  ;)

At the very least, could I ask you to separate out into separate PRs:
1.  adding a new `<Tab />` component, suggesting the use of a tab component where one wasn't and/or removing or changing to use a different kind of tab component
2. adding content to code samples that you believe is an improvement, including the added properties, changing `i` to `install` etc.
and then
... you have several content suggested improvements, not all of which relate to each other. I'd ask you to separate out these into meaningful batches of changes in different PRs, using the title of the PR as a guide to let us know what the intention is behind them.

A PR like this makes a lot of simple quick fixes actually harder to get through, as any one of the maintainers could quickly handle one of these changes, and the title can be a reasonable expectation of who is up for reviewing knowing what the PR contains in terms of content and scope. When that alternative exists, PRs like this just don't make a lot of sense for our community workflow. 

Remember, PRs are freeeee!  🥳  So please do in future try to keep changes contained to the PR title. You can decide whether you'd like to keep this one open for one of the PRs, and remove a bunch of the changes, or whether you'd like to close this one and start fresh with individual PRs for everything.

**Comment by mrienstra** [comment]
This PR was broken into the following:
1. https://github.com/withastro/docs/pull/1769
2. https://github.com/withastro/docs/pull/1772
3.  https://github.com/withastro/docs/pull/1775
4. https://github.com/withastro/docs/pull/1776
5. https://github.com/withastro/docs/pull/1777

**Pull request closed without merging**
