### PR TITLE
Feat: Linkcheck v2 (5 new checks, autofix support)

### PR DESCRIPTION
**Pull request by hippotastic**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [ ] Translated content
- [X] Changes to the docs site code
- [ ] Something else!

#### Description

- This PR contains a big overhaul of my linkcheck script that you can run with `pnpm run lint:linkcheck` (or `pnpm run lint:linkcheck:nobuild` if you want to skip the build).
- While the old version was mostly one monolithic file that only checked for broken page and fragment links, the new version has been refactored to make all checks modular and easily extensible.
- 5 completely new checks were added (see below).
- GitHub annotations were greatly improved, providing a clear explanation of the problem, and a fix suggestion (if available) ready for copy & paste.
  - In future versions, we could use this in an automation to perform an automated review with suggested changes that can be accepted by PR authors directly on GitHub with one click.
- A new `--autofix` mode has been added, which is also promoted by the CLI script in case autofixable issues were found. In this mode, the script automatically applies all fixes directly in the Markdown source code, validates the fixes, and finally highlights any remaining issues that need to be fixed manually.

#### Screenshot

current-output

### Links to meta refresh pages
GitHub annotation preview:
> Link to meta refresh page in src/pages/zh-CN/getting-started.md, line 28: Please link directly to the target page instead of a redirect page that uses meta refresh to forward the user. This improves ranking in search engines and avoids unnecessary requests. Suggested fix: /zh-CN/core-concepts/project-structure/

### Links not using canonical URLs
GitHub annotation preview:
> Link not using canonical url in src/pages/zh-CN/install/auto.md, line 146: Please use the proper canonical URL of the target page. This improves ranking in search engines and avoids unnecessary redirects. Suggested fix: /zh-CN/guides/deploy/

### Pages missing canonical URLs
GitHub annotation preview:
> Page missing canonical URL in src/pages/en/some/page.md, line 123: The target page does not have a canonical URL. Please consider adding a `<link rel="canonical" href="...">` element to the page.

### Unwanted absolute links
GitHub annotation preview:
> Unwanted absolute link in src/pages/en/guides/deploy.md, line 37: https:&sol;/docs.astro.build/en/reference/configuration-reference/#site Suggested fix: /en/reference/configuration-reference/#site

### Links to unexpected languages
GitHub annotation preview:
> Link to unexpected language in src/pages/zh-TW/getting-started.md, line 71: Expected link path to start with "/zh-TW/", but found "/en/". The correct prefix is required to ensure that users stay on their selected language version of the docs. Suggested fix: /zh-TW/reference/directives-reference/

&nbsp;

### CODE REVIEW

**Comment by hippotastic** [comment]
@delucis PTAL. You can see all the current link issues in the failed check report. These were all there before, they are now only made visible by the linkchecker V2.

We should merge this despite the failing check and then create a new PR with a minor commit that includes the result of running `--autofix` to fix all existing link issues in one go.

**Review by delucis — APPROVED** [review]
Well this is overwhelming! 😅 

I think this looks good to me although I can’t read through every detail.

I’m wondering something, @hippotastic. What do you think about turning this into a separate npm package we could consume? It seems at this point like a really solid tool that might be useful to others? We could keep certain checks in-repo (`same-language` is maybe specific to this project for example), but most of this could live in a dedicated repo. I’m thinking we’re hitting the kind of complexity where unit tests would be really nice to have, but I don’t think we’d want to add those here.

**Comment by hippotastic** [comment]
Thank you for the approval and the kind words! 💜

Really interesting thought regarding the NPM package. That would be my first one then. Thanks to the new extensible check interface, it should really be easy to keep repo-specific checks in here while having all the common checks done by the NPM package. I'll keep thinking about this!

**Comment by delucis** [comment]
Great! If you need guidance about getting npm modules packaged up etc. always happy to answer questions. That’s what I thought about the types: you import and extend the abstract class from the package and then you’ll know when the package changes the required check format. Really good work!

**Pull request merged**
