### PR TITLE
[i18nIgnore] Update bun-types in Bun recipe

### PR DESCRIPTION
**Pull request by jacobthesheep**
#### What kind of changes does this PR include?

- Update [bun recipe](https://docs.astro.build/en/recipes/bun/)

#### Description

- Add `-d` to `bun add bun-types` as shown in https://bun.sh/docs/installation

### CODE REVIEW

**Review by Rejke — APPROVED** [review]

**Comment by Genteure** [comment]
Can you also make this change in other languages too, and mark the PR as `[i18nIgnore]` please? Similar to #4633.

**Comment by jacobthesheep** [comment]
> Can you also make this change in other languages too, and mark the PR as `[i18nIgnore]` please? Similar to #4633.

Done

**Review by Genteure — APPROVED** [review]
LGTM

**Review by TheOtterlord — APPROVED** [review]
Thanks! Let's get this merged!

**Pull request merged**
