### PR TITLE
i18n(zh-cn): Update add-view-transitions.mdx

### PR DESCRIPTION
**Pull request by Nin3lee**
#### Description (required)
an awkward expression

the sentence “中网站” is in a wrong order, change it into “网站中”
#### Related issues & labels (optional)

- Suggested label:  i18n

### CODE REVIEW

**Comment by liruifengv** [comment]
Thanks! Nice catch! @Nin3lee 

We have a new commit need to update for this page: https://github.com/withastro/docs/pull/7468

Can you update it together?

**Comment by Nin3lee** [comment]
Okay! But how can i update them together?

Do i need to make another PR?

**Comment by liruifengv** [comment]
> Okay! But how can i update them together?
> 
> 
> 
> Do i need to make another PR? @liruifengv 

You're right, we need to update them in the same PR

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks peeps! @Nin3lee

**Pull request merged**
