### PR TITLE
i18n(zh-CN):translate `integrations\integrations.md` page

### PR DESCRIPTION
**Pull request by samawong**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [X] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

- translate `integrations\integrations.md` page

### CODE REVIEW

**Comment by samawong** [comment]
>

**Comment by kecrily** [comment]
You seem to do duplicate work. duplicate https://github.com/withastro/docs/pull/549

**Comment by samawong** [comment]
> You seem to do duplicate (重复) work. duplicate #549

Ok,I close this.

**Comment by delucis** [comment]
Thanks @samawong. Maybe you’d like to take a look at #549 and say if you see anything that you would do differently?

Sorry for the extra work! ❤️

**Pull request closed without merging**
