### PR TITLE
feat: update integrations related docs

### PR DESCRIPTION
**Pull request by florian-lefebvre**
#### Description (required)

1. Adding link to my integration template
2. Adding link to the discord server since we now have a dedicated channel

#### Related issues & labels (optional)

- Closes N/A
- Suggested label: improve documentation

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Thanks @florian-lefebvre, LGTM 😁

**Review by sarah11918 — APPROVED** [review]
Looks great! Thank you for running with this!  :purple_heart:

**Comment by florian-lefebvre** [comment]
Tbh I'm shocked I didn't receive any wording-related reviews 😂

**Comment by sarah11918** [comment]
It wouldn't be nice for me to say that I'm also shocked.... so I wont!  ;)

**Pull request merged**
