### PR TITLE
i18n(zh-tw): update `auto.mdx` translation

### PR DESCRIPTION
**Pull request by mingjunlu**
#### Description

- Updates Traditional Chinese translation of `src/content/docs/zh-tw/install/auto.mdx`

#### Related issues & labels

- ~~Closes #~~
- Suggested label: i18n

### CODE REVIEW

**Comment by liruifengv** [comment]
`create-astro` is now `create astro`.

**Comment by mingjunlu** [comment]
> Thank you. I can't comment on unmodified lines. Just point a issue, `create-astro` is now `create astro`.

Thanks for your reminder! I've [changed `create-astro` to `create astro` ](https://github.com/withastro/docs/pull/7135/commits/6321b2e42dae87bfac119e1437a3931a71d21808).

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks peeps. @mingjunlu

**Review by dreyfus92 — APPROVED** [review]
Thanks peeps! LGTM ✅

**Pull request merged**
