### PR TITLE
i18n(zh-cn): update `guides/content-collections.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### Description (required)

update `guides/content-collections.mdx`

Note that **this PR should be merged after #5349** 

#### Related issues & labels (optional)

#5312

### CODE REVIEW

**Comment by liruifengv** [comment]
ci 挂了，应该是要同步更新 config-reference

**Comment by 100gle** [comment]
> ci 挂了，应该是要同步更新 config-reference

#5349

**Review by Genteure — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Great work peeps 🚀

**Pull request merged**
