### PR TITLE
i18b(es): Update guides/server-side-rendering.mdx

### PR DESCRIPTION
**Pull request by nabu1615**
#### What kind of changes does this PR include?

- New or updated content

#### Description

Update translation for src/content/docs/es/guides/server-side-rendering.mdx

### CODE REVIEW

**Review by dreyfus92 — COMMENTED** [review]
Hey @nabu1615 thanks for jumping in, but I don't think these changes are necessary since they match the English version of the docs.

**Comment by nabu1615** [comment]
> Hey @nabu1615 thanks for jumping in, but I don't think these changes are necessary since they match the English version of the docs.

It looks confused for me, the idea about help with the translation tasks is more than just translate, the literal translation for this text does not match a logic idea that's becase it needs help from native speakers.

**Comment by Waxer59** [comment]
Thank you very much for the PR, I agree with @dreyfus92 and think these changes are not necessary. However, if you are interested in continuing to contribute there is a page where you can see the [pages available for translation](https://i18n.docs.astro.build/). Where there is currently [one available](https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/add-yaml-support.mdx).

**Comment by nabu1615** [comment]
> Thank you very much for the PR, I agree with @dreyfus92 and think these changes are not necessary. However, if you are interested in continuing to contribute there is a page where you can see the [pages available for translation](https://i18n.docs.astro.build/). Where there is currently [one available](https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/add-yaml-support.mdx).

Ok, thank you, I will take a look, I will close this PR.

**Pull request closed without merging**
