### PR TITLE
Add support for highlighting deploy guides with stars

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

Following up on some Discord chat, this PR adds support for “starring” deploy guides to highlight them subtly. Netlify & Vercel are the only two added so far.

image

image

### CODE REVIEW

**Comment by sarah11918** [comment]
Looks great! Are we going to have any kind of legend/explainer yet? Or just let the stars speak for themselves for now?

**Comment by delucis** [comment]
I was thinking to let them just be a little graphical detail to avoid needing to decide what we mean (sponsored? recommended?) although I can imagine someone asking “Hey how do I get a star on my platform?!” so maybe we should think about what our answer would be?

**Comment by sarah11918** [comment]
I would personally be infuriated by a symbol and not to know what it meant.  😅   (Like, the "asterisk but no fine print" deal.)

As long as we revisit this, and don't leave it like this forever, I'm content not to hold up the PR though!

**Comment by delucis** [comment]
No rush I don’t think! Let’s decide what we mean.

**Comment by sarah11918** [comment]
So options could be:

1. A blurb explaining what these stars indicate (preferred partner? Recommended? First-time friendly? Works well?) 

> Ready to build and deploy your Astro site? Follow one of our guides to different deployment services or scroll down for general guidance about deploying an Astro site.

ADD:
> Not sure which to try? The services labeled with a ⭐ are particularly Astro-friendly (well-suited to hosting Astro projects?), and a good choice if you've never deployed a site before.

2. A less-conspicuous line that acts as a legend:

> ⭐ - Recommended

3. Adding to the icon a tiny word like "Preferred" so that we don't have to give a full-blown explanation, but give SOME kind of idea what these stars are for. (@delucis would have to say whether that's too annoying technically to do, since it requires more than just making a star)

If just a single word on the icon:
Recommended
Preferred
(I hate "Easy" but maybe something along the lines of "Fast")
Beginner-friendly (I know that's probably too long?)

**Comment by Jutanium** [comment]
I agree that the stars should mean something specific and also not just be "pay us to get one". Some sort of objective criteria that you can meet to get a star, like:
- No credit card required
- One-click deploy (i.e., it integrates automatically with your repository, sees that you have Astro, and sets things up accordingly
- Both SSR and SSG support

**Comment by sarah11918** [comment]
> * No credit card required
> * One-click deploy (i.e., it integrates automatically with your repository, sees that you have Astro, and sets things up accordingly
> * Both SSR and SSG support

I know you're not suggesting this as an actual trio of conditions to meet all at once to get a star, but I'm more noticing that these are all very different things (e.g. the most horribly complicated option might not require a credit card...) so... maybe we need to have a broader core/maintain discussion about this? I worry that this boils down to a couple of us "picking stars" (even if we are "picking the criteria to be starred") and... I'm not entirely sure that should fall under the discretion of just a few maintainers like this, without others knowing this discussion is even happening.

I think our original intentions are good: steer users to "sensible" options that won't lead them down dark paths, should they be looking for some reasonable defaults. (e.g. Some of these options we know to be complicated, and/or we see people having trouble with them in support, and we WISH they'd choose something that has a greater chance of giving them an easier, gentler first experience.) But, we do already put Netlify and Vercel at the top of the list, so we do sort of steer users that way.

CHAOS MONKEY: A few different icons to represent different things?

**Comment by sarah11918** [comment]
I propose: STAR NETLIFY AND VERCEL AND MERGE AND DEAL WITH THE FALLOUT

**Comment by delucis** [comment]
Going to close this as I’m not convinced we gain a huge amount from this as it stands and we probably need further consideration of what our aims are before moving ahead.

**Pull request closed without merging**
