### PR TITLE
Routing updates (i18nIgnore)

### PR DESCRIPTION
**Pull request by TheOtterlord**
#### Description (required)

Collaboration on talking & docing.

### CODE REVIEW

**Comment by HiDeoo** [comment]
👋  Just adding myself a note to double check the title of the `sharing-state-islands` page.

**Comment by sarah11918** [comment]
Making a note to encourage people to leave thoughts as to what else maybe should change here at the same time!

e.g. Do we like the "Built ins" section, or just move those three items into guides?

**Comment by sarah11918** [comment]
OOh, note to check Astro Docs Docs to see if we're linking to any URLs that would be affected, so we can clean them up at the source!

**Comment by sarah11918** [comment]
UPDATE: On today's Talking and Doc'ing we:
- renamed `src/content/docs/[lang]/core-concepts/` to  `src/content/docs/[lang]/basics/`
- renamed `/[lang]/core-concepts/routing.mdx`, `/[lang]/core-concepts/endpoints.mdx`, and `/[lang]/core-concepts/framework-components.mdx` all to `/[lang]/guides/*.mdx`
- renamed `/[lang]/core-concepts/sharing-state.mdx` to `/[lang]/recipes/sharing-state-islands.mdx`
- updated `src/i18n/[lang]/nav.ts` for the 3 files moved from `core-concepts` to `guides` folder

**Comment by Fryuni** [comment]
For reference these are the files Git is considering as redirect:

<details>
<summary>
<code>`git diff --stat=200 --diff-filter=R main..sarah-logical-urls src/content/docs | rg -o -r '$1' '^ (.+\.mdx)'`</code>
</summary>


```
src/content/docs/ar/{core-concepts => basics}/astro-components.mdx
src/content/docs/de/{core-concepts => basics}/astro-components.mdx
src/content/docs/de/{core-concepts => basics}/astro-pages.mdx
src/content/docs/de/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/de/{core-concepts => basics}/layouts.mdx
src/content/docs/de/{core-concepts => basics}/project-structure.mdx
src/content/docs/de/{core-concepts => guides}/endpoints.mdx
src/content/docs/de/{core-concepts => guides}/framework-components.mdx
src/content/docs/de/{core-concepts => guides}/routing.mdx
src/content/docs/de/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/en/{core-concepts => basics}/astro-components.mdx
src/content/docs/en/{core-concepts => basics}/astro-pages.mdx
src/content/docs/en/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/en/{core-concepts => basics}/layouts.mdx
src/content/docs/en/{core-concepts => basics}/project-structure.mdx
src/content/docs/en/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/en/{core-concepts => guides}/endpoints.mdx
src/content/docs/en/{core-concepts => guides}/framework-components.mdx
src/content/docs/en/{core-concepts => guides}/routing.mdx
src/content/docs/en/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/es/{core-concepts => basics}/astro-components.mdx
src/content/docs/es/{core-concepts => basics}/astro-pages.mdx
src/content/docs/es/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/es/{core-concepts => basics}/layouts.mdx
src/content/docs/es/{core-concepts => basics}/project-structure.mdx
src/content/docs/es/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/es/{core-concepts => guides}/endpoints.mdx
src/content/docs/es/{core-concepts => guides}/framework-components.mdx
src/content/docs/es/{core-concepts => guides}/routing.mdx
src/content/docs/es/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/fr/{core-concepts => basics}/astro-components.mdx
src/content/docs/fr/{core-concepts => basics}/astro-pages.mdx
src/content/docs/fr/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/fr/{core-concepts => basics}/layouts.mdx
src/content/docs/fr/{core-concepts => basics}/project-structure.mdx
src/content/docs/fr/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/fr/{core-concepts => guides}/endpoints.mdx
src/content/docs/fr/{core-concepts => guides}/framework-components.mdx
src/content/docs/fr/{core-concepts => guides}/routing.mdx
src/content/docs/fr/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/it/{core-concepts => basics}/astro-components.mdx
src/content/docs/it/{core-concepts => basics}/astro-pages.mdx
src/content/docs/it/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/it/{core-concepts => basics}/layouts.mdx
src/content/docs/it/{core-concepts => basics}/project-structure.mdx
src/content/docs/it/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/it/{core-concepts => guides}/endpoints.mdx
src/content/docs/it/{core-concepts => guides}/framework-components.mdx
src/content/docs/it/{core-concepts => guides}/routing.mdx
src/content/docs/ja/{core-concepts => basics}/astro-components.mdx
src/content/docs/ja/{core-concepts => basics}/astro-pages.mdx
src/content/docs/ja/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/ja/{core-concepts => basics}/layouts.mdx
src/content/docs/ja/{core-concepts => basics}/project-structure.mdx
src/content/docs/ja/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/ja/{core-concepts => guides}/endpoints.mdx
src/content/docs/ja/{core-concepts => guides}/framework-components.mdx
src/content/docs/ja/{core-concepts => guides}/routing.mdx
src/content/docs/ko/{core-concepts => basics}/astro-components.mdx
src/content/docs/ko/{core-concepts => basics}/astro-pages.mdx
src/content/docs/ko/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/ko/{core-concepts => basics}/layouts.mdx
src/content/docs/ko/{core-concepts => basics}/project-structure.mdx
src/content/docs/ko/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/ko/{core-concepts => guides}/endpoints.mdx
src/content/docs/ko/{core-concepts => guides}/framework-components.mdx
src/content/docs/ko/{core-concepts => guides}/routing.mdx
src/content/docs/ko/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/pt-br/{core-concepts => basics}/astro-components.mdx
src/content/docs/pt-br/{core-concepts => basics}/astro-pages.mdx
src/content/docs/pt-br/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/pt-br/{core-concepts => basics}/layouts.mdx
src/content/docs/pt-br/{core-concepts => basics}/project-structure.mdx
src/content/docs/pt-br/{core-concepts => guides}/endpoints.mdx
src/content/docs/pt-br/{core-concepts => guides}/framework-components.mdx
src/content/docs/pt-br/{core-concepts => guides}/routing.mdx
src/content/docs/pt-br/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/ru/{core-concepts => basics}/astro-components.mdx
src/content/docs/ru/{core-concepts => basics}/astro-pages.mdx
src/content/docs/ru/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/ru/{core-concepts => basics}/layouts.mdx
src/content/docs/ru/{core-concepts => basics}/project-structure.mdx
src/content/docs/ru/{core-concepts => guides}/routing.mdx
src/content/docs/zh-cn/{core-concepts => basics}/astro-components.mdx
src/content/docs/zh-cn/{core-concepts => basics}/astro-pages.mdx
src/content/docs/zh-cn/{core-concepts => basics}/astro-syntax.mdx
src/content/docs/zh-cn/{core-concepts => basics}/layouts.mdx
src/content/docs/zh-cn/{core-concepts => basics}/project-structure.mdx
src/content/docs/zh-cn/{core-concepts => basics}/rendering-modes.mdx
src/content/docs/zh-cn/{core-concepts => guides}/endpoints.mdx
src/content/docs/zh-cn/{core-concepts => guides}/framework-components.mdx
src/content/docs/zh-cn/{core-concepts => guides}/routing.mdx
src/content/docs/zh-cn/{core-concepts/sharing-state.mdx => recipes/sharing-state-islands.mdx
src/content/docs/zh-tw/{core-concepts => basics}/astro-pages.mdx
src/content/docs/zh-tw/{core-concepts => basics}/layouts.mdx
src/content/docs/zh-tw/{core-concepts => basics}/project-structure.mdx
```
</details>

I'll send a PR targeting this PR with the Vercel redirects in a bit

**Comment by at-the-vr** [comment]
Final comment before Check Links gives ✅. Nice to see `routing` is fixed 😄 Redirects working super quick

**Comment by sasoria** [comment]
It was awesome to work on this together 🙌

**Pull request merged**
