### PR TITLE
i18n(zh-cn): Update `mpa-vs-spa.md` translation

### PR DESCRIPTION
**Pull request by earthrule**
#### What kind of changes does this PR include?

- ["MPA vs. SPA"](https://docs.astro.build/zh-cn/concepts/mpa-vs-spa/):Chinese translation of the document
- ["Astro Islands"](https://docs.astro.build/zh-cn/concepts/islands/):Chinese translation of the document

#### Description

- Chinese translation of ["MPA vs. SPA"](https://docs.astro.build/zh-cn/concepts/mpa-vs-spa/) 
- Chinese translation of ["Astro Islands"](https://docs.astro.build/zh-cn/concepts/islands/)

### CODE REVIEW

**Review by delucis — CHANGES_REQUESTED** [review]
Hi @earthrule! Welcome to the Astro docs! I'll ask our other translators to take a look. Please feel free to join us in the #docs-i18n channel [on Discord](https://astro.build/chat) if you like.

I notice you've translated the islands page but we actually already have a translation of that page! https://docs.astro.build/zh-cn/concepts/islands/

Could you remove those changes from this PR? We'd still love to add the MPA vs SPA translation though!

**Comment by earthrule** [comment]
Ok, because I didn't see the Chinese translation of these two articles in the document yesterday, I simply opened this pr.

**Comment by delucis** [comment]
No worries! I think the islands one was translated just before, sorry!

In general you can get an idea of what needs doing here: https://github.com/withastro/docs/issues/438

I would still love to see the MPA vs SPA translation added to docs.

**Comment by earthrule** [comment]
hi, I noticed that https://github.com/withastro/docs/pull/1634 has already translated `mpa-vs-spa.md`

**Comment by earthrule** [comment]
> No worries! I think the islands one was translated just before, sorry!
> 
> In general you can get an idea of what needs doing here: #438
> 
> I would still love to see the MPA vs SPA translation added to docs.

Hi, I noticed that https://github.com/withastro/docs/pull/1634 has already translated `mpa-vs-spa.md`

**Comment by delucis** [comment]
I just saw that! We did get some feedback that a community member preferred your translation. Do you maybe want to review #1634 and make suggestions for anything you think can be improved?

**Comment by delucis** [comment]
Actually — I have a better idea! We can accept their translation _and_ yours. Give me 1 second.

**Review by delucis — COMMENTED** [review]
OK! Now this PR is just _updating_ the other MPA vs SPA translation. What do you think?

**Comment by earthrule** [comment]
> 



> 还行！现在，此 PR 只是_更新_其他 MPA 与 SPA 的转换。你觉得怎么样？

Sorry for causing trouble to the community, I opened this PR because I didn't see the Chinese translations of `MPA vs. SPAs` and `Astro Islands` when I looked at the Doc yesterday.Maybe I should read PRs and Issues more carefully later to open PRs

**Comment by Dustella** [comment]
> > 
> 
> > 还行！现在，此 PR 只是_更新_其他 MPA 与 SPA 的转换。你觉得怎么样？
> 
> Sorry for causing trouble to the community, I opened this PR because I didn't see the Chinese translations of `MPA vs. SPAs` and `Astro Islands` when I looked at the Doc yesterday.Maybe I should read PRs and Issues more carefully later to open PRs

Actually your translations for `MPA vs. SPAs` is better, so we finnally got a better version!

**Comment by earthrule** [comment]
> > > 
> > 
> > 
> > > 还行！现在，此 PR 只是_更新_其他 MPA 与 SPA 的转换。你觉得怎么样？
> > 
> > 
> > Sorry for causing trouble to the community, I opened this PR because I didn't see the Chinese translations of `MPA vs. SPAs` and `Astro Islands` when I looked at the Doc yesterday.Maybe I should read PRs and Issues more carefully later to open PRs
> 
> Actually your translations for `MPA vs. SPAs` is better, so we finnally got a better version!

No seniors, you are great, please forgive my mistake of opening a new pr without looking at the other prs.

**Comment by delucis** [comment]
Thanks for your care and patience @Dustella and @earthrule!

We know it’s sometimes hard to track when a page is not translated yet but there is an open PR. We’d love to improve this experience for you (https://github.com/withastro/docs/issues/1059) when we have time.

**Pull request merged**
