### PR TITLE
glossary: add “Components” and "Islands"

### PR DESCRIPTION
**Pull request by Genteure**
#### Description (required)

Add the first terms to start the glossary page.

#### Related issues & labels (optional)

- Related to: #5035

### CODE REVIEW

**Review by at-the-vr — APPROVED** [review]
Is there a route we can look up in the deployment? I could not find it (`/contributor/glossary` gave 404 😕).
Besides that the content in itself is appropriate 👍

**Comment by at-the-vr** [comment]
sounds good

**Comment by sarah11918** [comment]
Ok reminder, I will not merge any of these into the glossary branch until it seems super obvious that you all are screaming to do so!  Since this PR was made before the branch existed, let me know if I'm needed for anything here. Otherwise, I'll wait for some positive signs re: merging!

**Review by at-the-vr — APPROVED** [review]
LGTM, one thing tony's PR #5546 might cause some conflict besides that its all 👍

**Review by sarah11918 — APPROVED** [review]
Let's get this party started! 🥳

**Pull request merged**
