### PR TITLE
[i18nIgnore] i18n(fr): fix a typo in tailwind.mdx

### PR DESCRIPTION
**Pull request by lou-bi**
#### Description (required)
There is a typo in the `tailwind.mdx` translation in french:
"éfinissez" should be "définissez"

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by thomasbnt — APPROVED** [review]
First contribution, welcome aboard! 🚀🚀 LGTM!

**Comment by McFlyPartages** [comment]
Thanks for contribution.

@lou-bi It's possible to add [i18nIgnore] in the title please

LGTM

**Review by McFlyPartages — APPROVED** [review]

**Comment by lou-bi** [comment]
Like this ?
Thats for Lunaria isn't it ?

**Comment by McFlyPartages** [comment]
> Like this @McFlyPartages ?
> Thats for Lunaria isn't it ?

Yes and yes.

Thanks

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks for the nice catch @lou-bi! 🙌

**Comment by lou-bi** [comment]
Thanks to the team to make this process such an ease !

**Pull request merged**
