### PR TITLE
Fix site title SVG clipping

### LINKED ISSUE #9047: Visual bug: Astro logo is clipped at the bottom
### 📝 Issue Description

The bottom of the flame on the logo in the header is clipped on the bottom
image

### 📋 On which page(s) it occurs

All pages with the header

### 🤔 Expected Behavior

For the logo to not be clipped as it appears in the press page

### 👀 Current Behavior

The logo is clipped

### 🖥️ Browser

Chrome 127.0.6533.72

### 📄 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by in-the-trees**
#### Description (required)

Increasing the height attribute of the SVG by a few pixels resolves the clipping. 

#### Related issues & labels (optional)

- Closes #9047 
- Suggested label: [design](https://github.com/withastro/docs/labels/design)

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Thanks for the PR @in-the-trees! This doesn’t seem to actually fix the issue for me? It breaks focus outlines but otherwise I still see the logo being clipped.

Example of the focus outline:

| Live site | This PR |
|---|---|
| image | image |

**Comment by in-the-trees** [comment]
> This doesn’t seem to actually fix the issue for me? 

Oops, that's my bad for only testing this in Safari 🤦‍♂️ Thanks for catching that.

**Comment by in-the-trees** [comment]
@delucis It should be fixed now! I made sure to do a more thorough test this time — apologies for not doing so the first time around.

**Review by at-the-vr — APPROVED** [review]
LGTM 🥳

**Review by delucis — APPROVED** [review]
Thanks @in-the-trees — looks great 🙌

**Pull request merged**
