### PR TITLE
i18n(zh-tw): update `project-structure.mdx` translation

### PR DESCRIPTION
**Pull request by mingjunlu**
#### Description

- Updates Traditional Chinese translation of `src/content/docs/zh-tw/basics/project-structure.mdx`

#### Related issues & labels

- ~~Closes #~~
- Suggested label: i18n

### CODE REVIEW

**Review by liruifengv — COMMENTED** [review]
I don't have a way to comment on the specified line. 
There are some little issues. 
Does `components` in the page need to be changed to `元件`?

image


There's no translation in English here.

**Comment by mingjunlu** [comment]
> I don't have a way to comment on the specified line. There are some little issues. Does `components` in the page need to be changed to `元件`?
> 
> image
> 
> There's no translation in English here.

Thanks! I've [translated the untranslated paragraph](https://github.com/withastro/docs/pull/7133/commits/7e941f0bf1b8e72e2cbd8ed2a003017853057292) and [improved translation consistency](https://github.com/withastro/docs/pull/7133/commits/7f640698366549d75a0ae06c3f44c15b6fa7a38c).

**Review by liruifengv — APPROVED** [review]
LGTM. Notice that this page uses `FileTree`. I'm trying to replace it with Starlight's `FileTree` in https://github.com/withastro/docs/pull/7182.

**Review by dreyfus92 — APPROVED** [review]
Thank you peeps, LGTM ✅

**Pull request merged**
