### PR TITLE
docs(tutorial): Add null checks to prevent potential errors

### PR DESCRIPTION
**Pull request by Deer404**
Add null checks to prevent potential errors(Optional chaining)

#### Description (required)

When I was following the tutorial and copied the code into the editor, eslint immediately reported an error about a possible null function call, so I suggested adding an optional chain to satisfy developers who use eslint to check.

zh-CN

Yes

### CODE REVIEW

**Comment by yanthomasdev** [comment]
Thanks @Deer404, we only add new content into docs in English, so that it can be first reviewed by our docs lead and then we allow the change (if approve) to be propagated into our translated languages. Could you update this PR to only change the `/en/` version of this file?

**Comment by Deer404** [comment]
> Thanks @Deer404, we only add new content into docs in English, so that it can be first reviewed by our docs lead and then we allow the change (if approve) to be propagated into our translated languages. Could you update this PR to only change the `/en/` version of this file?

Okay, I updated the changes to the English document separately. I think it is necessary to add an optional chain, because when creating a new project tsconfig.json, the default configuration is: "astro/tsconfigs/strict".

**Comment by sarah11918** [comment]
Hi @Deer404 !

>  creating a new project tsconfig.json, the default configuration is: "astro/tsconfigs/strict".

In fact, the tutorial instructions say to begin a new project using Astro's `base` TypeScript setting and this tutorial is intentionally designed to not require or use any TypeScript so that it is beginner friendly.

We have been discussing instead updating each of the samples with tabs to switch between TypeScript and JavaScript, which we think will be more helpful because then people can see/learn the difference, too! It can help people transition from using JavaScript to including more TypeScript in their code.

So, we are not going to make this change at this time because we intend to update the entire tutorial together with TypeScript advice. It does not affect many of our users currently, and the ones it does affect typically recognize and know how to update in their own projects, like you did!

**Comment by Deer404** [comment]
> Hi @Deer404 ! 你好！
> 
> > creating a new project tsconfig.json, the default configuration is: "astro/tsconfigs/strict".创建一个新项目tsconfig.json，默认配置为：“astro/tsconfigs/strict”。
> 
> In fact, the tutorial instructions say to begin a new project using Astro's `base` TypeScript setting and this tutorial is intentionally designed to not require or use any TypeScript so that it is beginner friendly.事实上，教程说明说要使用 Astro 的 `base` TypeScript 设置开始一个新项目，本教程有意设计为不需要或使用任何 TypeScript，因此它对初学者友好。
> 
> We have been discussing instead updating each of the samples with tabs to switch between TypeScript and JavaScript, which we think will be more helpful because then people can see/learn the difference, too! It can help people transition from using JavaScript to including more TypeScript in their code.我们一直在讨论用选项卡更新每个示例以在 TypeScript 和 JavaScript 之间切换，我们认为这会更有帮助，因为这样人们也可以看到/了解其中的区别！它可以帮助人们从使用 JavaScript 过渡到在他们的代码中包含更多的 TypeScript。
> 
> So, we are not going to make this change at this time because we intend to update the entire tutorial together with TypeScript advice. It does not affect many of our users currently, and the ones it does affect typically recognize and know how to update in their own projects, like you did!因此，我们目前不打算进行此更改，因为我们打算将整个教程与 TypeScript 建议一起更新。它目前不会影响我们的许多用户，而它影响的用户通常会识别并知道如何在自己的项目中更新，就像您一样！



> Hi @Deer404 !
> 
> > creating a new project tsconfig.json, the default configuration is: "astro/tsconfigs/strict".
> 
> In fact, the tutorial instructions say to begin a new project using Astro's `base` TypeScript setting and this tutorial is intentionally designed to not require or use any TypeScript so that it is beginner friendly.
> 
> We have been discussing instead updating each of the samples with tabs to switch between TypeScript and JavaScript, which we think will be more helpful because then people can see/learn the difference, too! It can help people transition from using JavaScript to including more TypeScript in their code.
> 
> So, we are not going to make this change at this time because we intend to update the entire tutorial together with TypeScript advice. It does not affect many of our users currently, and the ones it does affect typically recognize and know how to update in their own projects, like you did!

Oh, I didn't check the beginning of the tutorial carefully, thank you for correcting me!

**Pull request closed without merging**
