### PR TITLE
Link the Fontsource docs for Preloading Fonts in the Fonts page

### LINKED ISSUE #7451: Guide on font preloading
### 📚 Subject area/topic

Using custom fonts

### 📋 Suggested page

https://docs.astro.build/en/guides/fonts/

### 📋 General description or bullet points (if proposing new content)

Include information on how to add font preloading.

When a new Astro project is scaffolded using the blog template, `BaseHead.astro` includes font preloading:

image

It would be beneficial if the documentation for setting up fonts included a similar example. 

For the [local font file setup](https://docs.astro.build/en/guides/fonts/#using-a-local-font-file), all that is needed is to add lines like the ones above.

For [Fontsource library](https://docs.astro.build/en/guides/fonts/#using-fontsource) the setup is little bit more complicated. There's seems to be no default way how to do this in the Fontsource but there is a [workaround](https://github.com/fontsource/fontsource/issues/83#issuecomment-957853384)  which seems to be working very nicely in Astro. 

The Astro guide could include something like:

image

### 🖥️ Reproduction of code samples in StackBlitz

_No response_

### PR DESCRIPTION
**Pull request by vivitt**
#### Description (required)

Adds a link in the Using Fontsource section of the Fonts page referencing the Fontsource docs' [Preloading Fonts guide](https://fontsource.org/docs/getting-started/preload).

#### Related issues & labels (optional)

- Closes #7451 

Excited to share my first contribution to Astro Docs  🎉 My Astro Discord username is _vivitt

### CODE REVIEW

**Review by sarah11918 — COMMENTED** [review]
Thank you for adding this helpful resource @vivitt ! I think many people are interested in information about preloading fonts and will appreciate this.

I think it could be *even better* if there could be a one-sentence introduction, though. Right now, we haven't said *anything* about preloading fonts, so it feels like a bit out of nowhere. ("What is this? Why do I want to know about this?)

Would you like to try to add one short sentence *before* this sentence to introduce the concept? A "To speed up  rendering time, you may wish to preload your fonts...." or "Preloading your fonts can help make the page visible to your readers sooner."... 

Think about WHY *you* would use preloading, and make it a "warm up" sentence for the link that provides a bridge between "We just added a font" and "here's a thing you might want to do now after that."

What do you think?

**Comment by vivitt** [comment]
Hello @sarah11918,
Thanks for your quick feedback!
Your suggestions make a lot of sense. I’ve just added one more commit including both changes. Let me know what you think and if you see anything else that can be improved.

**Review by sarah11918 — APPROVED** [review]
Looks great, thank you @vivitt ! Welcome to Team Docs! :partying_face:

**Review by liruifengv — APPROVED** [review]
LGTM! Let's ship it! 🚀

**Pull request merged**
