### PR TITLE
RSS guide: Use `new URL()` instead of template literal

### PR DESCRIPTION
**Pull request by evadecker**
#### Description (required)

The RSS guide currently uses a template literal to concatenate `rss.xml` and `Astro.site`. This works without issue when the site is built, but it raises an ESLint warning:

image

This PR updates the guide to recommend the safer `URL()` constructor to create the link to the `rss.xml` file.

### CODE REVIEW

**Review by at-the-vr — APPROVED** [review]
Great PR Eva 🙌 and thank you for covering all locales as well

**Comment by sarah11918** [comment]
Hi @evadecker , thanks so much for providing this!

Because of our translation status tracking, however, we do ask that PRs only be submitted in one language, then we let the translators catch up. Some of these pages might be out of date translations, some not. Someone might be working on updating a page at the moment!  So, it's always easiest for us to only accept English versions of fixes, even when it *looks* like it should just be a simple fix across the board.

When you remove the other language files, we can get this merged!  🙌

**Comment by evadecker** [comment]
> Hi @evadecker , thanks so much for providing this!
> 
> Because of our translation status tracking, however, we do ask that PRs only be submitted in one language, then we let the translators catch up. Some of these pages might be out of date translations, some not. Someone might be working on updating a page at the moment! So, it's always easiest for us to only accept English versions of fixes, even when it _looks_ like it should just be a simple fix across the board.
> 
> When you remove the other language files, we can get this merged! 🙌

No worries, updated!

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
