### PR TITLE
add new sidebar and page layout

### PR DESCRIPTION
**Pull request by FredKSchott**
## Before
  
Screen Shot 2022-02-28 at 6 06 04 PM

## After

Screen Shot 2022-02-28 at 6 09 24 PM

### CODE REVIEW

**Comment by zadeviggers** [comment]
What's happening to the Netlify logo on the API tab?

**Comment by FredKSchott** [comment]
I'm not sure what was wrong with the svg in that screenshot, but both svg and mobile are now fixed

Bonus: new buttons!

Before: 
Screen Shot 2022-02-28 at 9 22 45 PM

After:

Screen Shot 2022-02-28 at 9 22 30 PM
.

**Comment by sarah11918** [comment]
Love the buttons!

I had to set my browser window zoom to 90% in order to see the right sidebar, though. So, perhaps the layout is optimized for slightly too large screens, and responsiveness kicks in a bit too early?

**Comment by FredKSchott** [comment]
@sarah11918 fixed! Returned to the original breakpoints.

**Comment by sarah11918** [comment]
Looks good on my machine, now!

**Pull request merged**
