### PR TITLE
i18n(zh-cn): Update error-reference.mdx

### PR DESCRIPTION
**Pull request by liruifengv**
#### Description (required)

- Update error-reference.mdx

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/6253

### CODE REVIEW

**Review by huyikai — COMMENTED** [review]
LGTM.

**Comment by Yan-Thomas** [comment]
Thanks @liruifengv, just a heads up I think you added another file by mistake: [src/styles/wechat.css](https://github.com/withastro/docs/pull/6449/files#diff-3e7bc57b0044511315643ece3690fa1dd2255bdb3d500261fc83fa1d95f04769)

**Comment by liruifengv** [comment]
> Thanks @liruifengv, just a heads up I think you added another file by mistake: [src/styles/wechat.css](https://github.com/withastro/docs/pull/6449/files#diff-3e7bc57b0044511315643ece3690fa1dd2255bdb3d500261fc83fa1d95f04769)

Sorry. I deleted it.

**Review by Yan-Thomas — APPROVED** [review]
LGTM!

**Pull request merged**
