### PR TITLE
i18n(de): translate `styling.mdx`

### PR DESCRIPTION
**Pull request by sarasate**
#### What kind of changes does this PR include?

- Translated content

#### Description

- Translate styling.mdx to german

### CODE REVIEW

**Comment by delucis** [comment]
Thank you for this @sarasate! Just checking — should this PR be a draft? I took a quick look at the translated page — https://deploy-preview-2778--astro-docs-2.netlify.app/de/guides/styling/ — and it seemed like everything was there!

**Comment by sarasate** [comment]
@delucis I had a discussion with Hippo on discord about the german translation of `Styles`, `Scoped Styles` etc. Haven't really decided for a solution.  Guess we should discuss that finally all together.

**Comment by Yan-Thomas** [comment]
Thanks for this @sarasate, we had a few small changes to this page last week, could you add these to the PR? I will merge it soon after 🙌 (oops, I accidentally added this message in another PR before 😅) 
https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/styling.mdx

**Comment by sarasate** [comment]
@Yan-Thomas Ok, I'll check that later today.

**Review by Yan-Thomas — APPROVED** [review]
LGTM, thanks @sarasate!

**Pull request merged**
