### PR TITLE
ci: update integration docs

### PR DESCRIPTION
**Pull request by fredkbot**
This PR is auto-generated by a nightly GitHub action to update the individual integration pages from the integration READMEs in withastro/astro.

### CODE REVIEW

**Comment by delucis** [comment]
Oops — didn’t notice when I was reviewing #1777 @mrienstra but one of those files was the MDX integration README that lives in the main Astro repo: https://github.com/withastro/astro/blob/main/packages/integrations/mdx/README.md

We’ll need to make these changes there instead.

**Comment by mrienstra** [comment]
@delucis, d'oh! 🤦 Guess I forgot to scroll up to the top to check, my bad. I think I might still have a few changes leftover from https://github.com/withastro/docs/pull/1729 of the same nature (within .md files pulled automatically from /astro to /docs).

**Comment by delucis** [comment]
Going to merge these now they actually have new content in them even though we lose @mrienstra’s fixes.

@mrienstra Feel free to add your fixes from #1777 to the astro repo when you have a moment!

**Comment by mrienstra** [comment]
@delucis, there seems to be a wee bit of a mystery!

[The anchor I added in #1777](https://github.com/withastro/docs/pull/1777/files#diff-9b31d0786f09a79aa1cd1cb6b8029afd2658cc0a4d9c1bfcc32de6a5b4d4c421L463-R463)

... appears to have been there [since that paragraph was added](https://github.com/withastro/astro/commit/8f8dff4d339a3a12ee155d81a97132032ef3b622#diff-f8b3ea982e3a2f14022902aeaefe786a2477d13f756d4679f70a249b2bacfd7bR397-R399)

... and that paragraph hasn't been changed since, according to [blame](https://github.com/withastro/astro/blame/44fa495/packages/integrations/mdx/README.md#L452-L454).

Very weird! Happy to dig deeper, but thought I'd run it past you first, in case the cause is obvious to you.

Aww nuts, I can't resist a good mystery, I'm diving in!
🤿 🐟 🌊

**Comment by mrienstra** [comment]
Here's the trail:
- [.github/workflows/nightly.yml#L9-L36](https://github.com/withastro/docs/blob/3122ce5/.github/workflows/nightly.yml#L9-L36) 
- [package.json#L16](https://github.com/withastro/docs/blob/3122ce5a0a394dc2d76f979179146a661debd50d/package.json#L16)
- [scripts/lib/filter-warnings.cjs](https://github.com/withastro/docs/blob/3122ce5a0a394dc2d76f979179146a661debd50d/scripts/lib/filter-warnings.cjs)
- [scripts/generate-integration-pages.ts](https://github.com/withastro/docs/blob/3122ce5a0a394dc2d76f979179146a661debd50d/scripts/generate-integration-pages.ts)

**Pull request merged**
