### PR TITLE
i18n(de): Add translations for `i18n/de/ui.ts`

### PR DESCRIPTION
**Pull request by hippotastic**
Adds missing German strings to UI dictionary.

### CODE REVIEW

**Review by Pukimaa — CHANGES_REQUESTED** [review]
This is some great work! But could you give me an url with a site which includes `<Since>` because in your example you wrote "NEW" and in the translation "Neu" which should be "NEU" If your example is correct. I know not your translation but if that would be changed it would be nice!

**Comment by hippotastic** [comment]
@Pukimaa Are you referring to the line `// Used in `<Since>`: Added in: v0.24.0 [NEW]`? This is just a comment that has been copied over 1:1 from the English original. The string that's actually being used is below and correctly states "Neu". 😄

**Comment by hippotastic** [comment]
Oh, and the English original file also doesn't use "NEW" in all uppercase in the actual string: https://github.com/withastro/docs/blob/1317bb6aee86a4d9f63015be524006e873266738/src/i18n/en/ui.ts#L29

**Review by Pukimaa — APPROVED** [review]
Thanks for the explanation for the "New" Tag. I would say it's ready to merge.

**Comment by hippotastic** [comment]
@delucis We're ready to merge here :)

**Review by delucis — APPROVED** [review]
Looks good!

You can see an example of the `Since` component here: https://deploy-preview-483--astro-docs-2.netlify.app/de/reference/configuration-reference/#serverhost

(There's no "new" badge as that is included if the version number where the feature was added is recent enough. It is rendered uppercase using CSS text-transform.)

**Pull request merged**
