### PR TITLE
How to create an index.html at root level via getStaticPaths()

### PR DESCRIPTION
**Pull request by jablonski**
See issue here: https://github.com/withastro/astro/issues/3990

#### What kind of changes does this PR include?

- New or updated content

#### Description

- What does this PR change? Give us a brief description.

Issue is discussed here: https://github.com/withastro/astro/issues/3990

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for this @jablonski. Was there a reason you closed this PR? I'm seeing it documented the recommended technique from https://github.com/withastro/astro/issues/3990

**Comment by jablonski** [comment]
I've closed #3990, because I'm totally fine with _undefined_ as value instead of an empty string to create a top level index.html route, so nothing needs to be fixed. It was just a lack of documentation.

**Comment by jablonski** [comment]
Now I understand the problem. This PR got closed automagically by Github because I've closed #3990. I cannot reopen it, but IMHO it should be merged to the docs.

**Comment by sarah11918** [comment]
Thanks so much for this @jablonski! I followed your thread in Discord, and the Issue you created at withastro/astro for this. I think this is a great addtion to the docs, but maybe this could be expanded to be a bit more than a "tip" to really make sense in context. (And, it means we don't need two "tips" right next to each other.

I like how you presented your discovery of "undefined" in https://github.com/withastro/astro/issues/3990 . Would you be prepared to change this content from a tip to an actual, simple, small code example to illustrate creating the index.html route? I think that would be more clear for the reader of Docs. I think *just* the `export default getStaticPaths()` function that shows setting a parameter to "undefined" alongside some other params?

Let me know what you think! Don't be afraid to just write and suggest something, and we can all discuss further from there!

**Comment by jablonski** [comment]
@sarah11918 I totally agree. 

Just a general thought: maybe it would help people to see self-contained examples in the docs which they can copy/paste to StackBlitz to try out things?

I've created an example, which should show how it should work in general. I'm not so sure about the wording (or the best place to put this example in the docs, because the example shows how to create the index.html at root level, but demonstrates also how to render content with dynamic paths (e.g. from a headless CMS).

Maybe this kind of content should be stored under a "recipes category" and linked from the docs?


```astro
---
export async function getStaticPaths() {
  const pages = [
    {
      slug: undefined,
      title: "Astro Store",
      text: "Welcome to the Astro store!",
    },
    {
      slug: "products",
      title: "Astro products",
      text: "We have lots of products for you",
    },
    {
      slug: "products/astro-handbook",
      title: "The ultimative Astro handbook",
      text: "If you want to learn Astro, you must read this book.",
    },
  ];
  return pages.map(({ slug, title, text }) => {
    return {
      params: { slug },
      props: { title, text },
    };
  });
}

const { title, text } = Astro.props;
---

<html>
  <head>
    <title>{title}</title>
  </head>
  <body>
    <h1>{title}</h1>
    <p>{text}</p>
  </body>
</html>
```

**Comment by jablonski** [comment]
I've created a new PR because I've deleted my fork already, so couldn't update it anymore:

https://github.com/withastro/docs/pull/1389

Sorry for the mess...

**Pull request closed without merging**
