### PR TITLE
i18n(ja): Fix code mistakes in `guides/cms/contentful.mdx`

### PR DESCRIPTION
**Pull request by ot07**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

- What does this PR change? Give us a brief description.
  - Fix code mistakes (copied and pasted from the English version to ensure accurate fixes)

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
Thanks @ot07! I saw the PR fixing the interface references in the English page, could you see if there are any missing of these updates here, so we can merge with everything corrected? Thanks in advance!
 https://github.com/withastro/docs/pull/3324

**Comment by ot07** [comment]
@Yan-Thomas 
I apologize for overlooking the modifications in the English version of the same document. Upon reviewing #3324, it seems that there are updates in this PR that haven't been incorporated yet. I plan to commit those changes as well, albeit with a slight delay.

**Comment by ot07** [comment]
@Yan-Thomas 
I have incorporated the updates from the English version into this PR!

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks for the great work @ot07 💜

**Pull request merged**
