### PR TITLE
perf(ContributorList): save cellular data and improve load time by specifying image size in URL

### PR DESCRIPTION
**Pull request by wtchnm**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

ContributorList: Save cellular data and improve load time by specifying image size in URL

| Before | After |
| ---    | ---   |
| image | image |

I'm participating in Hacktoberfest, so if PR is ok, I'd like it to be labeled as hacktoberfest-accepted.

### CODE REVIEW

**Comment by kevinzunigacuellar** [comment]
hello @wtchnm thank you for the PR, this is a very clever 'hack', I had no idea the endpoint accepted query params to do transforms. 🚀

**Comment by Jutanium** [comment]
LGTM, thank you!

**Comment by sarah11918** [comment]
What a clever, and valuable ($$) PR! Thank you @wtchnm!

**Comment by wtchnm** [comment]
Thanks, @kevinzunigacuellar, @Jutanium, and @sarah11918! I'm happy to help!

**Comment by sarah11918** [comment]
Too many docs PRs merging... need to keep updating the branch! lol.

I'll merge this as soon as the most recent checks finish.  ;)

**Pull request merged**
