### PR TITLE
i18n(fr) Update french translation for all outdated file

### PR DESCRIPTION
**Pull request by McFlyPartages**
#### Description (required)

Update french translation for all outdated files

### CODE REVIEW

**Comment by McFlyPartages** [comment]
> Trois erreurs au niveau des liens, sinon LGTM!

C'est corrigé merci

**Review by thomasbnt — APPROVED** [review]
LGTM!

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
LGTM y'all! Amazing work 🙌

**Pull request merged**
