### PR TITLE
Adam prendergast patch 1

### PR DESCRIPTION
**Pull request by AdamPrendergast**
#### Description (required)

Revised a sentence grammar in the 'headless DAM' sentence in the documentation for clarity.

The 'because' was confusing.

Yes ☺️ This is hopefully a valid hactoberfest update.

Do let me know if I have incorrectly labeled.

Many thanks,
Adam

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
Let's Get That Money! 🎃

**Comment by AdamPrendergast** [comment]
Whoop! Thanks @sarah11918 🙌

**Comment by AdamPrendergast** [comment]
@sarah11918 

Do you happen to know why the official Hacktoberfest is not recognising the repo?

image

**Comment by AdamPrendergast** [comment]
@sarah11918 Ignore my last message... it has picked it up now! ☺️

**Comment by sarah11918** [comment]
@AdamPrendergast If you want *another* Hacktoberfest PR... you made this PR to our beta 5 docs branch. I tried for a moment to repoint it to our main branch, but the two have really diverged and that was more effort to clean up than I cared to go through.  😅 

However, you can feel free to make this exact same PR again to `main` and get yourself a second PR!  😄

**Comment by AdamPrendergast** [comment]
Hi Sarah,

Awesome... I will look at doing that now :)

**Comment by AdamPrendergast** [comment]
Created PR for the above:
https://github.com/withastro/docs/pull/9720

Thanks again!

**Pull request merged**
