### PR TITLE
fix: typo in `ecommerce.mdx`

### PR DESCRIPTION
**Pull request by jsparkdev**
#### Description (required)

- fix typo in `ecommerce.mdx`

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by mearashadowfax** [comment]
LGTM!

**Review by mearashadowfax — COMMENTED** [review]
LGTM!

**Review by mearashadowfax — APPROVED** [review]

**Review by AitorMT — APPROVED** [review]
LGTM!

**Review by TheOtterlord — APPROVED** [review]
Thanks!

**Review by sarah11918 — APPROVED** [review]
Thanks for catching! :partying_face:

**Pull request merged**
