### PR TITLE
i18n(pt-BR): Add new `rendering-modes.mdx` translation

### PR DESCRIPTION
**Pull request by Egpereira**
# Add new `rendering-modes.mdx` translation

## Description

Added new translation for `rendering-modes.mdx` file in pt-BR.

## Dependencies

- [x] This PR will wait until https://github.com/withastro/docs/pull/7887 is merged.

## Considerations

1. On line 42, there is a link to the server side rendering page that is currently outdated in pt-BR, I believe I managed to get the best corresponding content to link, but it would be nice if someone else checked if its ok.
2. I update the `nav.ts` file to group all the "basics" links together, is that ok?

## First-time contributor to Astro Docs

This is my first contributing to the Astro Docs, I'm `.eduardopereira` on Discord 😊

### CODE REVIEW

**Comment by yanthomasdev** [comment]
Thanks @Egpereira, LGTM.

> On line 42, there is a link to the server side rendering page that is currently outdated in pt-BR, I believe I managed to get the best corresponding content to link, but it would be nice if someone else checked if its ok.

Can you roll back this link? I'd rather keep this PR here till we get this other page updated and then we can merge this one with the proper link.

**Comment by Egpereira** [comment]
> Can you roll back this link? I'd rather keep this PR here till we get this other page updated and then we can merge this one with the proper link.

Sure! You mean leave it as `(/en/guides/server-side-rendering/#enable-on-demand-server-rendering)` while we don't update the translation? Can also work on that update next.

**Comment by yanthomasdev** [comment]
> Sure! You mean leave it as (/en/guides/server-side-rendering/#enable-on-demand-server-rendering) while we don't update the translation? Can also work on that update next.

Yes, you can update the language part though, so `/pt-br/guides/server-side-rendering/#enable-on-demand-server-rendering`. This link will break but right after we merge the update on the other page, we update the `#` to match the translated heading and this PR is good to be merged.

**Comment by Egpereira** [comment]
@yanthomasdev switched the PR to a draft and added a dependency in the description to the update at https://github.com/withastro/docs/pull/7770.

**Comment by Egpereira** [comment]
@yanthomasdev this PR can be reviewed now! Should I make a rebase to update ti with the latest changes in main?

**Comment by yanthomasdev** [comment]
> @yanthomasdev this PR can be reviewed now! Should I make a rebase to update ti with the latest changes in main?

Thanks, no need @Egpereira! I just updated branch here 🙌

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks again 🙌

**Pull request merged**
