### PR TITLE
i18n(es): Update `data-fetching.mdx`

### PR DESCRIPTION
**Pull request by Waxer59**
#### Description (required)

Update `data-fetching.mdx` [`5c4e817`](https://github.com/withastro/docs/commit/5c4e817cd2598c70b20a3c442608d35a24495288)

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by K1ri86 — APPROVED** [review]
LGTM!

**Review by at-the-vr — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks for the great work 💜

**Pull request merged**
