### PR TITLE
i18n(fr): update tutorials/add-view-transitions.mdx

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
#### Description (required)

* Add updates made to `tutorials/add-view-transitions.mdx` in #8707
* Replace `page "About"` with `page "À propos"` (since the other ones are translated)
* Translate a missing `Update to Astro v4.x` comment
* Add a space before colon inside comments written in French
* Remove some extra indent on new lines (it was messing with syntax highlighting)

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Comment by liruifengv** [comment]
Hello @ArmandPhilippot Thanks for your update. There are two commits also need to update. 
- https://github.com/withastro/docs/pull/8723
- https://github.com/withastro/docs/pull/7677

**Comment by ArmandPhilippot** [comment]
Thanks @liruifengv, I just added those two changes.

**Review by thomasbnt — APPROVED** [review]
LGTM!

**Review by yanthomasdev — APPROVED** [review]
LGTM! Nice work!

**Pull request merged**
