### PR TITLE
i18n(es): update `server-side-rendering.md`

### PR DESCRIPTION
**Pull request by fredoist**
#### What kind of changes does this PR include?
- New or updated content
- Translated content

#### Description
- What does this PR change? Updates the server side rendering guide with latest changes for Endpoints.

`hacktoberfest-accepted`

### CODE REVIEW

**Comment by fredoist** [comment]
📌 Waiting for #1665 to be merged.

**Review by kevinzunigacuellar — APPROVED** [review]
LGTM!

**Review by agustinmulet — APPROVED** [review]
LGTM! 💯

**Comment by kevinzunigacuellar** [comment]
Gracias! @agustinmulet y @fredoist

**Pull request merged**
