### PR TITLE
Migrate Astro Docs to Lunaria v1 prerelease

### PR DESCRIPTION
**Pull request by yanthomasdev**
#### Description (required)

This PR moves the main Lunaria logic used from v0.1 to the current v1 prerelease. This is meant to unblock #9896 with the new `parameters` options for custom path parameters that will be necessary to move into the new built-in Starlight i18n, as well as make it easy for me to update Lunaria whenever a new bug arises (they're always on the horizon when it comes to my code)

- [X] Migrate Tuesday Bot
- [X] Migrate Lunaria dashboard
- [X] Migrate GitHub Action

To test locally, run `pnpm lunaria:build` and open `dist/lunaria/index.html` in your browser. Then, compare it with https://i18n.docs.astro.build/ to see if there are any differences.

Take in mind this is very early Lunaria v1, things like the dashboard in this PR and soon the updated Action are far from what is planned on the roadmap, so expect something better than that.

### CODE REVIEW

**Comment by yanthomasdev** [comment]
> The build step failed with this error:

oh, this one's already been fixed, I forgot to push the commit 😅, if you `pnpm install` again it should work @delucis

**Comment by ArmandPhilippot** [comment]
Using the same steps as Chris, I get an error too:

```
node:fs:2368
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, open 'dist/lunaria/index.html'
    at writeFileSync (node:fs:2368:20)
    at <anonymous> (myHome/docs/scripts/lunaria.mts:10:1) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/lunaria/index.html'
}

Node.js v20.17.0
```

By creating the file manually in the `dist` folder, the build worked!

I noticed two things:

1. The link for `source change history` uses the current locale instead of English. For example, under the French translations, the source change history link for `guides/deploy/render.mdx` is:
* https://github.com/withastro/docs/commits/main/src/content/docs/fr/guides/deploy/render.mdx?since=2024-07-08T20:09:47+02:00 on my local version (**`/fr/guides`**)
* https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/render.mdx?since=2024-07-08T18:09:47.000Z on [the online version](https://i18n.docs.astro.build/) (**`/en/guides`**)

2. The order of the files is different in "Translation status by file" (e.g. `ui.ts` and `docsearch.ts` are reversed, or `contribute.mdx` which is in the `guides/` list).

lunaria-contribute-in-between-guides

I didn't notice anything else! I don't know if the second point is important, but the first point seems to me to be unwanted.
Don't hesitate to ask for more details if needed! 😉

**Comment by yanthomasdev** [comment]
Thanks @ArmandPhilippot, all of these should be fixed now 🙌

**Review by delucis — APPROVED** [review]
Thanks @yanthomasdev! Looks good to me. I tested the dashboard locally and also ran the Tuesday Discord message script and it all ran as I expected.

Really appreciate how quickly you managed to put this together 💜

**Review by ArmandPhilippot — APPROVED** [review]
I think everything is good this time! No more errors during the build and the display seems identical to me. I didn't notice anything else! Well done! 💯

**Pull request merged**
