### PR TITLE
i18n(ru): Translation of View Transitions page

### PR DESCRIPTION
**Pull request by katokdoescode**
#### What kind of changes does this PR include?

- Translated content

#### Description

- Translates “View Transitions” page to Russian language.

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @katokdoescode ! Just checking if this PR should still be marked as a draft?

I know there have very recently been additions to this page (`## Lifecycle events` section is all new). Are you still able to work on translating this page, and if so, can you please add the changes to the page?

We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this can be ready, we would like to be able to review it.  Thanks!

**Comment by katokdoescode** [comment]
@sarah11918 Yes, I apologize. I'm still working on this translation. I'll upload the changes by the end of this month 🙏🙏🙏

**Comment by sarah11918** [comment]
@katokdoescode No need to apologize! We are very thankful for the translation! I am just checking in on some of our older/draft PRs so that I can better manage for the upcoming Starlight migration. Just seeing how everyone is doing.  :smile:

**Comment by sarah11918** [comment]
Hi @katokdoescode ! This page has now changed a few times since the beginning of this PR. I have updated your branch to match the significant changes that have happened in the code, but I will also close this PR for now since the code will be quite out of date.

Please do reopen this when you have translated and your content is ready for review! We are happy to have your translation! 

But, we prefer not to keep draft PRs open for too long, and prefer that you open a PR when the translation is mostly completed and ready for review. This is the easiest way for us to keep on top of the several open PRs we have to manage, and to make sure PRs don't get out of date, and need to be updated again before they're even merged! 😄

**Pull request closed without merging**
