### PR TITLE
i18n(es): Updated graphql example

### PR DESCRIPTION
**Pull request by sasoria**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Updated the graphql example from this [commit](https://github.com/withastro/docs/commit/6b4fc99ee1924298ab1904be42c715f27000a001).

### CODE REVIEW

**Comment by dreyfus92** [comment]
Hey @sasoria, thanks for bringing this up, but I think that in order to make an update on the docs, you should start by updating the EN version of them which is the default one. Afterwards if your pr gets merged the script that we have built in in the repo will notify other if the EN version was updated and check if other langs require to make the update based on the changes that were applied to the EN version of the docs.

**Comment by sasoria** [comment]
Thanks for the explanation, but I'm not sure I understand. I updated the EN docs in march and the changes never made it to the ES docs. Here's the original [issue](https://github.com/withastro/docs/issues/2775) I solved.

Do we still want the outdated example in the ES docs?

**Comment by dreyfus92** [comment]
My bad I wasn't aware that this was previously updated, I just noticed that our script never notified us about this update. You can check here what notify us when something needs to be updated to other locales [The Translation Status Overview](https://i18n.docs.astro.build/)

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by Waxer59 — APPROVED** [review]
LGTM ✔

**Review by Yan-Thomas — APPROVED** [review]
Nice catch, thanks peeps!

**Pull request merged**
