### PR TITLE
Fix several issues in the middleware documentation

### PR DESCRIPTION
**Pull request by wackbyte**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

A (maybe not-so-brief) description:

- Fixed a few cases where the `title` for code blocks was incorrectly spelled `tilte` instead
- Fixed `MiddlewareResponseHandler` being incorrectly referred to as `MiddlewareRequestHandler` instead
- Fixed a line comment that should've been a block comment and was cutting off the end of the line
- Replaced `html.replace` with `html.replaceAll` in the "redacting sensitive information" example
- Added a missing `title`
- Removed a draft version of the example for chaining middleware
- Fixed inconsistent indentation and formatting
- Added missing semicolons
- Removed extraneous spaces
- A few grammar fixes

I see that there may be conflicts once #3514 gets merged, so I'm ready to fix them.

### CODE REVIEW

**Comment by wackbyte** [comment]
Some of these issues (namely code formatting and misspelled `title` on code blocks) are now present in the Spanish translation.

**Comment by sarah11918** [comment]
Thanks @wackbyte - Fortunately, our Spanish translators will see notification that this file has changed, and they'll apply whatever fixes we make here!

And, Updating the branch here should have picked up anything merged in #3514, so no worries there, either! I'm going to try to get this one all vetted and merged today! Thanks for your patience!  :raised_hands:

**Comment by wackbyte** [comment]
Thank you!

**Review by sarah11918 — APPROVED** [review]
This looks great, @wackbyte! Thanks for your attention to detail!  :raised_hands:

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks @wackbyte 🙌

**Pull request merged**
