### PR TITLE
i18n(fr): add migrate-to-astro/from-create-react-app.mdx

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
#### Description (required)

* Translate [Migrating from Create React App](https://docs.astro.build/en/guides/migrate-to-astro/from-create-react-app/) (`migrate-to-astro/from-create-react-app.mdx`) added in #3788

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Comment by thomasbnt** [comment]
aaaah same time xD
I just created a draft PR with migrating guides https://github.com/withastro/docs/pull/8732, and this file is counted

**Comment by ArmandPhilippot** [comment]
@thomasbnt Ah sorry, I started early and I saw no PR so... I didn't checked before pushing. 😕 Maybe I should have warned on Discord (I finally found the `i18n-crew-fr` thread 😆 ). I can close this pull request if you prefer since you have already translated this file...

**Comment by thomasbnt** [comment]
> @thomasbnt Ah sorry, I started early and I saw no PR so... I didn't checked before pushing. 😕 Maybe I should have warned on Discord (I finally found the `i18n-crew-fr` thread 😆 ). I can close this pull request if you prefer since you have already translated this file...

I can remove this file from my PR if you want. I don't work on nuxtjs, nextjs and gastby for the moment

**Comment by ArmandPhilippot** [comment]
@thomasbnt I did a quick read and the file looks good (except a broken link :wink: ), so I'm closing this PR! I probably won't translate anything by tomorrow, so I'll check Discord for anything new. The list of files is getting smaller! 😃 

Duplicate of #8732

**Pull request closed without merging**
