### PR TITLE
i18n(es): Update `cli-reference.mdx` & `troubleshooting.mdx`

### PR DESCRIPTION
**Pull request by Waxer59**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.

`cli-reference.mdx` [`35a6255`](https://github.com/withastro/docs/commit/35a6255be7cfff1bf912b8e7b9a90dc758d2b9e7)

`troubleshooting.mdx` [`e40a703`](https://github.com/withastro/docs/commit/e40a7032ac0a909b17cdf2351a92160273f396b9#diff-0cfad3157930d43803d22899fe98b8f9ccfa0eaadf4e16adda85f8fc980e3af3R97) & Some missing sections have been added

### CODE REVIEW

**Review by dreyfus92 — CHANGES_REQUESTED** [review]
Buen trabajo @Waxer59 😁, te dejo una pequeña sugerencia.

**Comment by Waxer59** [comment]
Listo!, gracias por la revisión 🤠

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
Amazing work, thanks peeps 🙌

**Pull request merged**
