### PR TITLE
i18n(fr): Fix language inconsistency in blog tutorial

### PR DESCRIPTION
**Pull request by Nishogi**
#### Description

In the french tutorial for making a blog in Astro, the first `blog.astro` file proposed is written in English. Later on, the same file is showed in a french version. I replaced the first occurence with the first version for consistency.

### CODE REVIEW

**Comment by Nishogi** [comment]
Changing little details in several pages

**Review by dreyfus92 — APPROVED** [review]
Thank you for handling this @Nishogi 😁, LGTM ✅

**Review by thomasbnt — APPROVED** [review]
LGTM 🕺

**Review by sarah11918 — APPROVED** [review]
Merci bien, @Nishogi! We appreciate you taking the time to improve the tutorial. Bienvenue a Team Docs! :partying_face:

**Pull request merged**
