### PR TITLE
i18n(fr): update `community-resources/content.mdx`

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
#### Description (required)

* Add a new community recipe (see #8854)
* Translate all the links in French (It was a mix between English and French with no reason. I had talked about it with @thomasbnt  [on Discord](https://discord.com/channels/830184174198718474/971729943786561556/1258738049408569344) so while I was here and to keep link anchors consistent, I translated all the links)

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Review by thomasbnt — APPROVED** [review]
Good! LGTM!

**Comment by yanthomasdev** [comment]
👋 we're missing a small commit here, after this LGTM: https://github.com/withastro/docs/commit/cda574f31bb3bb409a5521f0bf2388bc89198acf

**Comment by ArmandPhilippot** [comment]
Thanks @yanthomasdev! I missed that update...

**Review by yanthomasdev — APPROVED** [review]
LGTM! Amazing work! 🙌

**Pull request merged**
