### PR TITLE
Fixed InferGetStaticPropsType example to use Props type

### PR DESCRIPTION
**Pull request by marceloverdijk**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content
- Changes to the docs site code
- Something else!

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

### CODE REVIEW

**Comment by delucis** [comment]
Thanks for this @marceloverdijk. Astro's language server actually automatically knows that Astro.props has the type of a local `Props` type so this shouldn't be necessary. Are you seeing a situation where that doesn't work?

**Comment by marceloverdijk** [comment]
@delucis yes I noticed an issue in VS code:

When having just:

```
export async function getStaticPaths() {
  const drivers = await prisma.driver.findMany({
    select: {
      id: true,
    },
  })
  return drivers.map((driver) => {
    return {
      params: { id: driver.id },
    }
  })
}

type Params = InferGetStaticParamsType<typeof getStaticPaths>

const { id } = Astro.params // so without as Params
```

VS code will state that the `id` is of type: `const id: string | undefined`
and it gives me other type issues using that `id`.

When changing it to:

```
const { id } = Astro.params  as Params
```

then the type inferring works as expected and the `id` has the correct type.

Note that Astro [docs](https://docs.astro.build/en/guides/typescript/) also do that:

```
---
import { InferGetStaticParamsType, InferGetStaticPropsType } from 'astro';

export async function getStaticPaths() {
  const posts = await getCollection('blog');
  return posts.map((post) => {
    return {
      params: { slug: post.slug },
      props: { draft: post.data.draft, title: post.data.title },
    };
  });
}

type Params = InferGetStaticParamsType<typeof getStaticPaths>;
type Props = InferGetStaticPropsType<typeof getStaticPaths>;

const { slug } = Astro.params as Params;
//                      ^? { slug: string; }
const { title } = Astro.props;
//                      ^? { draft: boolean; title: string; }
---
```

Note that the docs only use `as Params` for the `Astro.params` but not `as Props` for the `Astro.props` (https://github.com/withastro/docs/pull/2969)

**Comment by marceloverdijk** [comment]
PS I initially created this PR which is related: https://github.com/withastro/astro.build/pull/640

**Comment by delucis** [comment]
Right, we don’t currently auto-type `Astro.params`. But we _do_ for `Astro.props` which is what this PR is proposing changing, right?

**Comment by marceloverdijk** [comment]
Ah I see, then you are absolutely right. Sorry for confusion.

I've updated https://github.com/withastro/astro.build/pull/640 as well to only include the `as Params` part in the blog post.

**Pull request closed without merging**
