### PR TITLE
i18n(zh-cn): Update `guides/migrate-to-astro/from-gatsby.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### Description (required)

Update `guides/migrate-to-astro/from-gatsby.mdx`

Upstream PR:

- #6833

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by liruifengv — APPROVED** [review]
LGTM!

**Review by AitorMT — APPROVED** [review]
LGTM

**Comment by liruifengv** [comment]
!coauthor

**Comment by liruifengv** [comment]
Thanks for the review! @AitorMT

**Comment by AitorMT** [comment]
I just realized it, when I checked it again. Sorry for my changes review. In the last line the url to change `en` to `zh-cn` is missing.

**Pull request merged**
