### PR TITLE
i18n(zh-cn): update guides/integrations-guide.mdx

### PR DESCRIPTION
**Pull request by fuguid**
#### What kind of changes does this PR include?

- New or updated content

#### Description

Update guides/integrations-guide.mdx
Changed 'Not building a sitemap on Windows' -> 'Skipping sitemap construction on Windows', it feels more fluent.

### CODE REVIEW

**Comment by liruifengv** [comment]
hello。你好像没有在 issue 认领哈。另外，PR的描述要改一下

**Comment by fuguid** [comment]
好的谢谢

**Comment by fuguid** [comment]
https://github.com/liruifengv/docs/issues/1

**Comment by fuguid** [comment]
https://github.com/liruifengv/docs/issues/1

**Comment by liruifengv** [comment]
PR 的分类需要调整，留下你此次修改的分类，删除其他的。

另外，尽量用英文

**Review by liruifengv — APPROVED** [review]
LGTM!

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks 💜

**Pull request merged**
