### PR TITLE
Update zh-tw translations

### PR DESCRIPTION
**Pull request by ymcheung**
- [x] ui.ts
- [x] nav.ts 
- [x] Get Started

### CODE REVIEW

**Comment by delucis** [comment]
Hi @ymcheung — thanks so much for doing this! ❤️ 

Can I suggest you hold off on translating the other pages yet? We’re currently refreshing some of those pages so we’re trying to avoid translating them until they’re more stable so translators don’t end up doing twice as much work.

Also, if you’d like to be more involved in translating the docs, we’d love to welcome you in [the Astro Discord](https://astro.build/chat). We have a dedicated `#docs-18n` channel for discussing all things translation and internationalization.

**Comment by ymcheung** [comment]
> Can I suggest you hold off on translating the other pages yet? We’re currently refreshing some of those pages so we’re trying to avoid translating them until they’re more stable so translators don’t end up doing twice as much work.

Sure! I will translate only `Get Started` page in this PR.

> Also, if you’d like to be more involved in translating the docs, we’d love to welcome you in [the Astro Discord](https://astro.build/chat). We have a dedicated `#docs-18n` channel for discussing all things translation and internationalization.
Joined! 🤘

**Comment by sarah11918** [comment]
Yay, nice to have you onboard @ymcheung ! 🥳

**Review by delucis — APPROVED** [review]
Thanks again for this!

**Pull request merged**
