### PR TITLE
Fix broken link to 'reading time' example

### PR DESCRIPTION
**Pull request by Alynva**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

- What does this PR change? Give us a brief description.
  - Fix broken link to 'reading time' example that is now a reciple
  - Maybe this commented text should be ~~a `:::note` outside the code snippet~~ rewriten so the instructions are clear (as pointed by @sarah11918 )

### CODE REVIEW

**Review by ElianCodes — APPROVED** [review]
Hey @Alynva Thanks for updating the link to our new recipe!

**Comment by sarah11918** [comment]
Nice job spotting the link! Looking at this now, I totally agree @Alynva - Let's keep that code snippet short and sweet, and let's use our Recipe component to link to the Reading time recipe!

**Comment by Alynva** [comment]
> Nice job spotting the link! Looking at this now, I totally agree @Alynva - Let's keep that code snippet short and sweet, and let's use our Recipe component to link to the Reading time recipe!

Should I open a different PR or just commit it in here?

**Comment by sarah11918** [comment]
@Alynva Depends, how many PR credits do you want??  :wink: 

Either is fine! You decide, and let us know!

**Comment by Alynva** [comment]
@sarah11918 just commited here, let me know if its everything right 😃

**Comment by sarah11918** [comment]
@Alynva Looks great! Let's ship it!  :ship:

**Review by sarah11918 — APPROVED** [review]
Adding to the merge queue...

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks @Alynva

**Pull request merged**
