### PR TITLE
change action name from addToCard to addToCart

### PR DESCRIPTION
**Pull request by Grahf0085**
I believe addtoCard is a small spelling error and the correct name for the action should be addToCart. Sorry if I misunderstood.

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by apatel369 — APPROVED** [review]
Nice catch! Welcome to Team Doc!

**Review by sarah11918 — APPROVED** [review]
Great catch @Grahf0085 ! Thanks so much for taking the time to make this fix, and again, welcome to Team Docs! 🥳

**Comment by sarah11918** [comment]
!coauthor

**Comment by sarah11918** [comment]
Note that this error is present in the two currently translated and up to date pages: `fr` and `ko` as the code sample I'm sure was just copy-pasted. So, we do want Lunaria to update these pages' status!

**Pull request merged**
