### PR TITLE
Track Korean Translations in Status Overview Issue

### PR DESCRIPTION
**Pull request by Yan-Thomas**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

Add Korean translations to the Status Overview Issue.

### CODE REVIEW

**Review by delucis — APPROVED** [review]
Thanks for updating that @Yan-Thomas!

**Comment by delucis** [comment]
Oh actually. Do you want to add the other missing languages while you're here?

**Comment by Yan-Thomas** [comment]
> Oh actually. Do you want to add the other missing languages while you're here?

Oops. Not in this PR anymore, but sure! Will make a new one adding the others 😅!

**Comment by delucis** [comment]
Thanks! My idea was just to import from our `languages.ts` file but that would require converting this script to Typescript so up to you if you want to do that or just add the strings manually.

**Pull request merged**
