### PR TITLE
[i18nIgnore] i18n(zh-cn): delete DontEditWarning & Video

### PR DESCRIPTION
**Pull request by liruifengv**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
#### Description

- delete DontEditWarning & Video

#### Related Issue / Implementation PR

- Closes Issue #

### CODE REVIEW

**Comment by liruifengv** [comment]
Wait https://github.com/withastro/docs/pull/4821 merged

**Comment by Genteure** [comment]
Should this be marked as `[i18nIgnore]`?

**Comment by liruifengv** [comment]
> Should this be marked as `[i18nIgnore]`?

不用，改中文不会对其他产生影响

**Comment by Genteure** [comment]
But it would affect [the i18n tracker](https://i18n.docs.astro.build/) and mark these pages as up to date. It wouldn't matter if all the pages edited is already up to date anyways, but you never know what might get merged into the English `main` before this PR gets merged.

**Comment by liruifengv** [comment]
> But it would affect [the i18n tracker](https://i18n.docs.astro.build/) and mark these pages as up to date. It wouldn't matter if all the pages edited is already up to date anyways, but you never know what might get merged into the English `main` before this PR gets merged.
 
Done

**Review by Yan-Thomas — APPROVED** [review]
LGTM!

**Pull request merged**
