### PR TITLE
Add first-timer message to PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by sarah11918**
#### Description (required)

This might help when trying to find first-time contributors on Discord for their first-time contributor alert!

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Amazing idea, loved it 😁

**Review by ElianCodes — APPROVED** [review]
This is actually amazing!

**Review by TheOtterlord — APPROVED** [review]
Great idea!

**Review by delucis — COMMENTED** [review]
Love this idea!

Only tiny nit pick is that this format requires people to remember to delete a new heading in the template each time they open a PR.

Perhaps could be *only* a comment in the description section?

**Review by VoxelMC — APPROVED** [review]
Awesome, no more missing people!
I agree with Chris about the deleting, perhaps it is worth commenting out the heading as well, and add an "uncomment this" like the above.

Either way, it's great!

**Comment by sarah11918** [comment]
Thanks all! We'll try out this new version and see how we like it!

**Pull request merged**
