### PR TITLE
Remove start command

### PR DESCRIPTION
**Pull request by TheOtterlord**
#### Description (required)

Remove references to the `start` command as a `dev` alias, and update deploy guides.

#### Related issues & labels (optional)

https://github.com/withastro/astro/pull/12200

### CODE REVIEW

**Comment by sarah11918** [comment]
Thanks for jumping in with this @TheOtterlord !

Just noting that we will also need to update Step 2 here, showing adding the scripts yourself to 	`package.json`!

https://docs.astro.build/en/install-and-setup/#manual-setup

**Comment by casungo** [comment]
If its alright with everyone I can look into this :)

**Comment by sarah11918** [comment]
Hey @casungo ! I think @TheOtterlord is talking with the core team about whether this is happening for only 5 beta etc, and collecting more info. So best to hold off and wait for him!

**Review by sarah11918 — APPROVED** [review]
Looks great, thank you @TheOtterlord !

**Pull request merged**
