### PR TITLE
Hungarian Translation for Getting-Started + Config

### PR DESCRIPTION
**Pull request by lostra01**

### CODE REVIEW

**Comment by lostra01** [comment]
Added pages for Quick Start and Installation
Fixed links to parts of documentation that are not yet translated
Fixed typos in Getting Started page
Fixed wrong line breaks in Getting Started, especially where they break code snippets

**Comment by sarah11918** [comment]
Sorry, all I could really do to review this was check a bunch of the links, and Google Translate it to English to see whether anything jumped out at me. Not nearly the kind of review that your work deserves! But nothing stood out as not working or wrong to me from what little I could check.

**Review by jonathantneal — APPROVED** [review]

**Review by jonathantneal — APPROVED** [review]
The docs are for everyone! Yay! :)

Thank you, again, @lostra01!

**Comment by lostra01** [comment]
Thank you! Both of you :) I shall try to get a few more pages down tonight or over the weekend so expect some more PRs in the near future! To the moon!

**Pull request merged**
