### PR TITLE
docs(zh-CN): translate editor setup and migrate

### PR DESCRIPTION
**Pull request by kecrily**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [x] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

Translate editor setup and migrate

### CODE REVIEW

**Review by delucis — DISMISSED** [review]
Nice! Thank you so much @kecrily 

I think the changes in `pnpm-lock.yaml` don’t need to be included in this PR, would you mind removing them?

**Comment by kecrily** [comment]
Ok, but do we also need to update the pnpm version to v7?

**Comment by delucis** [comment]
> Ok, but do we also need to update the pnpm version to v7?

I think eventually, but currently we build using Node v14 which isn’t compatible with pnpm@7, so we need to move both together at some point.

**Review by delucis — APPROVED** [review]
Just checked the content here using Google Translate and it looks good to me. I can’t speak to any language details, but at least the translation matches the original content 🙌

**Pull request merged**
