### PR TITLE
i18n(ar): create tutorial/0-introduction/1.mdx file

### PR DESCRIPTION
**Pull request by d3vma**
#### Description (required)

AR translation for 0-introduction/1.mdx

Username on discord: d3vma

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by BassamXYZ** [comment]
You should also translate `title` and `description` values on the file frontmatter.
Every thing else is good.

**Comment by d3vma** [comment]
> You should also translate `title` and `description` values on the file frontmatter. Every thing else is good.

Thanks, updated.

**Comment by BassamXYZ** [comment]
LGTM! Thanks.

**Comment by yanthomasdev** [comment]
Thanks @d3vma, we only merge translations into docs once they're fully translated, so I'm going to point this PR to the `ar/tutorial` branch and we can merge it once all pages are translated 🙌

**Pull request merged**
