### PR TITLE
i18n(fr): Updating docsearch elements translation

### PR DESCRIPTION
**Pull request by pioupia**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
I updated the translation of `docsearch.ts` file.

### CODE REVIEW

**Review by thomasbnt — APPROVED** [review]
Lgtm!

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Comment by McFlyPartages** [comment]
LGTM

**Review by ElianCodes — APPROVED** [review]
Merci beaucoup @pioupia!

**Pull request merged**
