### PR TITLE
Update NGINX example

### PR DESCRIPTION
**Pull request by radenpioneer**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

- Updated NGINX example to include EXPOSE. Without it, anyone the `Dockerfile` will close immediately after running. This will be helpful for anyone new with Docker.

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Comment by ElianCodes** [comment]
I'm travelling/attending RenderATL. I'll check this out as soon as I can!

**Comment by sarah11918** [comment]
Thank you, @radenpioneer!  :raised_hands:  Leaving this one for @ElianCodes to merge when he's happy!

**Review by ElianCodes — APPROVED** [review]
LGTM! I see that I did include it in the rest of the examples, so it should be here as well!

Thanks for noticing and fixing this @radenpioneer ! 🚀

**Pull request merged**
