### PR TITLE
i18n(ko-KR): update `render.mdx`

### PR DESCRIPTION
**Pull request by jsparkdev**
#### Description (required)

- update `render.mdx`
- #9914

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by liruifengv — APPROVED** [review]
LGTM!

**Comment by jsparkdev** [comment]
@liruifengv Thank you. That's a great tip!

**Comment by liruifengv** [comment]
You can merge them now! @jsparkdev

**Comment by jsparkdev** [comment]
@liruifengv Ah, so this is how it's done! Thanks, I now know how to merge PRs properly. Thanks :)

**Comment by liruifengv** [comment]
> @liruifengv Ah, so this is how it's done! Thanks, I now know how to merge PRs properly. Thanks :)

It is best to wait for the CI to run successfully before merging

**Pull request merged**
