### PR TITLE
i18n(de): Update `rss.mdx` translation

### PR DESCRIPTION
**Pull request by selfire1**
#### What kind of changes does this PR include?

- Translated content

#### Description

The previous German version of `rss.xml` was moved to `old-translations` since it was outdated: https://github.com/withastro/docs/issues/4472.

I updated the German translation for `guides/rss.xml` to be at the same state as the English version.

#### Discussion point: Replacing English links
There are two external links in the original
1. One about promoting your feed: https://medium.com/samsung-internet-dev/add-rss-feeds-to-your-website-to-keep-your-core-readers-engaged-3179dca9c91e#:~:text=com/~deno%2Drss-,Advertising%20your%20RSS%20feed,-Now%20you%20have
2. The other is a general explanation of RSS feeds: https://aboutfeeds.com/

I am unaware of an adequate German replacement for link #1.

I researched a bit for possible general explanations of RSS in German. This site, https://www.rss-readers.org/einfuehrung-in-rss/, seems to convery similar information to the English version. But I dislike the cookies popup and find the links in the footer to Weight Watchers and AVZ a bit dubious. It also lacks the Creative Commons license of the English original.

Since the replacement options weren't convincing to me, I kept the English links in this PR. But I'd love for others to weight in on what possible localised links could be.

#### Uncertainties

I was a bit uncertain translating the `Using an older version?` aside title. "Verwendest du eine ältere Version?" is what I settled on, although it's more verbose. "Auf einer älteren Version?" was another alternative that I considered.

🐥 This is my first PR and translation of this kind! I tried my best to follow the _Anleitung für deutsche Übersetzungen_ and proofread for typos. Please feel free to let me know when I missed best practices or when things just sound strange. Immer frei raus!

### CODE REVIEW

**Review by bennykay — CHANGES_REQUESTED** [review]
In line 76 you write `RSS feed`, but further down you use `RSS feed`. I would prefer the spelling `RSS-Feed` and use it everywhere.

In line 227 you write `bewerden`, I think it should say `bewerben`.
After that in line 227, you forgot the word 'du', and you used the word `in` twice in a row. 

The sentence should read like this: `Durch das Hinzufügen des Standard-RSS-Symbols kannst **du** deine Leser wissen lassen, dass sie deine Beiträge in ihrem eigenen Feed-Reader abonnieren können.`

**Comment by selfire1** [comment]
Hi @bennykay, thanks for reviewing and surfacing those issues! I changed the three things you mentioned. Let me know if it looks good to you with those changes.

**Review by bennykay — CHANGES_REQUESTED** [review]
On Line 227, there is one too many periods at the end of the sentence.

**Review by bennykay — APPROVED** [review]

**Comment by Yan-Thomas** [comment]
Hey, thanks @selfire1, this looks great!

Answering your question re: localized links, we generally recommend keeping the original ones in English, except the page we linked (e.g. MDN, web.dev) has an official translation for it with the same content.

**Review by Yan-Thomas — APPROVED** [review]

**Pull request merged**
