### PR TITLE
i18n(es): add ssr page

### PR DESCRIPTION
**Pull request by kevinzunigacuellar**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [x] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

- Adds `guides/server-side-rendering.md` in Spanish
- Updates page name in `nav.ts`
- Update page to match #759

### CODE REVIEW

**Comment by sarah11918** [comment]
Oh no @kevinzunigacuellar - I changed this page out from under you!  😅

**Review by agustinmulet — COMMENTED** [review]
Small suggestions, looking good!

**Comment by kevinzunigacuellar** [comment]
LGTM! 🚀

**Comment by Yan-Thomas** [comment]
Nice work guys, time to merge :rocket:!

**Pull request merged**
