### PR TITLE
i18n(zh-cn): Translate core-concepts/endpoints、project-structure、sharing-state

### PR DESCRIPTION
**Pull request by lhz960904**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- update core-concepts  translation content
   - endpoints
   - project-structure
   - sharing-state

### CODE REVIEW

**Comment by liruifengv** [comment]
Maybe is `core-concepts`?

**Comment by liruifengv** [comment]
Some little missing:

for endpoints:
- https://github.com/withastro/docs/commit/8077640390594eab66c6497d5e9146c2e5bef371
- https://github.com/withastro/docs/commit/33b3229039014f1f9b7ab843300a0c630b1785f3
- https://github.com/withastro/docs/commit/046e0af9329b5f23bbc8dcde58681a4d956f3261


for project-structure:
- https://github.com/withastro/docs/commit/577ca11ac53006ab4e029f72c578b92c07fb3b93
- https://github.com/withastro/docs/commit/577ca11ac53006ab4e029f72c578b92c07fb3b93

**Review by liruifengv — CHANGES_REQUESTED** [review]
Some missing about endpoints.dx & project-structure.mdx.

**Comment by lhz960904** [comment]
> Some missing about endpoints.dx & project-structure.mdx.

very thanks to you review my commit and find missing some content。I added or update them 😃

**Review by liruifengv — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
