### PR TITLE
Enable content collection cache

### PR DESCRIPTION
**Pull request by delucis**
#### Description (required)

- Re-enables the experimental content collection caching feature

### CODE REVIEW

**Comment by delucis** [comment]
Looks like there's still a bug. Initial build for this branch succeeded, then when I re-ran the deployment with the same build cache, it failed.

**Comment by matthewp** [comment]
@delucis how are you rerunning the deployment? I don't see it on the page. In any event, mind rerunning it again? I upgrade to the latest Astro, not sure if that's the reason yet, though.

**Comment by delucis** [comment]
Redeployed manually from the Vercel dashboard. Just triggered one again.

**Comment by matthewp** [comment]
Ok thanks, think this is some extra information we need to retain in our cache manifest, will work on it.

**Comment by matthewp** [comment]
@delucis I did a preview release with what I think is the fix. Can you try rerunning? Thanks.

**Comment by delucis** [comment]
Looking good! https://vercel.com/astrodotbuild/docs/CPitQx2B7xJkUTiUKZvbvFUCypvA

**Comment by delucis** [comment]
Marking this as a draft until https://github.com/withastro/astro/pull/11170 is released.

**Review by TheOtterlord — APPROVED** [review]
lgtm :partying_face:

**Pull request merged**
