### PR TITLE
i18n(es) server-side-rendering.mdx

### PR DESCRIPTION
**Pull request by AitorMT**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content

#### Description

- Removed `Astro.redirect` to conform to the English documentation.
- Fixed the following broken links `redirect-with-no-location.mdx` and `static-redirect-not-available.mdx`.

### CODE REVIEW

**Comment by Waxer59** [comment]
Bien visto 🤠, habria que arreglar dos enlaces rotos, el de la página `redirect-with-no-location.mdx` tendria que apuntar a `es/reference/api-reference/#astroredirect` y el de la página `static-redirect-not-available.mdx` igual!

**Review by Waxer59 — APPROVED** [review]
LGTM ✔

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
Nice catch! LGTM!

**Pull request merged**
