### PR TITLE
i18n(es) Redundant description

### PR DESCRIPTION
**Pull request by AitorMT**
#### What kind of changes does this PR include?

- New or updated content

#### Description

The deleted text is because it is redundant information, in the following paragraph, which is the one that is maintained, it gives the same information and is more complete. If it is kept, it would be the same in the first paragraph as in the second.

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Nice catch this wasn't updated/removed as the `en` version of the docs, thank you for this @AitorMT. LGTM ✅

**Review by nabu1615 — APPROVED** [review]
It looks good to me, the text is redundant and it is not necessary.

**Review by Waxer59 — APPROVED** [review]
LGTM ✔

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Nice catch @AitorMT 🙌

**Pull request merged**
