### PR TITLE
i18n(zh-cn): update `guides/deploy/github.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### Description (required)

update `guides/deploy/github.mdx`

#### Related issues & labels (optional)

#5131

### CODE REVIEW

**Comment by 100gle** [comment]
@Yan-Thomas the reason of failed checking ci is so weired. Even I didn't change anything about sitemap or other languages version. How to solve it?

**Comment by Yan-Thomas** [comment]
> @Yan-Thomas the failed reason of checking CI is so weired. Even I didn't change anything about sitemap or other languages version. How to solve it?

Oh, this happens because sometimes GitHub fails to send the data we need for the contributors/translators list, so this issue happens. Rerunning the CI (be it manually or by adding a commit) solves it.

**Review by liruifengv — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
