### PR TITLE
Add retry logic to fetch

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- Something else!

#### Description

Adds retry logic to our `githubGet` helper to try and mitigate the regular CI failures we get for “Invalid response body” when generating integration pages. Here’s a recent example: <https://github.com/withastro/docs/runs/7837529942?check_suite_focus=true#step:4:18>

### CODE REVIEW

**Review by hippotastic — CHANGES_REQUESTED** [review]
Hey, thanks a lot for working on improving this! The approach you're suggesting would result in hammering the API with consecutive requests without any timeout or randomization though.

I would prefer if we could use one of the popular battle-tested retry packages like https://www.npmjs.com/package/p-retry instead of implementing our own retry logic. What do you think?

**Comment by delucis** [comment]
Thanks @hippotastic — yeah, this was quick and dirty, sorry! I’ll take a look at that suggestion. I’m also wondering if there’s a nice way to generalise this. We sometimes use `fetch` directly, other times `githubGet`.

**Review by natemoo-re — APPROVED** [review]

**Comment by natemoo-re** [comment]
Ha I retract my approval! @hippotastic's suggestion is much better!

**Comment by hippotastic** [comment]
I used `p-retry` now as discussed and tested it locally by simulating a connection error. It's retrying in exponentially increasing intervals for up to 5 times now. PTAL @delucis :)

**Review by hippotastic — APPROVED** [review]

**Comment by hippotastic** [comment]
(Please disregard my self-approval. I tried to declare my old review with requested changes as outdated and this was the result. 😆)

**Review by natemoo-re — APPROVED** [review]
😎 Lookin' good!

**Pull request merged**
