### PR TITLE
i18n(it): translate `core-concepts`, `sharing-state`

### PR DESCRIPTION
**Pull request by itsmatteomanf**
#### What kind of changes does this PR include?

- Translated content

#### Description

Translates [sharing-state.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/core-concepts/sharing-state.mdx).

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
I believe some Git issue happened here? I can see the PR only contains the English version with the links fixed😅

I am marking as a draft for now!

**Comment by itsmatteomanf** [comment]
This is very interesting... I did copy the English and then changed it over, but didn't commit until it was done.

I'll check 🙈

**Comment by sarah11918** [comment]
Hey @itsmatteomanf ! I'm closing the wonky PR  :sweat_smile: as there is literally no translation at all here, so I don't think having this draft sit open is helping anyone!  :smile: 

This doesn't affect your local branch, but your branch will keep getting more and more outdated, so while you are welcome to reopen this one when you figure out where your translations went, it might be a good idea to just start a new PR fresh in this case!

**Comment by itsmatteomanf** [comment]
Yeah... I left it open to try and check why the translation failed, as I'm 100% sure I did it.

But it's been a busy month and I didn't have the time :(

**Pull request closed without merging**
