### PR TITLE
Fix mismatched function names in Last Modified Time recipe

### PR DESCRIPTION
**Pull request by evadecker**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

The recipe for [Add Last Modified Time](https://docs.astro.build/en/recipes/modified-time/) sets the Astro config to import a function called `remarkModifiedTime`:

```mjs
import { remarkModifiedTime } from './remark-modified-time.mjs';

export default defineConfig({
  markdown: {
    remarkPlugins: [remarkModifiedTime],
  },
});
```

But the plugin exports a function named `modifiedTime`:

```mjs
export function modifiedTime() {
   return function (tree, file) {
     const filepath = file.history[0];
     const result = statSync(filepath);
     file.data.astro.frontmatter.lastModified = result.mtime.toISOString();
   };
}
```

When running the recipe as-is, this creates a vague console error:

image

Renaming the function from `modifiedTime` to `remarkModifiedTime` fixes the error.

### CODE REVIEW

**Comment by evadecker** [comment]
CC @carsakiller, who made this recipe (thank you so much, I'm using it on my site as of today!)

**Comment by carsakiller** [comment]
Ah! Nice catch! I was adapting what I had for the article and ended up mixing the two up a bit 🤦‍♂️. Glad you found it helpful!

**Review by carsakiller — APPROVED** [review]
Looks good!

**Comment by evadecker** [comment]
> Ah! Nice catch! I was adapting what I had for the article and ended up mixing the two up a bit 🤦‍♂️. Glad you found it helpful!

I had no idea something like this was possible, it's kinda magic! Beats the pants off of trying to remember to update a static field in the frontmatter every time I edit an article.

**Review by sarah11918 — APPROVED** [review]
Looks great, @evadecker , nice catch! Thank you so much for taking the time to contribute this fix, and welcome to Team Docs!  🥳

**Pull request merged**
