### PR TITLE
[i18nIgnore] (chore): Add back `<Tabs client:visible>` 

### LINKED ISSUE #4588: `<Tabs client:visible>` in Docs code doesn't sync tabs anymore
### 📝 Issue Description

We had to change `<Tabs client:visible>` to `<Tabs client:idle>` in the docs code {Astro v3 PR](https://github.com/withastro/docs/pull/4461).

This is simply an issue to track that we changed it and probably need to change it back sometime in the future!

### 📋 On which page(s) it occurs

all pages where the `<Tabs>` Preact component is used

### 🤔 Expected Behavior

🤷‍♂️

### 👀 Current Behavior

🙅‍♂️

### 🖥️ Browser

All of 'em

### 📄 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jacobthesheep**
#### Description (required)

Change `<Tabs client:idle>` back to `<Tabs client:visible>` in the docs code

#### Related issues & labels (optional)

- Closes #4588
- Suggested label:

### CODE REVIEW

**Review by TheOtterlord — COMMENTED** [review]
Thanks for the PR @jacobthesheep!

I checked the deployment preview, and I encounter the same bug we had before it was changed to `client:idle`. If you navigate to any page with multiple tabs, but only scroll one set into view, then proceed to click a tab, it will scroll in the new tabs, but will not correctly change them. It's a weird bug to explain, but here's a quick video to showcase it.

[Screencast from 2023-10-11 22-27-56.webm](https://github.com/withastro/docs/assets/64310361/ab95de1a-a1d0-4834-afca-f56d14d08cb5)

**Comment by jacobthesheep** [comment]
Yeah I saw that but when I tried it on my browser 

> Thanks for the PR @jacobthesheep!
> 
> I checked the deployment preview, and I encounter the same bug we had before it was changed to `client:idle`. If you navigate to any page with multiple tabs, but only scroll one set into view, then proceed to click a tab, it will scroll in the new tabs, but will not correctly change them. It's a weird bug to explain, but here's a quick video to showcase it.
> 
>  Screencast.from.2023-10-11.22-27-56.webm

Yeah I saw that but when I tried it on my browser the bug was gone.

**Comment by jacobthesheep** [comment]
Should I keep this PR open until there's a fix for it in the main astro repo?

**Comment by ElianCodes** [comment]
> Should I keep this PR open until there's a fix for it in the main astro repo?

Hey @jacobthesheep! You can close this PR, since it's actually an upstream issue in Preact!

**Pull request closed without merging**
