### PR TITLE
i18n(fr) Update `build-forms.mdx`

### PR DESCRIPTION
**Pull request by McFlyPartages**
#### Description (required)

Just for update tracker with PR #5766

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Review by huyikai — COMMENTED** [review]
Doesn't look right.

**Comment by McFlyPartages** [comment]
> Doesn't look right.

This PR doesn't bring any change, it's just there to update the translation tracker. PR #5766 should have been set to [ignore] so as not to appear as an update.

**Review by thomasbnt — APPROVED** [review]
LGTM for the tracker. Nothing was changed, only one line

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks 🙌

**Pull request merged**
