### PR TITLE
Update Starlight and Astro to latest versions

### PR DESCRIPTION
**Pull request by delucis**
#### Description (required)

- Updates Astro to v4.8.6
- Updates Starlight to v0.23.0
- Removes the previous custom rehype plugin we used to optimize MDX as this is now enabled in Starlight by default
- Removes our existing styles for `<details>` elements in favour of Starlight’s new built-in styles

#### How to review

- Kick the tyres! Test out different pages, check to see if styles look correct and if interactive components work as expected.
- Find places `<details>` are used to see if they look OK.

### CODE REVIEW

**Comment by sarah11918** [comment]
Adding a ton of screenshots of some of our details!

image

image

image

image

image

image

image

image

image

**Comment by delucis** [comment]
Amazing! We might want to add some extra CSS for the `<details>` in the purple box case? We handle the Starlight aside colours automatically, but that one is custom.

**Comment by delucis** [comment]
Added a custom colour for the purple boxes so the details looks a bit better in that context:
Purple container titled “Try it yourself - Add a blog page”. An expanded details element has a pleasantly contrasting purple border to match the container colour.

**Review by TheOtterlord — APPROVED** [review]
This looks great! I love the new details

**Comment by delucis** [comment]
Going to merge this based on @TheOtterlord’s approval to get those speedy builds out their working for people 🫡

**Pull request merged**
