### PR TITLE
[i18nignore] Removed Tigris from Astro Integrations

### LINKED ISSUE #6889: Remove Tigris from the Astro Integrations
### 📋 Explain your issue

Astro docs have the [Tigris Integration](https://docs.astro.build/en/guides/backend/tigris/#_top) which says Tigris being a  MongoDB / DynamoDB alternative NoSQLDB

Unfortunately the Project's direction is changed and Tigris is now an S3 compatible storage bucked (like Cloudflare R2) which makes no sense to be integrated with astro
Neither does it's JS SDK support the features any longer

The [Tigris Astro Integration](https://github.com/tigrisdata-archive/tigris-astro?tab=readme-ov-file) repository is also archived by the authors & it's [Get Started](https://www.tigrisdata.com/docs/quickstarts/quickstart-typescript/) page returns a 404

So please remove the integration from the Docs Site

### PR DESCRIPTION
**Pull request by SatanshuMishra**
#### Description (required)
- Removed `tigris.mdx` from `src/content/docs/en/guides/backend/`.
- Removed `tigris.svg` from `public/logos/`.
- Removed mention from `src/data/logos.ts`.
- Removed translation from `src/content/docs/es/guides/backend/tigris.mdx`.
- Removed translation from `src/content/docs/fr/guides/backend/tigris.mdx`.
- Removed translation from `src/content/docs/it/guides/backend/tigris.mdx`.
- Removed translation from `src/content/docs/zh-cn/guides/backend/tigris.mdx`.

These changes were made to remove tigris from Astro Integrations since the project no longer aligned or makes sense to be integrated into Astro. Furthermore, support for the [Tigris Astro Integration](https://github.com/tigrisdata-archive/tigris-astro?tab=readme-ov-file) has been discontinued by it's authors.

#### Related issues & labels (optional)

- Closes #6889.
- Suggested label: Improve Documentation

Special thanks to @RayyanNafees for bringing this issue up!

### CODE REVIEW

**Review by AitorMT — APPROVED** [review]
LGTM

**Comment by VoxelMC** [comment]
Thank you, Satanshu, for taking the time to tie up this loose end. LGTM

**Review by VoxelMC — APPROVED** [review]
Thank you, Satanshu, for taking the time to tie up this loose end. LGTM

**Review by dreyfus92 — APPROVED** [review]
Thank you for handling this @SatanshuMishra, LGTM 😁

**Review by sasoria — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks for the good work 🙌

**Pull request merged**
