### PR TITLE
i18n(ja): Update flightcontrol.mdx

### PR DESCRIPTION
**Pull request by morinokami**
#### Description (required)

- Update flightcontrol.mdx.
  - [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/flightcontrol.mdx?since=2023-01-16T08:47:42.000Z)
    - https://github.com/withastro/docs/pull/2912
    - https://github.com/withastro/docs/pull/5845

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by shuuji3 — APPROVED** [review]
LGTM! 🚀

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks!

**Comment by liruifengv** [comment]
!coauthor

**Review by yanthomasdev — APPROVED** [review]
LGTM! Good job y'all 🙌

**Pull request merged**
