### PR TITLE
i18n(de-DE): Translate `concepts/islands.md`

### PR DESCRIPTION
**Pull request by tobiasschmidt89**
Create and localise /de/concepts/islands.md.

#### What kind of changes does this PR include?

- Translated content

#### Description

- Create and localise /de/concepts/islands.md.
- Checked with pnpm dev

### CODE REVIEW

**Review by hippotastic — COMMENTED** [review]
Really nice translation, thanks a lot! I had some minor comments again, and we should be ready to go after addressing these. :)

**Comment by hippotastic** [comment]
Oh, I almost forgot: Could you please also edit the file `src/i18n/de/nav.ts` and add the translation for your new page title there? This will make the page title also show up correctly in the left navigation bar. It should be as simple as adding `'concepts/islands': 'Astro-Inseln',` to the `// Core Concepts` section.

**Comment by tobiasschmidt89** [comment]
Done, de/nav.ts updated and review feedback implemented.

**Review by hippotastic — APPROVED** [review]
LGTM!

**Pull request merged**
