### PR TITLE
Proposed new Astro v X to include jsx chart

### PR DESCRIPTION
**Pull request by sarah11918**
This brings back the Astro syntax VS JSX chart, and I think makes sense to include it in "Astro vs X" along with comparing to other site building tools.

Also changes header levels to make the right sidebar cleaner and easier to navigate, I think. Open to feedback!

### CODE REVIEW

**Comment by sarah11918** [comment]
While Netlify is down, visual of proposed changes: 

Screenshot 2022-03-09 09 57 37
Screenshot 2022-03-09 09 57 51

**Review by delucis — CHANGES_REQUESTED** [review]
Ahh, great to have this back & definitely agree that sidebar is a big improvement 😅 

Looks like VS Code is missing a link in the IDE Support row of the table. There was probably a line like 

```md
[code-ext]: https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode
```

somewhere in the original that got lost. (Basing that off it still existing on the Astro components page in [Spanish](https://github.com/withastro/docs/blob/1eaf8a2f064a9ce9ec5c9d6e1eef7080e7634eb4/src/pages/es/core-concepts/astro-components.md) and [German](https://github.com/withastro/docs/blob/582f257ce694c4025fe1b9c20085ece912503ed7/src/pages/de/core-concepts/astro-components.md).)

**Comment by sarah11918** [comment]
> There was probably a line like
> 
> ```lisp
> [code-ext]: https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode
> ```
> 
> somewhere in the original that got lost. 

Indeed! Sneaky little thing at the bottom of the file.... :)

**Comment by delucis** [comment]
By the way, that `[code-ext]` block doesn’t actually _have_ to be at the bottom of the file. You could also put it just below the table so it’s less likely to get lost next time the table gets moved.

I do like using this syntax for links because it keeps the text containing the link more readable (no hugely long URLs in the middle of sentences), but it does introduce some maintenance friction.

**Review by delucis — APPROVED** [review]

**Comment by FredKSchott** [comment]
I like it! My only suggestion is to move it down to the bottom of the page, since it's not really like the others. 

Reason: When its at the top of the page, it kind of sets the context for the reader that the "X" we're comparing Astro to are different syntaxes (JSX, Vue, etc) and then instantly changes it when you get to the second section ("actually, it's site builders). By moving it to the bottom, it's a bit less disruptive but still visible in search and the Table of Contents.

If this looks good to you, feel free to hit that merge button!

**Pull request merged**
