### PR TITLE
i18n(ko-KR): update `markdoc.mdx`

### PR DESCRIPTION
**Pull request by jsparkdev**
#### Description (required)

- update `markdoc.mdx`
- #7743
- #7744

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by huyikai** [comment]
> Heads up we got a [few more updates on this page](https://github.com/withastro/docs/commit/8a31bf3bc5f15b95a98b59ae3db54fe67491608b) would you be up to adding those changes here as well?

Sure, I will add these updates.

**Comment by jsparkdev** [comment]
> > Heads up we got a [few more updates on this page](https://github.com/withastro/docs/commit/8a31bf3bc5f15b95a98b59ae3db54fe67491608b) would you be up to adding those changes here as well?
> 
> Sure, I will add these updates.

Are you really going to update this PR?

**Comment by huyikai** [comment]
> > > Heads up we got a [few more updates on this page](https://github.com/withastro/docs/commit/8a31bf3bc5f15b95a98b59ae3db54fe67491608b) would you be up to adding those changes here as well?
> > 
> > 
> > Sure, I will add these updates.
> 
> @huyikai Are you really going to update this PR?

oh I think I made a mistake. I should have replied to the wrong message. I'm very sorry。Because zh-cn also has updates on this content. I think I'm confused.

**Comment by jsparkdev** [comment]
I thought it was a mistake so I asked a question :)

have a good day!

**Review by yanthomasdev — APPROVED** [review]
LGTM, good work!

**Pull request merged**
