### PR TITLE
i18n(fr): Translated `core-concepts/astro-syntax.mdx`

### PR DESCRIPTION
**Pull request by achtaitaipai**
#### What kind of changes does this PR include?

- Translated content

#### Description

Translated core-concepts/astro-syntax.mdx to french

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Awesome job @achtaitaipai, LGTM ✅

**Comment by Yan-Thomas** [comment]
Thanks @achtaitaipai, as you can see in the "files changed" tab, translating this page broke another link in the directives-reference page, which has a one-line change necessary to be updated, would you be up to translating it both fixing the link and adding the line missing? Here's the change history: https://github.com/withastro/docs/commits/main/src/content/docs/en/reference/directives-reference.mdx?since=2023-06-20T16:37:02.000Z

**Comment by achtaitaipai** [comment]
@Yan-Thomas Thank you ! I think it's ok now

**Review by Yan-Thomas — COMMENTED** [review]
LGTM! Thanks for the great work 🙌

**Pull request merged**
