### PR TITLE
Update add-content-collections.mdx

### LINKED ISSUE #6271: ⚠️ Issue while following tutorial page "Tutorial - Extend with Content Collections"
URL: https://docs.astro.build/en/tutorials/add-content-collections/

When creating file `src/content/config.ts` and adding it's contents from the tutorial a typescript throws an error `Cannot find module 'astro:content' or its corresponding type declarations.ts(2307)`

After a quick google search, I stumbled upon this issue https://github.com/withastro/astro/issues/5711 and running `npx astro sync` command has resolved this problem (by creating `src/env.d.ts` file)

I'll provide a PR shortly in order to update the tutorial page

### PR DESCRIPTION
**Pull request by eko24ive**
#### Description 

Updated tutorial with information about potential TS-related issue in the context of tutorial and provided solution on how to resolve it. Please refer to #6271 for more information 

#### Related issues & labels (optional)

- Closes #6271 
- Suggested label: tutorial

### CODE REVIEW

**Comment by eko24ive** [comment]
Self Self-reviewed my changes on the deployed preview on Netlify - looks good to me, but I can't shake the feeling that formatting may be improved somehow. I would appreciate if someone could point me in the right direction

**Comment by VoxelMC** [comment]
Hello! Thank you for bringing this up!

I am not sure if a numbered step is the right way to go for this addition.
@sarah11918, would such an addition constitute a `:::tip`?

**Review by sarah11918 — APPROVED** [review]
Thank you for your patience, @eko24ive ! We really appreciate you taking the time to add this helpful step to the tutorial, and are pleased to welcome you to Team Docs!  :partying_face:

**Comment by eko24ive** [comment]
Glad to be of help! Apologies for messing step number sequence - it totally slipped my mind 😅

**Pull request merged**
