### PR TITLE
Make corrections to `supabase.mdx`

### PR DESCRIPTION
**Pull request by VoxelMC**
#### Description (required)

This PR updates the `supabase.mdx` guide with some changes, as I currently use it to set up a project. These changes will be added to as I complete the setup.

Status: Complete!

Changes: 
- Missing import in `dashboard.astro`
- Move diff `add` to proper line in OAuth section

#### Related issues & labels (optional)

- Suggested label: improvement

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Thank you for handling this @VoxelMC, LGTM ✅

**Comment by sarah11918** [comment]
Converting this to draft since it says "STATUS: NOT DONE". Please undraft when it's ready for review!

**Comment by VoxelMC** [comment]
> Converting this to draft since it says "STATUS: NOT DONE". Please undraft when it's ready for review!

Done now! Just had to double check, but my Supabase app is working `Supa` well!

**Review by sarah11918 — APPROVED** [review]
🫡

**Pull request merged**
