### PR TITLE
i18n(ja): Update `ja/guides/styling.mdx`

### PR DESCRIPTION
**Pull request by totto2727**
#### Description (required)

- Update ja/guides/styling.mdx
  - The information on passing classes from parent to child was out of date, and the samples and explanations did not work with the current default settings.
  - It has been corrected to conform to the latest English documentation.

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Review by SnowDingo — APPROVED** [review]
@totto2727 さん、翻訳ありがとうございます！
翻訳された箇所を英語版と比べながら僕がレビューしてみましたが、自然で特に問題はありませんでした。
承認しておきます。

**Comment by totto2727** [comment]
ありがとうございます！

追記になるのですが、他の言語（ドイツ語など）も同様の問題がありそうです。
日本語と簡単な英語以外は読み書きできないため、私では対応できませんが…
こちらはIssueを立てるべきでしょうか？

Thank you very much!

I would like to add that other languages (e.g. German) seem to have the same problem.
As I cannot read or write anything other than Japanese and simple English, I cannot handle this...
Should I make an Issue here?

https://docs.astro.build/de/guides/styling/#%C3%BCbergabe-einer-class-an-eine-untergeordnete-komponente

**Comment by yanthomasdev** [comment]
> I would like to add that other languages (e.g. German) seem to have the same problem.
As I cannot read or write anything other than Japanese and simple English, I cannot handle this...
Should I make an Issue here?

Hey @totto2727, are you referring about those files being outdated? That doesn't require an issue, we have a proper [i18n tracking dashboard](https://i18n.docs.astro.build) that handles this for our contributors to know what pages need to be updated and what needs updating. If that's not it and there are any content/structure/etc issues, feel free to create an issue!

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
