### PR TITLE
Reorg the sidebar with guidance

### PR DESCRIPTION
**Pull request by FredKSchott**
- Reorganize the sidebar based on feedback from @sarah11918 
- Give guidance on new pages to add, convert, merge together, etc.

### CODE REVIEW

**Comment by sarah11918** [comment]
There's nothing here I don't like.  :)  Proposed, commented out changes look good, too.

The only thing I'm still not 100% sold on is that "API" is the *best* label to be opposite Learn.

Gatsby uses "Reference" for all that same kind of info that we have in "API" main section. My gut is that's more descriptive and accurate for us.

Nextjs and React use API, but then, the ONLY thing in their API section is actually API stuff, not other guides/config etc.

11ty has all sections in one big sidebar including separately Configuration, Plugins, API Services (*of interest for future, they also have a Glossary!)

**Comment by FredKSchott** [comment]
@sarah11918 +1 from me! I meant to change that here based oh your earlier feedback and forgot :)

**Comment by sarah11918** [comment]
So, I didn't need to round up the troops to get others to weigh in then?  ;)

**Comment by zadeviggers** [comment]
I agree with Sarah that reference is a much more descriptive label for that section.

I do feel like it's weird having some sidebar-headings being two words and some only being one word.
I also feel like the "basics" section name isn't the best name for that section (although I can't think of anything better, so feel free to ignore this opinion).

**Comment by sarah11918** [comment]
So, I think we like this!  3 things (though only the 3rd is blocking *before* we can actually switch up the sidebar on the live site. The other 2 can always be changed later):

1. Learn / Reference instead of Learn/API  (I'm not sure if I can JUST change `type: api` here to reference, or whether it's somewhere in the sidebar component itself this should (also?) be changed, so that's on @FredKSchott to take care of.

2. We've had a preference indicated for changing BASICS to ESSENTIALS. Anyone have strong feelings on this? (will also ping @delucis ) I have no strong preference for either header.

3. The "Why Astro?" get-to-the-heart-of-Astro page doesn't exist yet. Sarah has notes; Fred has thoughts. This one's on us.

**Comment by delucis** [comment]
1. Just opened #236, which ought to make this question easier to answer!

2. I think either Essentials or Fundamentals could both be good.

3. 🧑‍🚀 ⏩ ❤️ — ✅

**Comment by FredKSchott** [comment]
I agree with Sarah about keeping header words simple for accessibility & i18n. I do personally like Fundamentals though, but I think a11y and i18n win out over personal preference :) 

Cleaning up and merging! The comments in the config file are left as TODOs to tackle over the next few weeks

**Pull request merged**
