### PR TITLE
i18n(zh-cn): Update `reference/directives-reference.mdx` and `reference/integrations-reference.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

Update `reference/directives-reference.mdx` and `reference/integrations-reference.mdx`

### CODE REVIEW

**Comment by 100gle** [comment]
cc @liruifengv

**Comment by liruifengv** [comment]
Miss commits:
- https://github.com/withastro/docs/pull/3829
- https://github.com/withastro/docs/pull/3297

**Comment by 100gle** [comment]
> Miss commits:
> 
> * [chore(en): describe more accepted `class:list` value kinds #3829Chore(en)：描述更多被接受的 `class:list` 值类型 #3829](https://github.com/withastro/docs/pull/3829)
> * [fix: removes wrong inline style info #3297](https://github.com/withastro/docs/pull/3297)

#3892 这个 PR 好像有点问题……其他选项对应的是 Type，而新增的给出的是 `false` 或 `null` 值

**Comment by 100gle** [comment]
> Miss commits:
> 
> * [chore(en): describe more accepted `class:list` value kinds #3829](https://github.com/withastro/docs/pull/3829)
> * [fix: removes wrong inline style info #3297](https://github.com/withastro/docs/pull/3297)

DONE

**Comment by liruifengv** [comment]
- https://github.com/withastro/docs/commit/de631626235810f2d92884557d33c0b8ae427b04
- https://github.com/withastro/docs/commit/e52561db526dccf3e08ae5fce9b685ce2168b923#diff-4aa2d04c24b155473112c2cc7104df7627bfa0a40dc156564828ca6c2dd48a65

**Comment by 100gle** [comment]
> * [de63162](https://github.com/withastro/docs/commit/de631626235810f2d92884557d33c0b8ae427b04)
> * [e52561d#diff-4aa2d04c24b155473112c2cc7104df7627bfa0a40dc156564828ca6c2dd48a65](https://github.com/withastro/docs/commit/e52561db526dccf3e08ae5fce9b685ce2168b923#diff-4aa2d04c24b155473112c2cc7104df7627bfa0a40dc156564828ca6c2dd48a65)

DONE

**Review by liruifengv — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Pull request merged**
