### PR TITLE
add missing word in image integration-guide

### PR DESCRIPTION
**Pull request by mundry**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

This change adds a missing word in the integration-guide for the image integration.

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @mundry! This is super helpful, and well-spotted, thank you!

This page is takes a little more effort to edit, though, because the source content is hosted in a different repository. The content in the docs gets re-written over every day with the content from there, so we don't change this file directly here. 

If you open and look at the raw contents of this file again, there's a note at the very top with a link to the file on GitHub in the `withastro/astro` repo where the source of the content exists. 

Would you be wililng to make this exact same PR, but to that file in that repository? If you do, then please mention me there in the comment! If you would rather I just make the fix, I can do that too. Let me know if you'd like to make that PR, or if you have any questions!

**Comment by mundry** [comment]
Hey Sarah,
yeah, totally!
Sorry for the mix up.

**Comment by mundry** [comment]
This PR has been moved to the [withastro/astro](https://github.com/withastro/astro) repo at https://github.com/withastro/astro/pull/4303.

**Comment by sarah11918** [comment]
@mundry Perfect, thanks so much! 

I'm going to keep a note of THIS PR, so that when the PR comes in from our automated action, then I'll add your name to it in the commit comments, so we can still give you a shout out in our DocsCongratsBot in the Discord docs channel!  (Heads up @delucis that this is the plan, so let's not just automatically merge tomorrow's `ci` PR!)

Sorry this was a weird introduction to the Docs... you just *happened* to pick one of our funky pages to get started. When you make more contributions (you will, right??) then please do take a quick peek at the top of the page you're editing just in case you hit one of these pages again! If you're not in the right spot, it should tell you where to go.)  😄

**Pull request closed without merging**
