### PR TITLE
Persist sidebar state

### LINKED ISSUE #5771: Left Sidebar Resets to Top After Page Refresh
### 📝 Issue Description

Every time the page is refreshed, the scroll position in the left sidebar is lost and automatically resets to the top. This behavior occurs consistently upon every page refresh.

### 📋 On which page(s) it occurs

Occurs on all pages that have left sidebar

### 🤔 Expected Behavior

Implementing a feature to preserve the scroll position in the browser storage could resolve this issue.

[Expected Behavior](https://github.com/withastro/docs/assets/45861586/468fdf88-6ae5-457f-8b88-d655810025d1)

### 👀 Current Behavior

[Current Behavior](https://github.com/withastro/docs/assets/45861586/12e1e45e-1e58-44c7-a433-aa1cb9659fc2)

### 🖥️ Browser

Edge

### 📄 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by TheOtterlord**
#### Description (required)

Persist the sidebar state across a session.

#### Related issues & labels (optional)

- Closes #5771

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
It works for me! :tada:

**Comment by VoxelMC** [comment]
This is a 💌 - so perfect!

**Comment by SatanshuMishra** [comment]
This is amazing! Thank you for making this change :)!

**Comment by lschierer** [comment]
Oh I'd like this in starlight.

**Comment by sarah11918** [comment]
We're discussing whether to actually make this change in Starlight instead!

**Pull request closed without merging**
