### PR TITLE
update a code snippet in `guides/server-side-rendering.mdx`

### PR DESCRIPTION
**Pull request by ArmandPhilippot**
#### Description (required)

Following the discussion in #9673, I updated two sections regarding `Response` in `guides/server-side-rendering.mdx`. This is mostly code snippet updates to show the user that he can use `prerender = false` and that he can also return a `Response` using `Astro.redirect`.

#### Related issues & labels (optional)

- Suggested label: code snippet update

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
🫡

**Comment by sarah11918** [comment]
10 minutes ago... 2 commits behind.... Docs comes at you fast!

**Comment by sarah11918** [comment]
Actually, @ArmandPhilippot did you want to update the file name in line 233 as well?

**Comment by ArmandPhilippot** [comment]
Oh sorry, I think I wanted to go too fast. 😓  Yes I should! And maybe I should update the sentence too... I don't know why I only thought of that block.

**Comment by sarah11918** [comment]
Yup, make it match the changes in the other and we're good! Less work for the translators for later! 🎉

**Pull request merged**
