### PR TITLE
i18n(zh-cn): Update `integrations-guide.mdx` and `troubleshooting.mdx`

### PR DESCRIPTION
**Pull request by XindiShang**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- Updated the translations of `zh-cn/guides/integrations-guide.mdx` and the relevant part in `troubleshooting.mdx` to align with the updated content in English.

### CODE REVIEW

**Comment by liruifengv** [comment]
There are some conflicts. Please update from the `main` branch.

**Comment by XindiShang** [comment]
> There are some conflicts. Please update from the `main` branch.

Thanks for the heads-up! I have synced my fork.

**Comment by liruifengv** [comment]
Some checks failed. `/zh-cn/guides/troubleshooting/` troubleshooting page has a broken link. Can you fix it?

**Comment by liruifengv** [comment]
Thanks. 

There are a few typos that need to be fixed here.
```
了解所有不同地集成编写方式。
```
Can fix it to:
```
了解所有不同的集成编写方式。
```

And `Falsy` which I suggest is translated as `假值`：
```
Astro 会自动忽略禁用集成。
```
to:
```
Astro 会自动忽略假值的集成。
```

**Comment by liruifengv** [comment]
`Removing an Integration` has been added to the English page. You can update it.

**Comment by XindiShang** [comment]
> `Removing an Integration` has been added to the English page. You can update it.

Thanks for the careful review👏🏼. I'll double check the content before my next submit😅. Plus, for the next commit, I'll update the entire Chinese troubleshooting guide to match with the new English content (the current one only addresses the mismatch of 'integrations').

**Comment by XindiShang** [comment]
> > `Removing an Integration` has been added to the English page. You can update it.
> 
> Thanks for the careful review👏🏼. I'll double check the content before my next submit😅. Plus, for the next commit, I'll update the entire Chinese troubleshooting guide to match with the new English content (the current one only addresses the mismatch of 'integrations').

To keep this PR minimal, I'm gonna open another PR for the troubleshooting guide translation.

**Comment by Yan-Thomas** [comment]
Thanks @XindiShang, @liruifengv! Can I get a confirmation this is good to be merged now?

**Review by liruifengv — APPROVED** [review]
I think it is can be merged. @XindiShang And you?

**Comment by XindiShang** [comment]
> I think it is can be merged. @XindiShang And you?

@liruifengv Sure😄

**Pull request merged**
