### PR TITLE
i18n(it): Create `guides/astro-db.mdx` & `guides/integrations-guide/db.mdx`, modify `guides/integrations-guide.mdx` & `recipes/studio.mdx`

### PR DESCRIPTION
**Pull request by casungo**
#### Description (required)

Created `guides/astro-db.mdx`

### CODE REVIEW

**Comment by casungo** [comment]
The CI that checks the links fails because the links are from other PRs.
In this specific PR, 4 links fail because:
- The first 3 links are in PR #7324
- The last link is in PR #7323

**Comment by yanthomasdev** [comment]
Thanks @casungo, to avoid the link issues, could you bring the translation from https://github.com/withastro/docs/pull/7324 to here, so we make it only one PR? Also, these pages had a few changes recently, could you add them? After all this I believe this PR should be good to merge, sorry for the wait!

**Comment by casungo** [comment]
fixed the links + updated some pages in a minor way
no problem for the wait ;) @yanthomasdev

**Review by yanthomasdev — APPROVED** [review]
LGTM! Good work 🙌

**Pull request merged**
