### PR TITLE
fix external WP blog post link

### PR DESCRIPTION
**Pull request by lukethacoder**
#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

Fixes the `Astro and WordPress as an API` [Community Resources](https://docs.astro.build/en/guides/cms/wordpress/#community-resources) URL. Original post author looks to have updated the slug of the post.

image

please add the `hacktoberfest-accepted` tag.

### CODE REVIEW

**Review by dreyfus92 — CHANGES_REQUESTED** [review]
Hey @lukethacoder, thank you for handling this issue. Changes to the docs only should be made to the EN version of the docs cause we have a tracker for other locales that notifies translators to handle the changes of the current state of the docs. Would you mind removing the changes from the other locales and just leave the change for the EN version?

**Comment by lukethacoder** [comment]
@dreyfus92 no problem. just rolled back the changes. thanks

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks for catching this @lukethacoder 🙌

**Comment by DBozhinovski** [comment]
Apologies from the author, he was in the process of migrating the blog to a new theme and forgot to do his forwards properly :sweat_smile:

**Pull request merged**
