### PR TITLE
feat:  use Starlight's Tabs

### PR DESCRIPTION
**Pull request by liruifengv**
#### Description (required)

- Use Starlight's Tabs component

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/7531

### CODE REVIEW

**Comment by liruifengv** [comment]
Wait for the next Starlight version ⭐

**Comment by at-the-vr** [comment]
Hey liruifengv is your PR conflicting with #8322?

**Comment by delucis** [comment]
Ah, sorry, I’d forgotten about this PR when making #8322. But I think it can still be useful.

1. We can merge #8322 
2. Then we can use this PR to migrate to Starlight’s Tabs, which is super helpful!

**Comment by liruifengv** [comment]
> Ah, sorry, I’d forgotten about this PR when making #8322. But I think it can still be useful.
> 
> 
> 
> 1. We can merge #8322 
> 
> 2. Then we can use this PR to migrate to Starlight’s Tabs, which is super helpful!

No problem. I will update this PR after merge #8322

**Comment by delucis** [comment]
#8322 is merged — it’s all yours @liruifengv! 🚀

**Review by TheOtterlord — APPROVED** [review]
LGTM! Tested on a handful of pages, including the shared state recipe.

**Review by delucis — APPROVED** [review]
Looks fantastic and the sync feature is working well even on more complex content like the [“Sharing state” recipe](https://docs-git-fork-liruifengv-upgrade-startlight-022-astrodotbuild.vercel.app/en/recipes/sharing-state-islands/).

Thank you @liruifengv! 💖

**Comment by liruifengv** [comment]
Thank y'all!

**Comment by liruifengv** [comment]
!coauthor

**Comment by liruifengv** [comment]
Oh.. I got the coauthors, but I forget add them when merge. Lol

**Pull request merged**
