### PR TITLE
i18n(ko-KR): update `content-collections.mdx`

### PR DESCRIPTION
**Pull request by jsparkdev**
#### Description (required)

- update `content-collections.mdx`
- #9240
- #10143
- #10209
- #10213

#### Related issues & labels (optional)

- Closes #
- Suggested label:

### CODE REVIEW

**Comment by ArmandPhilippot** [comment]
Just so you don't forget when you've fixed the link issues (good luck... 😅), there's a new change (and probably a second one): #10209 and #10213

**Comment by jsparkdev** [comment]
@ArmandPhilippot Thanks!

**Comment by jsparkdev** [comment]
Once #10201, #10153, #10157, #10158, #10216, #10230 are merged, I expect to be able to merge this PR successfully.

**Review by yanthomasdev — APPROVED** [review]
LGTM! I'll merge the umbrella PR once I approve all of the individual PRs.

**Pull request closed without merging**
