### PR TITLE
fix: add spacing to 'added in' texts

### PR DESCRIPTION
**Pull request by kevinzunigacuellar**
#### Description

Add spacing to `<Since />` elements

| Before                                                                                                                     | After                                                                                                                      |
|----------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|
| image | image |

### CODE REVIEW

**Comment by ElianCodes** [comment]
Wouldn't it make more sense to add padding to the `<Since />` component instead of wrapping all of them in a `<p />?

**Comment by kevinzunigacuellar** [comment]
> Wouldn't it make more sense to add padding to the `<Since />` component instead of wrapping all of them in a `<p />`?

It would but there are some instances of Since that are inlined 😅

**Review by delucis — APPROVED** [review]
LGTM! Thanks for tackling this @kevinzunigacuellar 💜

**Comment by sarah11918** [comment]
Thanks, Kevin! I updated Astro Docs Docs to show this usage of the component in a standalone line!

**Pull request merged**
