### PR TITLE
i18n(en): Fix typo in `react-integration`

### PR DESCRIPTION
**Pull request by DawnMD**
#### What kind of changes does this PR include?
- Minor content fixes (broken links, typos, etc.)

#### Description
- What does this PR change? Give us a brief description.
  - This fixes a type in the page [react-integration](https://docs.astro.build/en/guides/integrations-guide/react/)
- Did you change something visual? A before/after screenshot can be helpful.
  - N/A

- Are these docs for an upcoming Astro release?
  - No

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
Nice catch @DawnMD, LGTM ✅

**Comment by DawnMD** [comment]
Thanks man 🙌🏼 @dreyfus92

**Comment by sarah11918** [comment]
Hey @DawnMD , good catch indeed!  🙌 

I'm going to have to send you to a different repo to fix this, though. This particular file is actually kept in the main `/withastro/astro/` repo, and the file is located here:  https://github.com/withastro/astro/blob/main/packages/integrations/react/README.md

Would you be willing to make this same PR, but over there changing that file? These integration package READMEs are pulled into our docs site automatically from the source code kept with the package itself.

Thanks!

**Comment by DawnMD** [comment]
Hey @sarah11918 

I was thinking of doing that but wasn't sure if that was the right place 😅. I will open the PR for changing the file you've mentioned with the link. Do I need to add changeset (`pnpm exec changeset`) for the typo change?

**Comment by ElianCodes** [comment]
Hey @DawnMD, looks like the PR was merged on the Astro core repo, so I'm going to close this one, our CI will automatically update this page!

**Comment by DawnMD** [comment]
Sure @ElianCodes thank you 🙏🏻

**Pull request closed without merging**
