### PR TITLE
delete old guides [i18nIgnore]

### PR DESCRIPTION
**Pull request by sarah11918**
The following ALLCAPS Markdown guides should have replacements now in a folder and more descriptive file names.

PLEASE CHECK that nowhere refers to any of these old ones instead of the new ones! I think I've been pretty thorough, but I am looking for people to verify!

### CODE REVIEW

**Comment by delucis** [comment]
Not strictly speaking related but do you also want to delete `old-translations/` and `CHANGELOG.md` as part of this? We're not going to use those I don't think so might as well delete at this point.

**Comment by TheOtterlord** [comment]
Only had time for a quick search, but I found a few places:

- https://github.com/withastro/docs/discussions/2894
- https://github.com/withastro/docs/blob/9d026521bc4ef73e817d72464df3ece3b68715cd/README.md?plain=1#L62C26
- https://github.com/withastro/docs/blob/9d026521bc4ef73e817d72464df3ece3b68715cd/scripts/lib/translation-status/template.html#L229
- https://github.com/withastro/docs/blob/9d026521bc4ef73e817d72464df3ece3b68715cd/src/components/FallbackNotice.astro#L8
- Translations of `contribute.mdx`

**Comment by sarah11918** [comment]
Thanks @TheOtterlord Just did a bunch more!

**Comment by sarah11918** [comment]
(And, I also updated Chris' message re: recipe ideas!)  :joy:

**Review by TheOtterlord — APPROVED** [review]

**Pull request merged**
