### PR TITLE
i18n(hi): add Astro v5 banner in Hindi

### PR DESCRIPTION
**Pull request by apatel369**
**Description (required)**

Add Astro v5 banner to Hindi version of `getting-started.mdx`

Related issues
[9387](https://github.com/withastro/docs/pull/9387)

**NOTE WHEN MERGING**
**After merging, update the beta branch, adding a commit to revert this pr**

### CODE REVIEW

**Comment by sarah11918** [comment]
Thank you, and what a cool first contribution to the docs to make, @apatel369 !

One of our maintainers will review this shortly, but in fact, this banner appears on a second page in docs, AND there is another note with the link to the upgrade guide too. Would you mind adding these to this PR?

How our Translators normally work is they notice an English PR that has merged, and then they replicate it in their language. You linked the correct PR where this change was added, but if you check that PR you'll see there are more changes made in that PR. You can see all the changes made in the "Files changed" view of the PR: https://github.com/withastro/docs/pull/9387/files

It would be great if you could add all those changes together at once! 🙌

**Comment by apatel369** [comment]
@sarah11918 Thanks for reviewing my changes. 
If I understand correctly you are referring to changes for [content-collections.mdx](https://github.com/withastro/docs/pull/9387/files#diff-a6fd5674a02c61d6110497ce6010118e4e9c6cfb50e3b5a9168faee52f77348d) and [upgrade-astro.mdx](https://github.com/withastro/docs/pull/9387/files#diff-5963da07070d6cac124699479c46c876d6cc7b9e971ed4c8981a13d506d31c88). 
But those files don't exist for hindi, that's those changes are absent in my PR. 

Is there anything else I need to do here?

Screenshot 2024-09-17 at 10 24 03 PM

**Comment by sarah11918** [comment]
@apatel369 D'oh, my mistake! Of course you're right and that makes perfect sense! 😄 

This is the only change applicable for your language, so it's perfect like this. No changes needed, and ready for a review when we can get to it! Thank you!

**Review by at-the-vr — APPROVED** [review]
This PR could not have been sooner 🔥 Welcome to Team Docs Arpan 🥳

**Comment by apatel369** [comment]
> This PR could not have been sooner 🔥 Welcome to Team Docs Arpan 🥳

Thanks! The Astro Team has been incredibly welcoming. I loved how quickly Sarah and Atharva reviewed my PR.

**Pull request merged**
