### PR TITLE
chore: bump actions/checkout in GitHub deploy guide 

### PR DESCRIPTION
**Pull request by swift502**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Primarily, update the script so it reflects that users should now use actions/checkout@v3 instead of v2, which was recently merged in https://github.com/withastro/action/pull/17
- Script is now a 1:1 match with the one found in [withastro/action](https://github.com/withastro/action) repository

Thanks!

### CODE REVIEW

**Comment by lino-levan** [comment]
LGTM! Not sure if the wording changes were necessary but it does improve clarity.

**Comment by swift502** [comment]
> Not sure if the wording changes were necessary

@lino-levan  I just matched the script from github, so now it should be 1:1. It seemed like the right thing to do.

Thanks for the Deno guide update, I didn't know this concerned other guides as well.

**Comment by lino-levan** [comment]
I'm not super sure why but a lot of the guides seem to be using `actions/checkout@v2`. It seems to work the same with v3 so I'm not entirely sure why this is the case (other than no one has bothered to update it yet).

**Review by delucis — APPROVED** [review]
Thanks @swift502 🙌

**Pull request merged**
