### PR TITLE
i18n(ru): Update `buttercms.mdx` translation

### PR DESCRIPTION
**Pull request by mearashadowfax**
#### Description

This PR updates the Russian translation of the `buttercms.mdx` page, addressing outdated content identified by the Translation Tracker.

Related:
- #7410

### CODE REVIEW

**Review by AitorMT — APPROVED** [review]
LGTM!

**Review by liruifengv — APPROVED** [review]
LGTM!

**Comment by liruifengv** [comment]
!coauthor

**Review by dreyfus92 — APPROVED** [review]
Thank you peeps! LGTM ✅

**Pull request merged**
