### PR TITLE
i18n(zh-cn): Update nav.ts

### PR DESCRIPTION
**Pull request by liruifengv**
#### Description (required)

Update nav.ts

#### Related issues & labels (optional)

- https://docs.astro.build/zh-cn/reference/dev-overlay-plugin-reference/

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @liruifengv ! Just checking if this PR should still be marked as a draft?

If it's ready for editing, then please change the status so that it is ready for review! We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this is ready, we would like to be able to review it.  Thanks!

**Comment by liruifengv** [comment]
> Hi @liruifengv ! Just checking if this PR should still be marked as a draft?
> 
> If it's ready for editing, then please change the status so that it is ready for review! We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this is ready, we would like to be able to review it. Thanks!

Yeah. It's ready for review. I think `Dev overlay` can keep the English.

**Review by sarah11918 — APPROVED** [review]
LGTM! Preview looks great, so let's get this in there!

Happy for a PR if someone wants to make a change, but I think it's helpful to have the new structure represented sooner rather than later! :raised_hands:

**Review by Genteure — COMMENTED** [review]
Retrospective review: LGTM 👍

**Pull request merged**
