### PR TITLE
Update GitHub Pages deploy guide

### LINKED ISSUE #108: 📘 DOC: Improve docs around deployment script to gh-pages
Hello all! I think Astro is pretty great at what it does and I even contribute a small amount each month to help support your work. 

I came across the docs for deploying to github pages and found the deploy script would overwrite my `main` branch with the output of the `dist` folder. I'd like to be able to maintain my `main` branch as it is but to instead deploy to a separate branch named `gh-pages`. I ran into issues with the deploy script for this scenario and instead went with using an npm package to help: `gh-pages`. All I had to do was run `yarn build && touch ./dist/.nojekyll && gh-pages -d dist -t true` and it worked like a charm. In my settings for the repo, I just point to `gh-pages` as the branch I want deployed.

I thought this would be a good idea to add to the docs but maybe it's too specialized to npm land, hence the bash script you have as the first/primary way to deploy. Anyhow, I'd thought I'd at least bring up the idea and see what you all thought in case there was agreement there. Thanks for all the work on this project, I am excited to see where things go.

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [X] New or updated content
- [ ] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

- Closes #108
- Updates the GitHub Pages deploy guide — hopefully making it simpler!

### CODE REVIEW

**Comment by sarah11918** [comment]
This looks amazing, @delucis , thank you! (I mean, it doesn't *start* with a warning anymore 😅  , so already much friendlier forjust  that reason alone!)

And, we already have someone on the job testing out how well someone who doesn't already know this stuff can follow the instructions.

GO TEAM! 🎉

**Comment by delucis** [comment]
Trying and failing to follow my own instructions so revision of this guide in the works… 😅

**Comment by delucis** [comment]
OK, made a couple of tweaks based on my experiences and I think this should now work. I’d be curious to hear from anyone else who has a chance to try to follow these instructions.

**Comment by sarah11918** [comment]
OK, WHEW.... do I have UPDATES!

So thank you both @delucis @tony-sull ... I *did* get not one, but two repositories successfully deployed! 🥳 

Yes, making a repository actually named sarah11918.github.io helped, but Chris' instructions for setting base worked for another repository too. (Didn't need to know about GH Actions at all, so omg YES, I think we have a winner!)

BUT 2 things to report, in order to know whether this should affect documentation at all:

1. With the `base:` set, when I open my repo in CodeSandbox, I get this screen when the dev server starts. (Clicking the link to the suggested base works fine, so I'm assuming that's not a problem for people in general?)
Screenshot 2022-05-17 20 51 12


2. I needed to `npm run build` my site FIRST, before my gh-pages branch showed up in the Pages tab of Settings.

Maybe this sounds ridiculous to you both, but until recently, I honestly never "built" my site... I just let Netlify do it. And, on CodeSandbox/StackBlitz etc, there's almost no point in ever building... you just run in dev mode. It's only recently I realized that if I did `npm run build` I could see messages and stuff, and make sure things DID build before letting Netlify fail and reading those logs! 😅 

So, I think that was where I was getting messed up before. I was getting a new astro starter from astro.new in CodeSandbox (and tried also in StackBlitz), commiting those starters back to a new repository in Github, then trying to follow the instructions (editing astro.config.mjs and adding the workflow file). BUT, without ever having ever built the site, it wasn't working. I don't even know what made me think of building... I just know that worked.

So, I don't even know whether that is something to document? Is that too "Sarah" to even mention? Anyway, just wanted to share that that is what  eventually worked for me, so we can decide whether it's noteworthy.

**Comment by delucis** [comment]
Thanks for trying this Sarah!

Were you _committing_ `dist`? Otherwise I'm wondering if running `npm run build` was actually unrelated/a fluke? The GitHub action builds the site for you. It's basically Netlify except much more fiddly.

So you think this ok for now and we can revisit as we get reports of it not working?

**Comment by sarah11918** [comment]
I do think this is OK to merge now!

**Comment by sarah11918** [comment]
Can we LGTM this, so I can make other edits to this page without resolving conflicts!  😅

**Pull request merged**
