### PR TITLE
feat: add new variant to `command`

### PR DESCRIPTION
**Pull request by ematipico**
#### Description (required)

This PR adds a new variant to one of the options returned to the hook `astro:config:setup`

### CODE REVIEW

**Comment by sarah11918** [comment]
@ematipico Looks like this will need updating in the section below, around lines 106-112 too?

**Comment by ematipico** [comment]
Updated!

**Comment by sarah11918** [comment]
@ematipico Thank you, but it also needs a line at 113 explaining it!  :smile:  Is it just the same text as the explanations for the others, or is it different?

**Comment by ematipico** [comment]
@sarah11918 done

**Review by yanthomasdev — APPROVED** [review]
LGTM!

**Review by sarah11918 — APPROVED** [review]
Woo! Another one ready to go for 4.15! Thank you @ematipico !

**Pull request merged**
