### PR TITLE
i18n(zh-cn): update consistent voice for tutorial

### PR DESCRIPTION
**Pull request by 100gle**
#### What kind of changes does this PR include?

- New or updated content

#### Description

update consistent voice for tutorial since #4700

### CODE REVIEW

**Comment by Genteure** [comment]
Looks good to me but if the changes made in this PR is based on the guideline in #4694, I feel like we should wait until we finalize (the initial version of) the guideline before starting to make formatting PRs, just to make sure we are not going be going back and forth and making wasted effort.
In the mean time can I have your opinion on #4694 please? It's still WIP and I'll make another push later today, but any suggestions would be greatly appreciated.

改动本身看起来没问题但如果这些改动是基于 #4694 里现在的翻译指南来的，我觉得应该先讨论、决定下来一个“正式”版本，合并了之后再做批量格式化的改动，防止万一之后决定下来的格式标准和现在的草稿版本不一致、需要再开PR再修改。
今天晚点我会再给 #4694 提交一个 commit 所以内容会不一样，可以麻烦你给 #4694 提出点意见吗？基本同意、有地方有异议，什么都行。

**Comment by 100gle** [comment]
> Looks good to me but if the changes made in this PR is based on the guideline in #4694, I feel like we should wait until we finalize (the initial version of) the guideline before starting to make formatting PRs, just to make sure we are not going be going back and forth and making wasted effort. In the mean time can I have your opinion on #4694 please? It's still WIP and I'll make another push later today, but any suggestions would be greatly appreciated.
> 
> 改动本身看起来没问题但如果这些改动是基于 #4694 里现在的翻译指南来的，我觉得应该先讨论、决定下来一个“正式”版本，合并了之后再做批量格式化的改动，防止万一之后决定下来的格式标准和现在的草稿版本不一致、需要再开PR再修改。 今天晚点我会再给 #4694 提交一个 commit 所以内容会不一样，可以麻烦你给 #4694 提出点意见吗？基本同意、有地方有异议，什么都行。

@Genteure In actuality, I use [Autocorrect](https://github.com/huacnlee/autocorrect), a linter and formatter tool for CJK content, including markdown, to automatically format the content. Autocorrect has its own rules that enhance the readability of CJK content by improving typography, which may be compatible with [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines).

I recommend using an automated tool like Autocorrect, which provides various plugins for mainstream editors or IDEs. These tools ensure that the content is formatted correctly with appropriate spaces and punctuation. While the guidelines in #4694 regarding concepts like "hydrate" are valuable, they may be less relevant when it comes to formatting and typography. Reviewing every punctuation mark in a PR, similar to source code, can be challenging. Therefore, relying on tools like Prettier, gofmt (for Golang), or Black (for Python) for automatic formatting is more efficient than manual intervention.

实际上，我使用了 [Autocorrect](https://github.com/huacnlee/autocorrect) 这一针对 CJK 内容以及 Markdown 的 Linter 和格式化工具来进行自动地格式化处理。Autocorrect 内置了一些规则通过改善排版以提高 CJK 内容的可读性，这些规则大多数与 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) 相兼容。

我也比较建议用像 Autocorrect 这样为主流编辑器或 IDE 提供了插件支持的自动化工具来确保内容格式化后有着恰当的空格或其他标点。在 #4694 中的指导方案对于像「hydrate」这样的概念名词我觉得好的，但是像标点符号或排版这样其实有些过于琐碎。而且就像源码一样，很难在一个 PR 中事无巨细地去核对每个标点符号或排版是否准确。所以我更希望是用和 Prettier、gofmt（Go 语言）或者 Black（Python） 这样的工具去自动格式化会更高效，而不是手动修改。

**Review by Genteure — APPROVED** [review]
LGTM

I went over the changes again and I don't think it's possible to have a conflict with the draft guideline, so let's get this merged! 👍

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🙌

**Pull request merged**
