### PR TITLE
i18n(es): Update of `api-reference.mdx` and `cli-reference.mdx`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.  Update of `api-reference.mdx` based on this commit 8aae80213ed4346db27d9a031794dd32ce81edbc and `cli-reference.mdx` based on this commit 8aae80213ed4346db27d9a031794dd32ce81edbc

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Quick note: we’ve just merged #2133 and are now using `.mdx` for content. We’ll need to update this PR to apply these changes to the `.mdx` file instead of `.md`.

**Comment by dreyfus92** [comment]
Thanks for the note @delucis

**Review by delucis — COMMENTED** [review]
Sorry I missed this one @dreyfus92!

Noticed there has been one small addition to the API reference since this PR was created: https://github.com/withastro/docs/commit/621b9f00498a8c5f96d839db4abd9fea7f202094#diff-0de04fc4668d94caefab6638b3c81590ebd87b5bc93403ffb5d3d4a98aebeaab

Do you want to add that and we can get this merged?

**Comment by dreyfus92** [comment]
@delucis I've added missing content but had a bit of a struggle with pushing the code because of divergente branches, let me know if it worked.

**Review by delucis — APPROVED** [review]
Ah, that was probably my fault because I updated your branch and didn’t warn you. There were a few auto-format errors that I think I’ve caught them all, so this should be good to go!

**Comment by dreyfus92** [comment]
Thank you so much for the review @delucis 💚

**Pull request merged**
