### PR TITLE
i18n(es): Update `guides/integrations-guide/` `V3`

### PR DESCRIPTION
**Pull request by Waxer59**
#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update `guides/integrations-guide/` `V3` [PR](https://github.com/withastro/docs/pull/4166/files#diff-1103a93a6ea58897df4b7496eef84895e43f61e2475d13b4e712443621d477e0)

### CODE REVIEW

**Review by dreyfus92 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🚀

**Comment by Yan-Thomas** [comment]
Thanks for this peeps, I'll note there have been a few changes to https://github.com/withastro/docs/pull/4166/commits/8f2b8fef73ae43e629f1b6e656e69206e4ee91c7, feel free to tackle this before or after the release PR merging this page happens, this is a considerably small change that won't affect us much, so no worries or rush here! 💜

**Comment by Waxer59** [comment]
Thanks for the heads up! I have sent a PR updating the page. [PR](https://github.com/withastro/docs/pull/4423) @Yan-Thomas

**Pull request merged**
