### PR TITLE
Migrating to Fathom Analytics

### PR DESCRIPTION
**Pull request by tony-sull**
#### What kind of changes does this PR include?

- Something else!

#### Description

- Migrates from GTM to Fathom Analytics.  This is the same GDPR-compliant analytics tool used on the new astro.build site

Bonus: using the same Fathom project allows us to properly track users moving between the landing page and docs site all while respecting user privacy and international requirements 🚀

### CODE REVIEW

**Comment by delucis** [comment]
I’m seeing this error in Chrome Dev Tools: 
image
They link to these docs: <https://web.dev/samesite-cookies-explained/>

Do we need to move the script within docs?

**Comment by matthewp** [comment]
Is that maybe a cookie you have cached? There shouldn't be a `_ga` cookie, that's google analytics. Unless this PR isn't completely removing it.

**Comment by tony-sull** [comment]
Yeah that'd be an existing cookie from the current Google Analytics script, Fathom won't set a `_ga` cookie

Not sure the right way to handle that transition, would it make sense to add a custom header to the Netlify config to delete the cookie?

**Review by delucis — APPROVED** [review]
Ahhh, yup, my bad — testing in an incognito window shows no issues. Not sure we need do anything — those cookies will expire and this was only an issue because Lighthouse was flagging it, not actually causing a problem going forward I don’t think.

LGTM! Thanks so much @tony-sull!

**Pull request merged**
