### PR TITLE
Some fixes in the astro config

### PR DESCRIPTION
**Pull request by JuanM04**
- Removed `mode: 'mdx'` because it's no longer necessary
- Formatted
- Moved `remark-gfm` and `remark-smartypants` to `remarkPlugins`
- Added plugins to package.json

### CODE REVIEW

**Comment by delucis** [comment]
I guess this needs to wait for https://github.com/withastro/astro/pull/3234 to be merged right? Looks like removing `remark-slug` with the current Astro version breaks the heading links (the little link icons next to headings).

Might be a good idea to mark this PR as a draft until it's safe to merge or split it up to apply the slug changes in a later PR?

**Comment by JuanM04** [comment]
@delucis actually, no. If you see the preview, you'll see everything working just fine. That's because that PR only removes extra work but doesn't change any functionality

**Comment by JuanM04** [comment]
@delucis it should be fixed!

**Comment by delucis** [comment]
Yep, looking good now! Thanks for figuring that out.

**Pull request merged**
