### PR TITLE
i18n(ko): Update the outdated ko/project-structure.mdx

### PR DESCRIPTION
**Pull request by sujang958**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Updated `project-structure.mdx`

### CODE REVIEW

**Review by filename24 — APPROVED** [review]
약간 수정된 내용이라 크게 리뷰할게 없어 보이네요

**Comment by sujang958** [comment]
수정했습니다!

**Review by imjlk — APPROVED** [review]
LGTM

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks everyone for the careful review and for the awesome translation 💜

**Pull request merged**
