### PR TITLE
Translation of the deploy file to Spanish

### PR DESCRIPTION
**Pull request by Franqsanz**
#### What kind of changes does this PR include?

- Translated content

#### Description

Added implementation file translation to Spanish

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
Hi @Franqsanz 👋, welcome to the Astro Docs and thanks so much for your contribution. I would love it if you joined us in [our Discord chat](https://astro.build/chat)! 🙌

If you want to be an active i18n contributor, there you can grab the `@i18n-gang-es` role (`#manage-roles` channel) and join our Spanish translation thread, this way you can easily talk with other Spanish i18n contributors, ask for reviews, be aware of when someone needs a review and notify people of the pages you're going to translate to avoid duplicate effort.

You may also want to see [our Translation Status Overview](https://github.com/withastro/docs/issues/438), there you can see the pages that are available to be translated (marked as `i18nReady: true`) and those that need updates.

**Comment by kevinzunigacuellar** [comment]
Bienvenido @Franqsanz 🥳, gracias por la contribución!

**Comment by Yan-Thomas** [comment]
Hi @Franqsanz, I'm really sorry for the delay, just reviewed your PR and LGTM! Welcome to the Docs' Face Pile 🥳, I hope to see you again with more awesome contributions! 🙌

**Comment by Franqsanz** [comment]
Hello @Yan-Thomas , no problem, that's good news.
Thank you very much for accepting my PR, a pleasure to contribute!

**Pull request merged**
