### PR TITLE
[fix] Create new folder and add files for contributor guides

### LINKED ISSUE #3300: Better discoverability of contributing guides
Having a conversation in the `#docs` channel in Discord. We're proposing:

- creating a Contributing directory for all our various kinds of contributing guides
- renaming and moving ALL BUT CONTRIBUTING.md (since that's an expected file people look for)
	- this way, files don't *need* to follow the ALLCAPS.md file format and can actually be more descriptive
	- e.g. Do people know that `RECIPES.md` is a writing guide? :sweat_smile: 
- updating the docs contributing page with the new links, now that locations and filenames have changed
- linking all these other contributing guides in the new directory prominently in CONTRIBUTING.md for discoverability from there.

### PR DESCRIPTION
**Pull request by CBID2**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- Fixes #3300 
- What does this PR change? Give us a brief description.
This PR will make it easier for Astro contributors and maintainers to find contributing guides. 
- Did you change something visual? A before/after screenshot can be helpful.
N/A

### CODE REVIEW

**Comment by sarah11918** [comment]
Hi @CBID2! Here it is, your first PR!

Can you use the file names I suggested though? It looks like you took these from Mark's post, but I had wanted the names that I listed in my post: https://github.com/withastro/docs/issues/3300#issuecomment-1570461906  (Not all of them should have "to docs" at the end)

And, please remove the "closes issue 3300" from the original message, because there's still more for Mark to do with this one! I don't want it closed on him!

Thanks! :raised_hands:

**Comment by CBID2** [comment]
> Hi @CBID2! Here it is, your first PR!
> 
> Can you use the file names I suggested though? It looks like you took these from Mark's post, but I had wanted the names that I listed in my post: [#3300 (comment)](https://github.com/withastro/docs/issues/3300#issuecomment-1570461906) (Not all of them should have "to docs" at the end)
> 
> And, please remove the "closes issue 3300" from the original message, because there's still more for Mark to do with this one! I don't want it closed on him!
> 
> Thanks! 🙌

Hey @sarah11918! :) I made the necessary changes

**Comment by sarah11918** [comment]
Hi @CBID2, oops wrong table! Please use the file names that *I* suggested in that post, not the ones copied from the spreadsheet!  
worsesomehow

**Comment by CBID2** [comment]
> Hi @CBID2, oops wrong table! Please use the file names that *I* suggested in that post, not the ones copied from the spreadsheet!  
> 
> worsesomehow
> 
> 

I made the changes @sarah11918.

**Comment by sarah11918** [comment]
Woo! Looks great now! Just waiting for all the checks to pass, then we can welcome you to Team Docs! (officially... ;) ) :partying_face:

**Pull request merged**
