### PR TITLE
Multiple Environments explanation

### PR DESCRIPTION
**Pull request by MedLeon**
- [ ] Minor content fixes (broken links, typos, etc.)
- [X] New or updated content
- [ ] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

Multiple Environments are not yet supported by Astro, but there is an easy work around. On Discord there are multiple support threads but nothing on this topic can be found yet in the docs.

### CODE REVIEW

**Comment by sarah11918** [comment]
Thanks for submitting this @MedLeon ! I'm marking this for the Technical Steering Committee to confirm as something to document, because sometimes things are undocumented for a reason!

Even if workarounds are successful, when they are not intended as a core Astro feature, they may not supported, or future development issues may not prioritize them.. So, we want to make sure we are setting our readers up for both short-term and long-term success.  😄 

Just wanted to make sure I acknowledged this contribution, and let you know what's happening!

**Comment by MedLeon** [comment]
@sarah11918 Sounds good! 👍🏼

**Comment by MedLeon** [comment]
Hi @sarah11918, 
when do you expect the Technical Steering Committee to review the PR?

**Comment by sarah11918** [comment]
Hi @MedLeon ! I'm sorry, I know there have been some holidays in the last couple of weeks, but I'm going to push for a resolution on this next week!  Thanks for your patience.

**Comment by MedLeon** [comment]
No worries and no rush! 
I was just curious 😀. Thanks for the push!

**Comment by delucis** [comment]
Hi @MedLeon — thanks so much for this! This input was really helpful and triggered some interesting discussion. We’ve checked with the core team how we might want to best tackle this and we’re going to close this for now and hopefully we’ll have a better technical solution instead soon! 🙌

**Pull request closed without merging**
