### PR TITLE
Make search input more noticeable

### PR DESCRIPTION
**Pull request by mayank99**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

Made the search bar pilled shaped and larger, made the language select shorter and truncated. Swapped out the backgrounds between the two.

Fixes (small) part of #618 

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

**Review by delucis — APPROVED** [review]
Nice work @mayank99, looks great! 🙌

**Comment by delucis** [comment]
@Yan-Thomas shared this screenshot of the language select in Chrome (Windows 11) and @sarah11918’s seeing the same in Chrome OS:

Astro docs language drop down with contrast issues

I’m on a Mac and looks OK in both FF & Chrome. Not quite clear what the heuristics are but _might_ be related to switching to a transparent background colour on the dropdown?

**Comment by mayank99** [comment]
@delucis @Yan-Thomas  Oh wow, good catch! Should be fixed now

**Review by delucis — COMMENTED** [review]
Awesome! I have… no way to validate this fix worked, but I’m sure some more evil devices than my own will be along shortly to put this to the test.

FWIW it _still_ LGTM 🙌

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Great job @mayank99 🙌 

Astro Docs' language selection dropdown with proper color contrast

**Comment by sarah11918** [comment]
LGTM, thanks @mayank99!

**Pull request merged**
