### PR TITLE
Make docs styling slightly fancier 💅

### PR DESCRIPTION
**Pull request by delucis**
Following on from #198, this PR proposes theming changes to the docs site to bring it slightly closer to the main astro.build site.

Key changes:

- Use a gradient background. The light and dark variants draw on gradients used on the astro.build home page introducing subtle purples in the light theme and leaning into a night sky blue in the dark theme 🌟 

- In the light theme in particular many of the grey shades now have a subtly purple hue to vibe with the background.

- Code blocks now have a neon-y glow that is particularly visible in the dark theme.

- The dark theme Algolia DocSearch modal has been updated to match.

- The link cards on the Themes page have been tweaked to fit with the other changes.

Obviously this is all just me tinkering, so feel free to push back or reject any or all of this if it doesn’t seem appropriate.

---

cc @natemoo-re @sarah11918 @RafidMuhymin 

Closes #212

### CODE REVIEW

**Comment by FredKSchott** [comment]
I really like this, way more than I ever thought I'd like purple and orange together.

I wonder if we should just embrace full purple? This is some very VERY rough color changing:

#### Before
Screen Shot 2022-03-10 at 9 51 45 PM


#### After
Screen Shot 2022-03-10 at 9 50 44 PM

**Comment by delucis** [comment]
> I wonder if we should just embrace full purple?

Interesting. In a quick round of experiments there are a couple of places I still prefer a splash of orange but for links, a purple could work. I'll keep tweaking 👨‍🔬

**Comment by RafidMuhymin** [comment]
@delucis and @FredKSchott After looking at the example of purple-colored links you provided above, I think the orange-colored links are looking better.

**Comment by RafidMuhymin** [comment]
@delucis and @FredKSchott After looking at the example of purple-colored links you provided above, I think the orange-colored links are looking better.

**Comment by RafidMuhymin** [comment]
@delucis and @FredKSchott After looking at the example of purple-colored links you provided above, I think the orange-colored links are looking better.

**Comment by sarah11918** [comment]
FWIW, Unless they're too annoying to separate out from other links, the active "Learn" and "API" specifically (only?) *could* still be orange, since they are very close to the logo and it works well. (Regardless of what you end up doing with the other links in the sidebar re: purple v orange). It gives a "the active section is orange / the hidden section is the light purple, blend in with the background" vibe.

But, I'm the last person who should be weighing in! 😅 Just wanted to point out that we *could* treat the top two sections there differently, especially if we're still leaning into orange for text links etc.

**Comment by delucis** [comment]
Hi folks!

Spent some time working on a version with purple links so we can see the options head-to-head.

- **Orange:** https://deploy-preview-205--astro-docs-2.netlify.app/

- **Purple:** https://deploy-preview-212--astro-docs-2.netlify.app/

Check out both the dark & light themes. I find the “Frameworks” page pretty useful when testing as it includes most of the possible combos of different text styles if you’re looking for how things add up.

My thoughts:

- In light mode, I marginally prefer purple over orange.

- In dark mode, I actually really miss how well the orange popped.

With zero feedback, I might suggest going with purple for the light theme, but sticking with orange for the dark. (Wild, I know!)

---

Re: @sarah11918’s suggestion, that’s a nice idea. The one issue is that the logo orange doesn’t provide quite enough contrast for text in the light theme, so we end up with the slight mismatch in orange shades, which I don’t love, whereas exactly that resonance is something I love in the dark theme.

image image

That said, whichever way we go a solution like this might also work:

image

**Comment by sarah11918** [comment]
Again, fwiw, slight preference for the purple theme (links in sidebar) in each case BUT with the orange Learn and underline in dark mode, and the orange underline only in light mode.

**Comment by sarah11918** [comment]
I like it! But, I do want to make sure everyone has at least looked at a page with a large code sample in dark mode because... it's A. Choice. (It would totally be MY choice, but I would have wanted to have seen this for myself first, before, "Surprise! It's live!") The one-line on the getting started landing page doesn't quite do it justice.... :)

**Comment by delucis** [comment]
Yes definitely. Do double check before I spill this neon glow all over the production build.

**Comment by delucis** [comment]
I _think_ this is good to merge. Let me know if you see anything that still looks out of place! Thanks all for your feedback and suggestions 🙌

**Comment by sarah11918** [comment]
I've scrolled through every page in dark mode, top to bottom, and nothing jumps out at you (that isn't supposed to jump out at you!)

I suspect if anything, dark mode would be the more problematic one to catch little things, but I'm doing light mode now, then I'll give my sign off on it!

**Comment by sarah11918** [comment]
No surprises in light mode!

**Comment by FredKSchott** [comment]
There's some great work in here that I really don't want to lose or see get stale. I really like this overall direction, so +1 from me! If anyone has feedback post-merge (@natemoo-re I know you didn't get a chance to review) we can always do some follow-up PRs to address.

**Comment by FredKSchott** [comment]
FYI I made some tweaks while I was testing locally, as a part of merging this in: https://github.com/withastro/docs/commit/deb66f550877585b31ca4b9c676573a1aa4924a5

**Pull request merged**
