### PR TITLE
[i18nIgnore] Export function declared in MDX file

### LINKED ISSUE #7302: MDX code example in the Layouts section does not work
### 📚 Subject area/topic

Basics / Layouts

### 📋 Page(s) affected (or suggested, for new content)

- https://docs.astro.build/en/basics/layouts/#importing-layouts-manually-mdx

### 📋 Description of content that is out-of-date or incorrect

Testing out the code sample as shown in the documentation leads to `MDXError: Could not parse expression with acorn`.
The issue seems to be related to the function declaration.
```js 
function fancyJsHelper() {
  return "Try doing that with YAML!";
}
```

According to the [MDX Documentation](https://mdxjs.com/docs/using-mdx/) the function has to be exported. And indeed the following version works:
```js
export function fancyJsHelper() {
  return "Try doing that with YAML!";
}
```

I will create a pull request for the fix.

### 🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)

_No response_

### PR DESCRIPTION
**Pull request by kossidts**
#### Description (required)

As described in issue #7302 the MDX code sample does not work if the declared function is not exported. So this PR fixed the error by exporting the sample function i.e. adding the `export` keyword in front of the function.  

#### Related issues & labels (optional)

- Closes #7302

### CODE REVIEW

**Review by at-the-vr — APPROVED** [review]
LGTM, Great fix 👍

**Review by sarah11918 — APPROVED** [review]
Thank you for this helpful correction! We appreciate you taking the time to contribute and are happy to welcome you to Team Docs! :partying_face:

**Comment by sarah11918** [comment]
!coauthor

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks 🙌

**Pull request merged**
