### PR TITLE
perf(a11y): add searchbox role

### PR DESCRIPTION
**Pull request by kecrily**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [ ] Translated content
- [ ] Changes to the docs site code
- [x] Something else!

#### Description

Aria-label attribute cann't be used on a span with no valid role attribute. So I add `searchbox` role for it.

### CODE REVIEW

**Comment by delucis** [comment]
Thanks! Would you mind explaining how you tested the accessibility with and without the `aria-role`? My understanding is that span receives a default “text container” role.

Firefox’s accessibility tree shows this:

image

And Chrome this:

image

That suggests that at least those browsers are taking the `aria-label` into account. Obviously if the label is missing from screen reader output we should fix that, but we probably need a better role as the text there is describing a shortcut to activate search rather than the `searchbox` input itself.

**Comment by kecrily** [comment]
I used the narrator that comes with Windows for testing. Its presence or absence does not seem to affect the result; the narrator will always read the button role of the previous level.

This issue was reported by [Microsoft's A11y extension](https://accessibilityinsights.io/docs/general/telemetry/).

**Review by delucis — COMMENTED** [review]
Thanks so much for looking into that. Given that, and given the difficulty of finding an appropriate `role`, what do you think of this solution? Move the shortcut label *into* the placeholder span and hide its visibility. So the button is labelled “Search (Press / to search)” and we don’t worry about the `<kbd>` element.

**Comment by delucis** [comment]
Thanks @kecrily! Out of curiosity did you check that this works as expected with your A11y tool?

**Comment by kecrily** [comment]
Yes, now the A11y tool can't find any problems. Astro docs did a great job on the A11y! 🌟

**Review by delucis — APPROVED** [review]
Fantastic. Thanks so much for doing that research and taking the time to work on it 🙌

**Pull request merged**
