### PR TITLE
i18n(es): Update `astro-pages`

### PR DESCRIPTION
**Pull request by dreyfus92**
#### Description (required)

Updated `astro-pages` based on these 3 commits 39eceec0cee0178996d534be6b9778d3e634a0ca, 59c54501c52c0ade3ab488dc0ec94b906ec28758 & d304a59e795adf26c09055c10c976094018de5a9

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Review by Waxer59 — COMMENTED** [review]
Buena PR 🤠, te dejo una sugerencia!

**Comment by dreyfus92** [comment]
Muchas gracias por la revisión @Waxer59 😁

**Review by Waxer59 — APPROVED** [review]
LGTM ✅

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Thanks peeps 🙌

**Pull request merged**
