### PR TITLE
Migrate Docs to Starlight

### PR DESCRIPTION
**Pull request by TheOtterlord**
#### What kind of changes does this PR include?

- Changes to the docs site code

#### What does this PR change?

Migrates Astro docs to Starlight 0.14

Check out the site [Vercel site preview](https://docs-git-fork-theotterlord-starlight-migration-astrodotbuild.vercel.app/en/getting-started) and report any issues you find. **Note: The previous Netlify deploy preview is now outdated**

### CODE REVIEW

**Comment by Genteure** [comment]
Previous next navigation buttons in tutorial pages is not working correctly.

https://astro-docs-migration-preview.netlify.app/zh-cn/tutorial/2-pages/3/
https://astro-docs-migration-preview.netlify.app/pt-br/tutorial/2-pages/3/

Languages with a subtag only have a "Next" button linking to https://astro-docs-migration-preview.netlify.app/en/tutorial/0-introduction
image

https://astro-docs-migration-preview.netlify.app/zh-tw/tutorial/2-pages/3/
https://astro-docs-migration-preview.netlify.app/hi/tutorial/2-pages/3/

Untranslated languages have links to the English version.
image

**Comment by HiDeoo** [comment]
Some feedback I spotted during Talking & Doc'ing:

- Some pages like this [one](https://astro-docs-migration-preview.netlify.app/en/guides/integrations-guide/alpinejs/) do not have sidebar highlighting (feature request tracked in Starlight [here](https://github.com/withastro/starlight/discussions/950))
- Small tutorial checkbox alignment [issue](https://github.com/withastro/docs/assets/494699/a53c105a-2f7b-49c7-80b6-2bb4a64ba1fe) 
- The tutorial steps indicator seems to be [slightly off](https://github.com/withastro/docs/assets/494699/fee0c393-ac07-4431-abee-281ec6799179) text size wise compared to the Figma mockup
- The tutorial tracker step outline [seems](https://github.com/withastro/docs/assets/494699/34df125e-0021-45b1-bcc0-3fcb2589a893) to be using an old color

**Comment by sasoria** [comment]
The contrast in the Island diagram looks great now, thanks 🙌

**Comment by sarah11918** [comment]
Sorry if some of these have already been covered, but here's my handwritten list from Talking and Doc'ing yesterday:
(Also, did not check to design spec, so these are just impressions)

- current docs has an outline on the `<details>` element, and I think I prefer having one
- All the Aside components no longer have their titles transformed to uppercase. I think this makes sense, since not everyone will *want* all caps every time, but we either have re-implement it here to keep all caps all the time, or manually update all content (including the default eg `note` `tip` etc.
- Our current "Checklists" are way more subtle in colour, and with the 3 border outline (I think most of the tutorial components have that outline?) We need to decide whether we want to reimplement the border, and whether these colours seem too shocking for tutorial components.
- The site uses the entirely white only logo in the upper left. I think the version with the coloured flames would fit here?
- The combination of Astro and Docs vs now clearly separated by a line in the top right... do we like this, do we want to get closer to the original (Also, not loving the font for DOCS -- I like how we matched the astro logo font before)
- the `<Badge />` component has such subtle background shading and border. I might like a bit more background distinction on this one as it seems to blend into the text a bit too much?
- Revealed spoiler text - I just have a gut feeling that it should be styled even slightly differently from regular text?
- Our special layouts with grids of icons (migration guide, CMS, deploy) haven't carried over yet
- missing the link for Contributor Guides in the Contribute section of the right sidebar, since this was created after the design spec

**Comment by Genteure** [comment]
I checked navigation buttons for languages with subtag again, they are mostly fixed but there's still a small problem.

Using this page as an example: https://astro-docs-migration-preview.netlify.app/zh-cn/tutorial/2-pages/3/

The Previous is linking to https://astro-docs-migration-preview.netlify.app/zh-CN/tutorial/2-pages/2 , this doesn't break navigation because `/zh-CN/*` gets redirected to `/zh-cn/*` but perhaps those links are taking locales from a different source? (i.e. from config file instead of the page path)

**Comment by sarah11918** [comment]
I can see "Mobile landing page" is still one of the to-do items. Just adding for when we get there that the facepile doesn't seem to be disappearing early enough.

Screenshot 2023-11-20 16 50 35

**Comment by Fryuni** [comment]
Looks so pretty 🤩 

I found a few things that don't seem to have been reported yet.

These are all nits and on Starlight itself, not the use of it in this docs (maybe I should report them there, but I noticed it here)

---
The tabs for multiple package managers are much smaller now and even have a scroll bar.

| Deployed Doc | Image |
|--------|--------|
| New Doc | image |
| Current Doc | image |

---
On those same tabs, there is an inconsistent scroll behavior. If you click on a link on the sidebar, the page immediately jumps to that section with no scroll animation. But if I click on any of those tabs, there is a smooth scroll animation until it is at the top of the page.

The current docs have the scroll animation on either case.

---
Lastly one that is more of a mind thing. It is objectively the opposite of what is happening, but I asked a few people, and they all pointed out the same thing.

On a big screen, larger than the maximum viewport, moving the sidebar to the middle makes the text feel more compressed and cluttered.

The space for the text is slightly bigger with Starlight, but without putting one right above the other, all seven people I asked "Which one shows more of the main content?" chose the current site.

| Deployed Doc | Image |
|--------|--------|
| New Doc | image |
| Current Doc | image |

Maybe this is just from quickly moving between them, and it is something that I'd get used to quite fast, but I share this perception nonetheless.

**Review by ElianCodes — APPROVED** [review]
MERGE IT!

**Review by Yan-Thomas — APPROVED** [review]
I am here for my commit cred, bye

**Comment by doodlemarks** [comment]
houston_lights_intense

**Review by doodlemarks — APPROVED** [review]
YOU DID GOOD

**Comment by n0hack** [comment]
GREAT :rocket::rocket::rocket:

**Comment by VoxelMC** [comment]
This is great, and a massive step for Starlight! Can't wait to get started on the new Glossary :)

**Comment by kevinzunigacuellar** [comment]
Need my gh green square 🟩 😂

**Pull request merged**
