### PR TITLE
i18n(fr): Update `guides/content-collections.mdx` from #8967

### PR DESCRIPTION
**Pull request by thomasbnt**
#### Description (required)
Update `guides/content-collections.mdx` from #8967

#### Related issues & labels (optional)

- Suggested label: i18n

### CODE REVIEW

**Review by ArmandPhilippot — CHANGES_REQUESTED** [review]
Just a small rewording, otherwise LGTM!

**Comment by thomasbnt** [comment]
Thanks @ArmandPhilippot for the small review !

**Review by ArmandPhilippot — APPROVED** [review]
LGTM! Thanks @thomasbnt 🚀

**Review by yanthomasdev — APPROVED** [review]
LGTM! Good work! 🙌

**Pull request merged**
