### PR TITLE
Add guide of deploying static site to Deno Deploy

### PR DESCRIPTION
**Pull request by NanamiNakano**
#### Description

Add guide of deploying static site to Deno Deploy.

Right now the docs only redirect to Deno Deploy's static deployment docs, missing the full guide. This PR adds missing guides.

### CODE REVIEW

**Comment by sarah11918** [comment]
Thank you for adding this helpful content to the docs @NanamiNakano ! 🙌 

We plan to review and test it this week, so we'll be taking a look at it soon!

**Review by casungo — APPROVED** [review]
Looks great! I tested a basic deploy and everything worked.

**Comment by casungo** [comment]
Note: While I approve these changes, I believe a "re-write" of this page should be considered in the future to make it more beginner-friendly and accessible for someone like me, who is trying Deno for the first time (I had heard of it before, but didn't have a reason to install and try it). Notably, `npx astro add deno` installs `@astrojs/deno`, not `@deno/astro-adapter` as outlined in the manual install section, + other things like wording and content organization. Maybe after v5 ;)

**Review by sarah11918 — APPROVED** [review]
Thank you, this looks good @NanamiNakano ! We appreciate you coming to add this, and are happy to welcome you to Team Docs! :partying_face:

**Comment by sarah11918** [comment]
Thank you for your review @casungo ! It's very helpful and yes, down the road we probably could make improvements to this page. :raised_hands:

**Pull request merged**
