### PR TITLE
Fix alias guide to use correct syntax in examples

### PR DESCRIPTION
**Pull request by VodnikAngus**
Hi,
I noticed that the docs have wrong example on using aliases and I wanted to make a quick fix

### CODE REVIEW

**Review by jonathantneal — APPROVED** [review]
Nice fix. Nit, but I think some folks may have wanted the docs to show aliases starting with `@/`. If you want, you can update these to use that. If not, both styles are valid, and if there’s a preference, others can chime in.

**Comment by VodnikAngus** [comment]
I just went by: https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353 where I found how it actually works. I don't really have any preference

**Review by zadeviggers — COMMENTED** [review]
I think that using `@something` for import aliases is the more common practice, so I would recommend we go with that, although I think the current import examples look much cleaner.

I agree with not having the slash after the `@` - I think it looks weird.

**Comment by sarah11918** [comment]
Am I correct that SOMETHING needs to change in the docs, since exactly what's written there didn't work for @VodnikAngus : EITHER the docs example for suggested config needs to change, OR the docs example for import statements syntax needs to change? 

If I have this correct, based on what @zadeviggers contributed on Discord, the options are:

OPTION 1 (change the config example, keep the import syntax)
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "component:": ["src/components/*"],
      "asset:": ["public/assets/*"]
    }
  }
}

---
import Button from 'component:Button';
import logoUrl from 'asset:logo.png';
---
```

OPTION 2 (change the import syntax, keep the config example)
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"]
    }
  }
}

---
import Boilerplate from "@layouts/Boilerplate.astro";
---
```

A. Are these both correct options? (I know there are multiple ways to configure aliases; checking for correctness of each)

B. Which will be our preferred style for the docs, even if both work correctly? Is one "more in keeping" with our style, or what we've suggested elsewhere for other things?

**Comment by VodnikAngus** [comment]
Both are correct you can alias path to literally anything. I used ``@something`` in my PR since that's what I found as a convention online.

**Comment by jonathantneal** [comment]
This PR fixes a discrepancy introduced when the docs were updated to use `@/`, only not completely, introducing the inconsistency. I believe any aforementioned syntax, as long as it is consistent, is supported. Thank you for your attentiveness, @VodnikAngus.

You ask a good question, @sarah11918, which is “what will be our preferred style”. I believe this is worth discussing. To give appropriate time for comment, my preference would be to merge this PR now in order to fix the instruction, and then perform any stylistic changes later, fully realized across the docs.

If you agree, I would need your help to accomplish this, as my contributor abilities are now missing. I’m also pinging @tony-sull, who, as staff, can step in to either pause this PR for a stylistic review, or merge it as-is to be discussed separately. 🙏

Either way, your comments are correct, @VodnikAngus, and thank you for taking the time to fix this for others. 👍

**Comment by sarah11918** [comment]
Then I'm satisfied that correct docs are best docs!

Thanks again, @VodnikAngus and everyone who chimed in, and if we want to suggest different syntax in docs later, we can always change it.

**Pull request merged**
