### PR TITLE
i18n(zh-cn): update `core-concepts/astro-pages.mdx`

### PR DESCRIPTION
**Pull request by 100gle**
#### Description (required)

Added and translated some missing content for `core-concepts/astro-pages.mdx` in `zh-cn`

#### Related issues & labels (optional)

#5205

### CODE REVIEW

**Review by liruifengv — APPROVED** [review]
LGTM. Page partials is a so cool feature!

**Comment by 100gle** [comment]
@Yan-Thomas It has been a long time since you merged the main branch, and you may have forgotten to merge this PR. 👀

**Comment by Yan-Thomas** [comment]
> @Yan-Thomas It has been a long time since you merged the main branch, and you may have forgotten to merge this PR. 👀

OOPS 😆

**Review by Yan-Thomas — APPROVED** [review]
LGTM! Good work peeps 🙌

**Pull request merged**
