### PR TITLE
Replace image with translatable IslandsDiagram

### PR DESCRIPTION
**Pull request by hippotastic**
#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [X] New or updated content
- [ ] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

- Replaces the static islands architecture image with our new, accessible `IslandsDiagram` component, allowing its contents to be translated in i18n versions of the page.

### CODE REVIEW

**Review by delucis — APPROVED** [review]
LGTM!

**Comment by hippotastic** [comment]
Just a note for the person merging this: This will cause my German version of partial-hydration.md to switch to "needs updating" even though it introduced the component in the first place. 😅

If you want to go the extra mile, you can prevent this from happening by editing the JSON state data in the translation status overview issue BEFORE merging this PR and setting `de` -> `core-concepts/partial-hydration.md` -> `lastMajorChange` a bit into the future, e.g. to: `2022-05-18T10:00:00.000Z`

**Comment by sarah11918** [comment]
OR... @hippotastic makes a trivial change to "update" the German page... 😅 

But this looks great! Fantastic contribution, Hippo!

**Comment by hippotastic** [comment]
Yeah, I can do that too, of course! A trivial "major" update. 😄

**Comment by Yan-Thomas** [comment]
I did some tests with NVDA and it looks great. Amazing job! 🚀

**Comment by delucis** [comment]
I **LOVE** that you've been doing that a11y testing @Yan-Thomas! Thank you!

**Comment by sarah11918** [comment]
Alright @hippotastic , if that time code messed anything up, it's on you! Here we go....

**Comment by hippotastic** [comment]
Nope, it worked perfectly! Thanks for carefully editing the right spot, @sarah11918! 😄

**Pull request merged**
