### PR TITLE
ci: update reference docs

### PR DESCRIPTION
**Pull request by fredkbot**
This PR is auto-generated by a nightly GitHub action to update the reference docs from source code in withastro/astro.

### CODE REVIEW

**Comment by delucis** [comment]
Same here @mrienstra — sorry! #1777 updated the config reference but that gets automatically generated from <https://github.com/withastro/astro/blob/main/packages/astro/src/%40types/astro.ts>

**Comment by delucis** [comment]
Ah, this one we can hang onto for a bit longer. No significant changes upstream just yet.

**Comment by mrienstra** [comment]
@delucis, I just opened https://github.com/withastro/astro/pull/5204, so no worries about overwriting those changes. 👍

**Comment by delucis** [comment]
Thanks @mrienstra! Merged that, so tomorrow the CI will run and this PR should be no more! 🎉 

(Or I guess maybe it’ll pull in other changes — either way we’ll get to keep the `#` links.)

**Review by delucis — APPROVED** [review]
Nice `alternative extension` to this sentence 🚀

**Pull request merged**
