### PR TITLE
i18n(zh-cn): update some docs from 4.14

### PR DESCRIPTION
**Pull request by liruifengv**
#### Description (required)

update some docs from 4.14

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9081
- https://github.com/withastro/docs/pull/9108

### CODE REVIEW

**Comment by yanthomasdev** [comment]
This LGTM, we just have to update `integrations-guide/vercel.mdx` before updating since a new change was added: https://github.com/withastro/docs/commit/2e42082f67dcf3fb4139c7bc8c66144f3548dd28

**Comment by liruifengv** [comment]
Thank you @yanthomasdev I've updated it.

**Review by Nin3lee — APPROVED** [review]
LGTM!

**Review by yanthomasdev — APPROVED** [review]
LGTM! Amazing work!

**Pull request merged**
