### PR TITLE
i18n(pt-br): added missing options of Experimental Flags

### PR DESCRIPTION
**Pull request by jeffdrumgod**
#### Description (required)

Added missing options of Experimental Flags for pt-br locale:
- experimental.clientPrerender
- experimental.globalRoutePriority
- experimental.i18nDomains

---

Discord user: jeff_drumgod

### CODE REVIEW

**Comment by Yan-Thomas** [comment]
Thanks @jeffdrumgod, in case of outdated translations like this we like to have the entire page updated in the PR (vs. a few sections) so we have a predictable way to track its outdated/updated status using Lunaria. Would you be up to the task? https://github.com/withastro/docs/commits/main/src/content/docs/en/reference/configuration-reference.mdx?since=2024-01-08T19:08:58.000Z

**Comment by jeffdrumgod** [comment]
Sure @Yan-Thomas ! I can try.
But before proceeding, I wonder if there is any mechanism in place to indicate who may have already undertaken the task of translating a page, to prevent duplication of effort by multiple people. Translating an entire page requires considerable effort, and it would be disheartening to discover that someone else has completed the same work just minutes before your submission.

**Comment by Fryuni** [comment]
> I wonder if there is any mechanism in place to indicate who may have already undertaken the task of translating a page

The Portuguese translation thread on Discord is where you can coordinate your efforts with others

**Comment by Yan-Thomas** [comment]
> But before proceeding, I wonder if there is any mechanism in place to indicate who may have already undertaken the task of translating a page, to prevent duplication of effort by multiple people. Translating an entire page requires considerable effort, and it would be disheartening to discover that someone else has completed the same work just minutes before your submission.

As Fryuni said above, the best place is [our Discord](https://astro.build/chat), there we have an `#docs-i18n` channel with threads for each language available for translation where people coordinate their effort. No one has claimed this page before yet, so you're free to proceed with no worry. 🙌

**Comment by jeffdrumgod** [comment]
Great! I will prepare the mission to help translate all the pages :) Please ignore this PR, I will send a new one as soon

**Pull request closed without merging**
