### PR TITLE
fix(routing): document priority of redirects

### PR DESCRIPTION
**Pull request by ematipico**
#### Description (required)

This PR fixes an issue where we should have mentioned the priority of redirects.

Source: https://github.com/withastro/roadmap/blob/main/proposals/0041-redirects.md#routing-priority

#### Related issues & labels (optional)

- Closes https://github.com/withastro/astro/issues/11412

### CODE REVIEW

**Comment by sarah11918** [comment]
See what you think of this, @ematipico !

**Comment by ematipico** [comment]
Looks good @sarah11918 !

**Comment by sarah11918** [comment]
@ematipico Great! I think this can go live to close an issue, so we'll add it into our bucket to merge! :raised_hands:

**Review by sarah11918 — APPROVED** [review]
Thank you! Helpful addition to docs!

**Review by yanthomasdev — APPROVED** [review]
LGTM!

**Pull request merged**
