### PR TITLE
i18n(zh-tw): update `manual.mdx` translation

### PR DESCRIPTION
**Pull request by mingjunlu**
#### Description

- Updates Traditional Chinese translation of `src/content/docs/zh-tw/install/manual.mdx`

#### Related issues & labels

- ~~Closes #~~
- Suggested label: i18n

### CODE REVIEW

**Comment by liruifengv** [comment]
As https://github.com/withastro/docs/pull/7135, `create-astro` is now `create astro`.

This page also has some text from code samples that can be translated

**Comment by mingjunlu** [comment]
> As #7135, `create-astro` is now `create astro`.
> 
> This page also has some text from code samples that can be translated

Thanks! I've [changed `create-astro` to `create astro`](https://github.com/withastro/docs/pull/7139/commits/9246d6fbb7e72f5a90ea8c8ae0eb2fa6d4f7b913) and [translated some untranslated contents](https://github.com/withastro/docs/pull/7139/commits/c1f6f08309d6302278e85ece1b0ffefb4bbbf0ba).

**Review by liruifengv — APPROVED** [review]
LGTM. Thanks @mingjunlu

**Review by dreyfus92 — APPROVED** [review]
Thank you peeps, LGTM ✅

**Pull request merged**
