### PR TITLE
[i18nIgnore] Delete comparisons page & lighthouse audits

### PR DESCRIPTION
**Pull request by delucis**
#### What kind of changes does this PR include?

- New or updated content

#### Description

- Deletes the old unmaintained `comparing-astro-vs-other-tools` pages
- Deletes the Lighthouse audits they linked to
- Adds redirects for both of these sets of deleted content to redirect to `guides/migrate-to-astro`

### CODE REVIEW

**Comment by Princesseuh** [comment]
This unlocks `astro check` in CI 👀

**Comment by delucis** [comment]
> This unlocks `astro check` in CI 👀

It does?!

**Comment by Princesseuh** [comment]
> > This unlocks `astro check` in CI 👀
> 
> It does?!

Yes! `astro check` does not support ignoring files, and those files would majorly trip it due to the huge minified script tags (maybe there was a way to fix it, but I didn't explore it)

**Review by Yan-Thomas — APPROVED** [review]
Goodbye page and lighthouse audits, welcome faster builds and `astro check`! 🥳

**Comment by delucis** [comment]
Thanks for patching this up @Yan-Thomas! Wave good bye to these pages 🥳 

@Princesseuh Do you want to open a PR to add `astro check` to our CI workflows?

**Comment by Princesseuh** [comment]
> Thanks for patching this up and remembering to add the `i18nIgnore` tag, @Yan-Thomas! Wave good bye to these pages 🥳
> 
> @Princesseuh Do you want to open a PR to add `astro check` to our CI workflows?

I can do! Though it won't pass

**Comment by delucis** [comment]
Do you remember how close we were to passing last time? Maybe this is the motivation for me to go through and cleanup type errors.

**Pull request merged**
